### ISSUE TITLE
The displayed title contains `#`

### ISSUE THREAD

**Issue by L-Super** [CaiJimmy/hugo-theme-stack#1004]
### What happened?

The displayed title contains `#`, this is different from the previous display
![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/40905056/def1204d-bbd4-4ef2-b520-93f757c7c577)

### Hugo version

v0.124.1

### Theme version

v3.25.0

### What browsers are you seeing the problem on?

Microsoft Edge

### More information about the browser

Windows11，Android

### Link to Minimal Reproducible Example

https://demo.stack.jimmycai.com/p/markdown-syntax-guide/#paragraph

**Comment by thangbuiq** [comment]
+1
Is there any option to turn off the `#` before every heading? @CaiJimmy

**Comment by matthews84** [comment]
+1
I have the same problem

**Comment by CaiJimmy** [comment]
Sorry for the late reply, I'll add an option to this feature when I have more time.

**Comment by getvictor** [comment]
By default, the `#` should only be visible on hover, like here: https://stack.jimmycai.com/config/image-processing#cover

**Comment by CaiJimmy** [comment]
Should be fixed now with #1016, heading anchor can be enabled with the `article.headingAnchor` parameter.
