### ISSUE TITLE
Why does the tutorial on the hugo website suggest to put it in the posts file, but this theme is in the posts folder?

### ISSUE THREAD

**Issue by huhu415** [CaiJimmy/hugo-theme-stack#1013]
### What happened?

The hugo official [tutorial](https://gohugo.io/getting-started/quick-start/) shows that it's in the posts. I thought all themes were in posts, asked about the difference, and it took me 3h to deug
![IMG_4278](https://github.com/CaiJimmy/hugo-theme-stack/assets/93107032/1cc74883-8b80-4773-b1a7-83a54e6fcfda)

### Hugo version

0.125

### Theme version

least

### Link to Minimal Reproducible Example

https://github.com/CaiJimmy/hugo-theme-stack

**Comment by duan-1** [comment]
post 和 posts 的区别并不大，你喜欢用哪一个就用哪一个即可
