### ISSUE TITLE
Some math formulas can not be displayed

### ISSUE THREAD

**Issue by pixelock** [CaiJimmy/hugo-theme-stack#1019]
### What happened?

I published a blog with lots of block math. Strangely, some of them can not be showed properly.

A test blog is published to show this problem: https://pixelock.github.io/p/math-typesetting/

![WX20240513-135118](https://github.com/CaiJimmy/hugo-theme-stack/assets/95493953/dccb69ec-a1d5-42e1-be52-c970ab17763d)

Two blocks are not showed correctly. Details in .md

```markdown
$$
\begin{aligned}
& \mathbf{q}_t = W_Q \mathbf{h}_t \\
& \mathbf{k}_t = W_K \mathbf{h}_t \\
& \mathbf{v}_t = W_V \mathbf{h}_t
\end{aligned}
$$
在 MHA 中, $\mathbf{q}_t, \mathbf{k}_t, \mathbf{v}_t$ 被拆分为 $n_h$ 个 heads, 然后每个 head 中进行 attention 计算:

$$
\mathbf{q}_t + \mathbf{q}_{1}
$$

每个 head 计算得到的结果再拼接起来, 经过参数矩阵 $W_O \in \mathbb{R}^{d \times d_h n_h}$ 得到 MHA 的输出张量.

$$
\begin{aligned}
& {\left[\mathbf{q}_{t, 1} ; \mathbf{q}_{t, 2} ; \ldots ; \mathbf{q}_{t, n_h}\right]=\mathbf{q}_t,} \\
& {\left[\mathbf{k}_{t, 1} ; \mathbf{k}_{t, 2} ; \ldots ; \mathbf{k}_{t, n_h}\right]=\mathbf{k}_t,} \\
& {\left[\mathbf{v}_{t, 1} ; \mathbf{v}_{t, 2} ; \ldots ; \mathbf{v}_{t, n_h}\right]=\mathbf{v}_t,} \\
& \mathbf{o}_{t, i}=\sum_{j=1}^t \operatorname{Softmax}_j\left(\frac{\mathbf{q}_{t, i}^T \mathbf{k}_{j, i}}{\sqrt{d_h}}\right) \mathbf{v}_{j, i}, \\
& \mathbf{u}_t=W^O\left[\mathbf{o}_{t, 1} ; \mathbf{o}_{t, 2} ; \ldots ; \mathbf{o}_{t, n_h}\right]
\end{aligned}
$$
```
same latex math code can be show properly in another blog pubulish framework, so the math code itself is correct:

![WX20240513-135439](https://github.com/CaiJimmy/hugo-theme-stack/assets/95493953/afc5f3e0-0598-4276-a17f-e660ae6155a2)

Can you help to find the cause of this problem, thx!

### Hugo version

0.125.7

### Theme version

3.26.0

### What browsers are you seeing the problem on?

Chrome

### Link to Minimal Reproducible Example

https://github.com/pixelock/blogtest

**Comment by pixelock** [comment]
I find that either inline math or block math containing `_{` or `\{` will cause this problem.

How to fix it?

> ### What happened?
> I published a blog with lots of block math. Strangely, some of them can not be showed properly.
> 
> A test blog is published to show this problem: https://pixelock.github.io/p/math-typesetting/
> 
> ![WX20240513-135118](https://private-user-images.githubusercontent.com/95493953/329936849-dccb69ec-a1d5-42e1-be52-c970ab17763d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODI0MjUsIm5iZiI6MTcxNTU4MjEyNSwicGF0aCI6Ii85NTQ5Mzk1My8zMjk5MzY4NDktZGNjYjY5ZWMtYTFkNS00MmUxLWJlNTItYzk3MGFiMTc3NjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA2MzUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMWFiZTc3MGEwZWE3NjMyNjY2MDU2ZjJiMTJhMGM5MDFmZDEwYjUwZGEwMmM3MzA3YjU5YmE3OTYzMWE4ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V4KRm0H7iIAbp0nibyhysn14Cu0IbuaGy_p-bkMe1AE)
> 
> Two blocks are not showed correctly. Details in .md
> 
> ```
> $$
> \begin{aligned}
> & \mathbf{q}_t = W_Q \mathbf{h}_t \\
> & \mathbf{k}_t = W_K \mathbf{h}_t \\
> & \mathbf{v}_t = W_V \mathbf{h}_t
> \end{aligned}
> $$
> 在 MHA 中, $\mathbf{q}_t, \mathbf{k}_t, \mathbf{v}_t$ 被拆分为 $n_h$ 个 heads, 然后每个 head 中进行 attention 计算:
> 
> $$
> \mathbf{q}_t + \mathbf{q}_{1}
> $$
> 
> 每个 head 计算得到的结果再拼接起来, 经过参数矩阵 $W_O \in \mathbb{R}^{d \times d_h n_h}$ 得到 MHA 的输出张量.
> 
> $$
> \begin{aligned}
> & {\left[\mathbf{q}_{t, 1} ; \mathbf{q}_{t, 2} ; \ldots ; \mathbf{q}_{t, n_h}\right]=\mathbf{q}_t,} \\
> & {\left[\mathbf{k}_{t, 1} ; \mathbf{k}_{t, 2} ; \ldots ; \mathbf{k}_{t, n_h}\right]=\mathbf{k}_t,} \\
> & {\left[\mathbf{v}_{t, 1} ; \mathbf{v}_{t, 2} ; \ldots ; \mathbf{v}_{t, n_h}\right]=\mathbf{v}_t,} \\
> & \mathbf{o}_{t, i}=\sum_{j=1}^t \operatorname{Softmax}_j\left(\frac{\mathbf{q}_{t, i}^T \mathbf{k}_{j, i}}{\sqrt{d_h}}\right) \mathbf{v}_{j, i}, \\
> & \mathbf{u}_t=W^O\left[\mathbf{o}_{t, 1} ; \mathbf{o}_{t, 2} ; \ldots ; \mathbf{o}_{t, n_h}\right]
> \end{aligned}
> $$
> ```
> 
> same latex math code can be show properly in another blog pubulish framework, so the math code itself is correct:
> 
> ![WX20240513-135439](https://private-user-images.githubusercontent.com/95493953/329937478-afc5f3e0-0598-4276-a17f-e660ae6155a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODI0MjUsIm5iZiI6MTcxNTU4MjEyNSwicGF0aCI6Ii85NTQ5Mzk1My8zMjk5Mzc0NzgtYWZjNWYzZTAtMDU5OC00Mjc2LWExN2YtZTY2MGFlNjE1NWEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA2MzUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NDc1YzAxYjliYmZiZTAxMWZkY2I5ZmMzNjAzMjM5ZTYxODA1MjNhZjE2MTU5MzA1YWUwMGU3N2U2YmVkMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.apAG17S032hktHOw2ksNmuX3dapPkKxEAuZlkFdodbo)
> 
> Can you help to find the cause of this problem, thx!
> 
> ### Hugo version
> 0.125.7
> 
> ### Theme version
> 3.26.0
> 
> ### What browsers are you seeing the problem on?
> Chrome
> 
> ### More information about the browser
> _No response_
> 
> ### Relevant log output
> _No response_
> 
> ### Link to Minimal Reproducible Example
> https://github.com/pixelock/blogtest

**Comment by pixelock** [comment]
s\_{j, t} \mid 1 \leqslant j \leqslant N_r

**Comment by pixelock** [comment]
I find that either inline math or block math with `_{` or `\{` will cause this problem.

How to fix it?

**Comment by nonotran68** [comment]
@pixelock alright, i think some features in this theme is kinda... outdated :) 
you can find fix in https://gohugo.io/content-management/mathematics/

**Comment by pixelock** [comment]
> @pixelock alright, i think some features in this theme is kinda... outdated :) you can find fix in https://gohugo.io/content-management/mathematics/

i'll try. thanks for helping!

**Comment by lovelock** [comment]
> @pixelock alright, i think some features in this theme is kinda... outdated :) you can find fix in https://gohugo.io/content-management/mathematics/

I've added config files by following the two steps and it works, thanks

**Comment by CaiJimmy** [comment]
I have added this configuration to the starter template so it will work in the future, thanks for all the feedback!
