### ISSUE TITLE
主题实用的旧版本v2 Waline在更新到新版Waline V3后报错

### ISSUE THREAD

**Issue by lin-snow** [CaiJimmy/hugo-theme-stack#1023]
### What happened?

主题实用的旧版本v2 Waline在更新到新版Waline V3后报错。新版本的Chrome 和Edge会导致主题的左侧边栏出现一条无法消除的滚动条

### Hugo version

lastest

### Theme version

lastest

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

latest,latest

### Link to Minimal Reproducible Example

https://github.com/CaiJimmy/hugo-theme-stack

**Comment by CaiJimmy** [comment]
抱歉，我不用 Waline，没有办法修复和复现这个 Bug，只能停留在 v2 版本了。
