### ISSUE TITLE
Author not displayed on demo site

### ISSUE THREAD

**Issue by getvictor** [CaiJimmy/hugo-theme-stack#1028]
### What happened?

The author is not displayed on the demo site: https://demo.stack.jimmycai.com/p/markdown-syntax-guide/

Even though the top matter has it:
```
+++
author = "Hugo Authors"
title = "Markdown Syntax Guide"
```

### Hugo version

See demo site

### Theme version

See demo site

### What browsers are you seeing the problem on?

Chrome

### Link to Minimal Reproducible Example

https://demo.stack.jimmycai.com/p/markdown-syntax-guide/

**Comment by getvictor** [comment]
Also, the authors need to be added to OpenGraph in `opengraph/provider/base.html` like:
```
{{ range .Param "authors" }}
<meta property='article:author' content='{{ . }}' />
{{ end -}}
```

**Comment by CaiJimmy** [comment]
Hi, sorry for the late reply!

> The author is not displayed on the demo site: https://demo.stack.jimmycai.com/p/markdown-syntax-guide/
> Even though the top matter has it:

That's actually because I copied the sample site files from Hugo without modifying them 😥. This template does not have multi-author support, so I don't think we need to add support for that parameter. 

Thanks again for pointing that out.
