### ISSUE TITLE
Extra blank on the right side.

### ISSUE THREAD

**Issue by h4ck4t** [CaiJimmy/hugo-theme-stack#1030]
### What happened?

I've got extra blank on the right side, while the demo site doesn't.
![屏幕截图 2024-06-10 121802](https://github.com/CaiJimmy/hugo-theme-stack/assets/116735067/bff10455-f6a5-476d-9854-91b3bdc07f08)
![屏幕截图 2024-06-10 121943](https://github.com/CaiJimmy/hugo-theme-stack/assets/116735067/bfab87ba-572e-46dd-9959-235432988559)

### Hugo version

hugo v0.126.1-3d40aba512931031921463dafc172c0d124437b8+extended windows/amd64 BuildDate=2024-05-15T10:42:34Z VendorInfo=gohugoio

### Theme version

3.26.0

### What browsers are you seeing the problem on?

Firefox

### More information about the browser

None

### Link to Minimal Reproducible Example

None

**Comment by CaiJimmy** [comment]
Closing this issue as there is no way for me to reproduce this without an example.
