### ISSUE TITLE
Support localized date format

### ISSUE THREAD

**Issue by weeix** [CaiJimmy/hugo-theme-stack#1040]
### What happened?

After setting the `defaultContentLanguage` parameter in *hugo.yaml*, most parts of the website were localized. However, the dates in the articles were not localized.

May I create a pull request to address this?

### Hugo version

0.128.1

### Theme version

3.26.0

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

Chrome 127, Windows 11

### Link to Minimal Reproducible Example

https://github.com/CaiJimmy/hugo-theme-stack-starter

**Comment by CaiJimmy** [comment]
Thanks!
