### ISSUE TITLE
Error when running hugo server -D

### ISSUE THREAD

**Issue by irfanirawansukirman** [CaiJimmy/hugo-theme-stack#105]
**Describe the bug**
Start building sites … 
ERROR 2020/12/31 05:27:33 render of "page" failed: execute of template failed: template: _default/single.html:4:12: executing "_default/single.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/irfanirawansukirman/Documents/personal_projects/8droid/themes/stack/layouts/partials/helper/image.html:27:31": execute of template failed: template: partials/helper/image.html:27:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
ERROR 2020/12/31 05:27:33 render of "section" failed: execute of template failed: template: _default/list.html:4:12: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/irfanirawansukirman/Documents/personal_projects/8droid/themes/stack/layouts/partials/helper/image.html:27:31": execute of template failed: template: partials/helper/image.html:27:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
ERROR 2020/12/31 05:27:33 render of "taxonomy" failed: execute of template failed: template: _default/list.html:4:12: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/irfanirawansukirman/Documents/personal_projects/8droid/themes/stack/layouts/partials/helper/image.html:27:31": execute of template failed: template: partials/helper/image.html:27:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
ERROR 2020/12/31 05:27:33 render of "taxonomy" failed: execute of template failed: template: _default/list.html:4:12: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/irfanirawansukirman/Documents/personal_projects/8droid/themes/stack/layouts/partials/helper/image.html:27:31": execute of template failed: template: partials/helper/image.html:27:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
Built in 69 ms
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:4:12: executing "index.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/irfanirawansukirman/Documents/personal_projects/8droid/themes/stack/layouts/partials/helper/image.html:27:31": execute of template failed: template: partials/helper/image.html:27:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
irfanirawansukirman@Irfans-MacBook-Pro-2 8droid % 
irfanirawansukirman@Irfans-MacBook-Pro-2 8droid % hugo server -D
Start building sites … 
ERROR 2020/12/31 05:27:37 render of "taxonomy" failed: execute of template failed: template: _default/list.html:4:12: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/irfanirawansukirman/Documents/personal_projects/8droid/themes/stack/layouts/partials/helper/image.html:27:31": execute of template failed: template: partials/helper/image.html:27:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
ERROR 2020/12/31 05:27:37 render of "page" failed: execute of template failed: template: _default/single.html:4:12: executing "_default/single.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/irfanirawansukirman/Documents/personal_projects/8droid/themes/stack/layouts/partials/helper/image.html:27:31": execute of template failed: template: partials/helper/image.html:27:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
ERROR 2020/12/31 05:27:37 render of "home" failed: execute of template failed: template: index.html:4:12: executing "index.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/irfanirawansukirman/Documents/personal_projects/8droid/themes/stack/layouts/partials/helper/image.html:27:31": execute of template failed: template: partials/helper/image.html:27:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
ERROR 2020/12/31 05:27:37 render of "taxonomy" failed: execute of template failed: template: _default/list.html:4:12: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/irfanirawansukirman/Documents/personal_projects/8droid/themes/stack/layouts/partials/helper/image.html:27:31": execute of template failed: template: partials/helper/image.html:27:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
Built in 46 ms
Error: Error building site: failed to render pages: render of "section" failed: execute of template failed: template: _default/list.html:4:12: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/irfanirawansukirman/Documents/personal_projects/8droid/themes/stack/layouts/partials/helper/image.html:27:31": execute of template failed: template: partials/helper/image.html:27:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil

**To Reproduce**
If you do not have git installed, you can download the archive of the latest version of this theme from: https://github.com/CaiJimmy/hugo-theme-stack/archive/master.zip
Extract that .zip file to get a “gohugo-theme-stack-master” directory.
Rename that directory to “stack”, and move it into the “themes/” directory.

**Expected behavior**
Implementation hugo theme

**Comment by CaiJimmy** [comment]
Have you copied `config.yaml` from `exampleSite` to Hugo site folder?

https://docs.stack.jimmycai.com/getting-started

**Comment by GAGANsinghmsitece** [comment]
I'm also getting same error even after  copying `config.yaml` to site folder

**Comment by CaiJimmy** [comment]
Try to copy all contents from `exampleSite` to your site folder. 

And, check if your Hugo version meets the requirements (>= 0.78).

**Comment by zishanq** [comment]
Hi @CaiJimmy,
I am also facing the same issue, I am in 0.79 version

**Comment by CaiJimmy** [comment]
Please give more information about this issue. 
Ej. source code or screenshot of the folder structure.

**Comment by zishanq** [comment]
![image](https://user-images.githubusercontent.com/57523874/103437395-97d9c900-4c27-11eb-9b0f-0bddb98ed41e.png)
![image](https://user-images.githubusercontent.com/57523874/103437399-ad4ef300-4c27-11eb-90e5-7f192af399a8.png)

When I try to run hugo server, I have this error
Thank you for your help

**Comment by CaiJimmy** [comment]
Remove config.toml

**Comment by zishanq** [comment]
@CaiJimmy you rocks! Thank you

**Comment by GijuAhn** [comment]
'**$hugo new site projectName**' makes default **config.toml**
After remove it, works well. thanks!
