### ISSUE TITLE
Wrong redirection on search widget + missing i18n

### ISSUE THREAD

**Issue by cobalto** [CaiJimmy/hugo-theme-stack#106]
**Describe the bug**
After changing the default path/slug of the **search** page, the search widget on the sidebar keep redirecting to the default "search" page.

**To Reproduce**
1. Go to the home page
2. Search anything on the sidebar search widget
3. Site will redirect to the 404 page
4. Address bar will show the default page path

**Expected behavior**
Form action send the search to the current search page instead of default address.
Since it's the widget form error, the search page works just fine.
Aditionaly, the search partials have a i18n missing.
**I KNOW I can change all of this manually, but I think it will be nice to have this kind of thing set with just parameterization**

### Screenshots

Search on widget
![image](https://user-images.githubusercontent.com/1196314/103410598-d188d200-4b4a-11eb-85fb-506d59b67fc4.png)

Wrong redirection
![image](https://user-images.githubusercontent.com/1196314/103410616-e1081b00-4b4a-11eb-8b4f-72597158538a.png)

Same search directly on the search page
![image](https://user-images.githubusercontent.com/1196314/103410631-f0876400-4b4a-11eb-99dd-26ef36740d2f.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any, really.
 - Version: Any, yeah yeah

### Additional context

**My setup:**
```bash
# config.yaml
menu:
  - identifier: busca
    name: Busca
    url: busca
    weight: -60
    pre: search
```

```bash
# content/page/busca.md
---
title: "Busca"
slug: "busca"
layout: "search"
outputs:
    - html
    - json
---
```

### ~stack/layouts/partials/widget/search.html
![~stack/layouts/partials/widget/search.html](https://user-images.githubusercontent.com/1196314/103411236-ac499300-4b4d-11eb-8410-569a1697c2c3.png)
* Line 1: The `action="/search"` is hardcoded.
* Line 6: Missing i18n.

### ~stack/layouts/page/search.html
![~stack/layouts/page/search.html](https://user-images.githubusercontent.com/1196314/103411409-9092bc80-4b4e-11eb-8cdd-1289cc8ef59d.png)
* Line 14: Missing i18n.

### Final Notes
Sorry for making everything as a issue instead of PR, at least the translations.
Thanks for the awesome theme and *_Happy New Year_*, Jimmy 🍾🎆

**Comment by CaiJimmy** [comment]
Happy New Year too! ✨

> I KNOW I can change all of this manually, but I think it will be nice to have this kind of thing set with just parameterization

I've got something better. The theme will automatically detect the path to the search page. I will bring this change soon to the archive and search widget.
