### ISSUE TITLE
分类使用背景后会被糊上一个背景色

### ISSUE THREAD

**Issue by xiahuaijia** [CaiJimmy/hugo-theme-stack#1064]
### What happened?

预期应该显示为
![image](https://github.com/user-attachments/assets/39a1c00b-2b23-454d-a728-dadba3319131)

现在错误的显示为
![image](https://github.com/user-attachments/assets/2bd4c6af-8a60-4e6f-839c-e3deb4a27f45)

创建一个全新站点可以重现该问题, 不知这个是主题的设计还是主题的bug.

根据git提交记录找到在 b03390d237427a2b9cfee55949cb1da62f1a6856  `assets/ts/main.ts` 文件中第 50 行 这里添加了颜色蒙版

```
articleDetails.style.background = `
                        linear-gradient(0deg, 
                            rgba(${colors.DarkMuted.rgb[0]}, ${colors.DarkMuted.rgb[1]}, ${colors.DarkMuted.rgb[2]}, 0.5) 0%, 
                            rgba(${colors.Vibrant.rgb[0]}, ${colors.Vibrant.rgb[1]}, ${colors.Vibrant.rgb[2]}, 0.75) 100%)`;
```

> Revert "Merge branch 'canary' into master (#711)"
> 
> This reverts commit 8a597a5c9c861d2bce22a5e06c7667cd9c8e263a.

### Hugo version

hugo v0.134.1-2f89169baa87a9db47e288b60705f4e99e21a945+extended windows/amd64

### Theme version

git 048a000f1701a1bd75df54ae2a0f8288f07fbc88

### What browsers are you seeing the problem on?

Chrome

### Link to Minimal Reproducible Example

https://github.com/CaiJimmy/hugo-theme-stack

**Comment by CaiJimmy** [comment]
> 不知这个是主题的设计还是主题的bug.

对的，这个是主题的设计。
