### ISSUE TITLE
Page/Tab Title says "Pager # - Site Title" instead of "Page"

### ISSUE THREAD

**Issue by mozziemozz** [CaiJimmy/hugo-theme-stack#1071]
### What happened?

Hi, the site/tab title says "Pager #" instead of "Page #" is that intentional or a typo?

![image](https://github.com/user-attachments/assets/8f2976ad-9afd-4fbe-ba91-46f43a13f238)

### Hugo version

0.135.0

### Theme version

3.27.0

### What browsers are you seeing the problem on?

Microsoft Edge

### More information about the browser

Edge 129.0.2792.79, Windows 11 24H2

### Link to Minimal Reproducible Example

https://heusser.pro/page/2/

**Comment by CaiJimmy** [comment]
> the site/tab title says "Pager #" instead of "Page #" is that intentional or a typo?

That's the default output of Hugo paginator: https://github.com/CaiJimmy/hugo-theme-stack/blob/2a18a92901e2689c23ff340c380a164a88208d78/layouts/partials/data/title.html#L15, you can do a string replace if you wish.

**Comment by mozziemozz** [comment]
Thanks for your reply, I'll take a look at it.

**Comment by markmonroy** [comment]
@mozziemozz Can you please tell me how you implemented this? I've been trying for hours to figure out where exactly in title.html I need to put the replace function. Just piping it into the line @CaiJimmy  highlighted above doesn't seem to do anything. Thanks!!

**Comment by mozziemozz** [comment]
I just made a PowerShell script that loops through all the html files of the build directory and replaces "<title>Pager" with "<title>Page".

**Comment by markmonroy** [comment]
Oh brilliant, that worked! Thanks @CaiJimmy .

In case it's helpful to anyone, here's context for where I placed the Replace function in /partials/data/title.html (for both the homepage and taxonomy sections):

```
5    <!-- Homepage, and it's pagination -->
...
13    {{ if .Paginator.HasPrev }}
14       <!-- Paginated. Append page number to title -->
15        {{ $paginatorTitle := strings.Replace .Paginator "Pager" "Page" 1 }}
16        {{ $title = printf "%s - %s" $paginatorTitle $siteTitle }}
...
21    <!-- Taxonomy page -->
...
30    {{ if .Paginator.HasPrev }}
31       <!-- Add page number-->
32        {{ $paginatorTitle := strings.Replace .Paginator "Pager" "Page" 1 }}
33        {{ $title = $title | append " - " $paginatorTitle }}
```
