### ISSUE TITLE
Empty home page

### ISSUE THREAD

**Issue by Wonderer11** [CaiJimmy/hugo-theme-stack#1072]
### What happened?

I have add pages to the content folder but the home page is empty, also it shows the following when I test locally, while I have copy the files content/page/archives/index.md and content/page/search/index.md from the example site:
WARN  Search page not found. Create a page with layout: search.
WARN  Archives page not found. Create a page with layout: archives.

I have deploy my site on github, hope it helps showcase my problem.
https://github.com/Wonderer11/Wonderland

Thank you

### Hugo version

0.135

### Theme version

3.27

### Relevant log output

```shell
WARN  Search page not found. Create a page with layout: search.
WARN  Archives page not found. Create a page with layout: archives.
```

### Link to Minimal Reproducible Example

https://github.com/Wonderer11/Wonderland

**Comment by CaiJimmy** [comment]
> I have add pages to the content folder but the home page is empty

You have `defaultContentLanguageInSubdir` set to true.

(https://github.com/Wonderer11/Wonderland/blob/6b026065ae3f6cb5e1fb8e4529729ad8a9cbb0f2/config/_default/hugo.yaml#L11)

<img width="649" alt="image" src="https://github.com/user-attachments/assets/48f88509-f413-43d4-a2a0-a4a44e8c92ae">

So the content should not be in `content/*`, but `content/LANG_CODE/*`.  In this case you have no content, hence the empty start page.
