### ISSUE TITLE
The newly created article cannot be displayed

### ISSUE THREAD

**Issue by zlaazlaa** [CaiJimmy/hugo-theme-stack#1079]
### What happened?

Follow the instructions in [Hugo quick start](https://gohugo.io/getting-started/quick-start/), just like this:
```shell
hugo new site quickstart
cd quickstart
git init
git submodule add https://github.com/CaiJimmy/hugo-theme-stack/ themes/hugo-theme-stack
echo "theme = 'hugo-theme-stack'" >> hugo.toml
hugo server
```
Then I created a new article and run Hugo:
```
hugo new content content/posts/my-first-post.md
hugo server -D
```
The new article didn't shown, even I change draft tag to false.

### Hugo version

hugo v0.135.0+extended darwin/arm64 BuildDate=2024-09-27T13:17:08Z VendorInfo=brew

### Theme version

Commit 2a18a92901e2689c23ff340c380a164a88208d78

### What browsers are you seeing the problem on?

Safari

### More information about the browser

Safari 18.1, MacOS 15.1

### Link to Minimal Reproducible Example

https://github.com/zlaazlaa/hugo-stack-bug-report

**Comment by zlaazlaa** [comment]
After run hugo server -D, main page is below
<img width="910" alt="image" src="https://github.com/user-attachments/assets/b1ec02fa-f4e4-41cb-aede-e95efdcab523">

**Comment by CaiJimmy** [comment]
> hugo new content content/posts/my-first-post.md

Should be `content/post`, not `posts`.

Better use the starter template instead of `hugo new site`: https://github.com/CaiJimmy/hugo-theme-stack-starter
