### ISSUE TITLE
一直报错啊

### ISSUE THREAD

**Issue by namofoo** [CaiJimmy/hugo-theme-stack#1104]
### What happened?

ERROR error calling resources.GetRemote: Get "https://publish.twitter.com/oembed?dnt=false&omit_script=true&url=https%3A%2F%2Ftwitter.com%2FDesignReviewed%2Fstatus%2F1085870671291310081": net/http: TLS handshake timeout
ERROR render of "page" failed: "D:\blog\hugo\blog-hugo-stack\themes\hugo-theme-stack\layouts\_default\single.html:27:7": execute of template failed: template: _default/single.html:27:7: executing "main" at <partial "article/article.html" .>: error calling partial: "D:\blog\hugo\blog-hugo-stack\themes\hugo-theme-stack\layouts\partials\article\article.html:2:7": execute of template failed: template: partials/article/article.html:2:7: executing "partials/article/article.html" at <partial "article/components/header" .>: error calling partial: "D:\blog\hugo\blog-hugo-stack\themes\hugo-theme-stack\layouts\partials\article\components\header.html:34:7": execute of template failed: template: partials/article/components/header.html:34:7: executing "partials/article/components/header.html" at <partialCached "article/components/details" . .RelPermalink>: error calling partialCached: partial "article/components/details" timed out after 30s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.

### Hugo version

hugo v0.139.2

### Theme version

hugo-theme-stack-3.29.0

### Link to Minimal Reproducible Example

https://github.com/CaiJimmy/hugo-theme-stack

**Comment by SunsetMkt** [comment]
本地环境无法访问twitter.com？

**Comment by CaiJimmy** [comment]
不要直接复制 `exampleSite` 里面的内容，因为有一篇文章用到了 Twitter 短代码，而你的电脑无法正常访问 Twitter，所以就报错了。

建议使用 Stater Template：https://github.com/CaiJimmy/hugo-theme-stack-starter
