### ISSUE TITLE
Git deployment on Azure

### ISSUE THREAD

**Issue by zishanq** [CaiJimmy/hugo-theme-stack#113]
Hi, I am deploying the theme on Azure Web App Static through github but I am facing an issue with the submodule, if I don't specify the submodule to your repo it's doesn't work.
.gitmodules file : 
[submodule "themes/hugo-theme-stack"]
	path = themes/hugo-theme-stack
	url = https://github.com/CaiJimmy/hugo-theme-stack

The crucial point is I can only refer to your github repo, I tried to copy paste your github repo in a personnal repo but it didn't work. 
I don't have any rights on your module so I cannot edit the profil picture for example.

Could you help me please? Thank you

**Comment by CaiJimmy** [comment]
> I cannot edit the profile picture for example.

You can overwrite it by placing `avatar.png` under `assets/img` of your Hugo site folder. (Or change it editing `config.yaml`)

**Comment by zishanq** [comment]
Thank you
