### ISSUE TITLE
分类页与标签页

### ISSUE THREAD

**Issue by stO-Orz** [CaiJimmy/hugo-theme-stack#116]
算是求助类的 issue 因此没有提交到 Bug Report 和 Feature Request 中。

你好，想请问下 categories 页面和 tags 页面有办法可以通过设置让其显示为文章列表或者 tag-cloud 的样式吗？

当前的横向滚动条在分类数较少的情况下样式很好看，但是如果分类数/ tag 数多的话在其中寻找某一个特定的类或者 tag 就会很不方便。

在文档中没有找到设置的方法，因此在 issue 中寻求帮助，谢谢~

**Comment by CaiJimmy** [comment]
> 想请问下 categories 页面和 tags 页面有办法可以通过设置让其显示为文章列表或者 tag-cloud 的样式吗？

抱歉暂时没有 😓

**Comment by stO-Orz** [comment]
那好吧，我前端太抠脚了所以不太会改……老哥要是有兴趣可以当个 feature 以后看看有没有机会实现 :) 还是很感谢你写的这一套 theme，好看~

**Comment by CaiJimmy** [comment]
改了下逻辑，应该可以了

**Comment by cobalto** [comment]
@CaiJimmy Sorry for the intrusion on this (closed) issue, but can we have an option with something more like this? 
(just changing to vertical aligment, but keeping the cards view)

![image](https://user-images.githubusercontent.com/1196314/104829129-93c8c080-584f-11eb-9898-dbefc69f97b3.png)

**Comment by CaiJimmy** [comment]
> @CaiJimmy Sorry for the intrusion on this (closed) issue, but can we have an option with something more like this?
> (just changing to vertical aligment, but keeping the cards view)
> 
> ![image](https://user-images.githubusercontent.com/1196314/104829129-93c8c080-584f-11eb-9898-dbefc69f97b3.png)

@cobalto 
Sorry for the late reply. But I don't think so 😓. That vertical alignment style doesn't look good to me.
