### ISSUE TITLE
utterances 评论系统颜色主题显示错误

### ISSUE THREAD

**Issue by jo-hnny** [CaiJimmy/hugo-theme-stack#117]
**Describe the bug**
主题切换为暗色，刷新页面，评论任然为亮色

**To Reproduce**
前置条件：
1.  ![image](https://user-images.githubusercontent.com/15609400/103521110-30d04480-4eb3-11eb-8543-b15ec76f35bd.png)
2.  ![image](https://user-images.githubusercontent.com/15609400/103521179-4e9da980-4eb3-11eb-9274-c2f9ed30e0fb.png)
表现:
1. 打开博客，主题模式切换为暗色模式，然后刷新页面，评论仍为亮色模式
![image](https://user-images.githubusercontent.com/15609400/103521415-acca8c80-4eb3-11eb-9fcd-9fa1161a812d.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CaiJimmy** [comment]
更新主题到仓库最新版本。 #111

**Comment by CaiJimmy** [comment]
啊抱歉，不是同一个 Bug 😂

**Comment by CaiJimmy** [comment]
已经提交更新。应该可以了

**Comment by jo-hnny** [comment]
还是有问题，没登录就没问题，当我点击了 sign in to comment之后就不行了
![image](https://user-images.githubusercontent.com/15609400/103529259-4f890800-4ec0-11eb-9eab-74bc538f6332.png)

**Comment by jo-hnny** [comment]
初步猜想应该是 emit onColorSchemeChange 事件的时候，iframe可能还没加载好；
我的想法是加载utterances的script标签时，theme属性优先从locastorage取，否则使用.Site.Params.comments.utterances.theme

**Comment by CaiJimmy** [comment]
应该就是你所说的。主要问题是 Utterances 没有 onLoad 事件，不能等加载后再设置主题。

> 我的想法是加载utterances的script标签时，theme属性优先从locastorage取，否则使用.Site.Params.comments.utterances.theme

这样就得使用 JS 来加载 Utterances，而不是 HTML 标签直接加载。可行，但是感觉不太优雅。

**Comment by CaiJimmy** [comment]
已经提交更新，好像可以了。
