### ISSUE TITLE
when I ran command "hugo" to build the site , some errors happened。

### ISSUE THREAD

**Issue by Tweakzx** [CaiJimmy/hugo-theme-stack#119]
**Describe the bug**
build unsuccessfully

**To Reproduce**
1. Go to  the root directory of my site
2. run " hugo"  in the command line
4. See errors

**Expected behavior**
I want to see it built successfully and produce a folder named "public".

**Screenshots**
Error: Error building site: failed to render pages: render of "taxonomy" failed: execute of template failed: template: _default/list.html:4:12: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "D:\software\Scoop\apps\hugo-extended\tweakzx\themes\hugo-theme-stack\layouts\partials\helper\image.html:27:31": execute of template failed: template: partials/helper/image.html:27:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: edge
 - Version :2.0.1

**Additional context**
May I need to add something to the config file before I build it? Or is there any method else?

**Comment by CaiJimmy** [comment]
Delete `config.toml`.

See #105

**Comment by Tweakzx** [comment]
![image](https://user-images.githubusercontent.com/34200438/103754788-ca305f80-5047-11eb-95f4-0937a1485360.png)
Actually, there is no "config.toml" in the exampleSite, but still occurs the same errors. Thank you for your reply.

**Comment by CaiJimmy** [comment]
`config.toml` under `D:\software\Scoop\apps\hugo-extended\tweakzx\`, not under `exampleSite`.

**Comment by Tweakzx** [comment]
Thanx, I have tried to delete the "config.toml" under the site root directory, but it said cant found a config file. After your reply, I tried to move the config.yaml to the root directory of my site, and it works. Thank you very much.
