### ISSUE TITLE
如何添加友情链接(links)?

### ISSUE THREAD

**Issue by MrPeterJin** [CaiJimmy/hugo-theme-stack#124]
如题，在pages中新建对应md文件后不知道后续怎么配置

**Comment by CaiJimmy** [comment]
抱歉，主题没有包括友链页面。

**Comment by MrPeterJin** [comment]
> 抱歉，主题没有包括友链页面。

额，我看到您的主页在这个主题下似乎也是使用了友链？

**Comment by CaiJimmy** [comment]
对。但没有提交到主题仓库里，因为是随便修改的，使用方法 & 代码并不是很优雅。
