### ISSUE TITLE
为代码块指定语言后，中文样式异常

### ISSUE THREAD

**Issue by sudrizzz** [CaiJimmy/hugo-theme-stack#126]
如果为代码块指定语言，例如 c 语言，然后代码块中添加中文。生成的页面上，中文会有一层背景色，导致看不清楚。详细情况见下图。

![Snipaste_2021-01-11_20-37-52.png](https://i.loli.net/2021/01/11/i1jAYxH2yl8I6OP.png)
![Snipaste_2021-01-11_20-37-42.png](https://i.loli.net/2021/01/11/bXLF4SovWY5aPAd.png)
![Snipaste_2021-01-11_20-38-07.png](https://i.loli.net/2021/01/11/n6cZ8CMeF5S7kaL.png)

**Comment by jo-hnny** [comment]
我的scss代码中也存在这个问题，主要是一些$、#符号之类的
