### ISSUE TITLE
Warning when I start server

### ISSUE THREAD

**Issue by MrAntooo** [CaiJimmy/hugo-theme-stack#127]
Hi, I'm still not very knowledgeable about Hugo Framework, when I start the server via the "hugo server" command it doesn't give any error, but as soon as I enter as localhost it tells me this:

**found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.**   

What should I do?

My version of Hugo is  0.78

Thanks.

**Comment by CaiJimmy** [comment]
I need more information to determine the problem, like the directory structure of your Hugo site, the content of config file, etc.

However, the first guess I make is that you have both `config.toml` and `config.yaml` present in Hugo's site folder. Delete `config.toml` and see if it helps.

**Comment by MrAntooo** [comment]
Yes! Thanks, I solved.
