### ISSUE TITLE
SVG images are not supported to be embeded in posts or as header image

### ISSUE THREAD

**Issue by julian-alarcon** [CaiJimmy/hugo-theme-stack#132]
**Describe the bug**
Trying to add an `svg` image is not possible.
`![svg-image](svg-image.svg)`

**To Reproduce**
1. Add svg image `![svg-image](svg-image.svg)`
2. Try to start the hugo server `hugo server`
3. No server is booted, and error below is show:
```
Start building sites … 
Built in 314 ms
Error: Error building site: "/home/user/Code/my-blog/themes/hugo-theme-stack/layouts/_default/_markup/render-image.html:4:45": execute of template failed: template: _default/_markup/render-image.html:4:45: executing "_default/_markup/render-image.html" at <$image.Width>: error calling Width: *resources.genericResource is not an image
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser : Firefox/Chrome

Hugo version: Extended 0.80.0

**Additional context**
I use the theme https://github.com/halogenica/beautifulhugo with no issues embedding `svg` files.

**Comment by julian-alarcon** [comment]
It's important to mention, when I use a normal post (without Page bundle) the .svg files works with no issues.

**Comment by CaiJimmy** [comment]
Thanks for reporting.

Should be fixed now.
