### ISSUE TITLE
默认缩放下UI显示不完整的问题

### ISSUE THREAD

**Issue by imzhizi** [CaiJimmy/hugo-theme-stack#136]
默认情况下不显示左边侧栏

![image](https://user-images.githubusercontent.com/38089699/106980563-6068ba00-679b-11eb-9815-99ccd39e2c46.png)

而缩放到90%，左边侧栏会出现
![image](https://user-images.githubusercontent.com/38089699/106980598-6fe80300-679b-11eb-8dd4-2c6574e719c1.png)

在自己的博客中同样复现

**Comment by imzhizi** [comment]
大概明白了，是自己开了缩放的原因……

**Comment by stO-Orz** [comment]
@imzhizi 你好，想请教一下解决的方案？我的环境是 13‘ MBP，没有设置缩放时，在 Safari 和 Google Chrome 上均无法显示右边栏（缩小至 80% 时右边栏出现）。

**Comment by CaiJimmy** [comment]
自适应这方面还需要继续打磨。我在我博客上做了些修改，小屏幕上可以更好地利用空间，但暂时还没确定，也就没提交到仓库里。

**Comment by stO-Orz** [comment]
@CaiJimmy 请问可以通过对 scss 文件手动设置来实现首页的三栏布局显示么？【私心来说自己没有移动端的使用需求，笔记本的浏览器应该是唯一的适用场景了。】我自己尝试过在 custom.scss 里面对 grid.scss 的部分变量进行覆盖，不过好像唯独对右边栏没什么效果（始终无法令其在 100% UI 下显示）。

**Comment by imzhizi** [comment]
> @CaiJimmy 请问可以通过对 scss 文件手动设置来实现首页的三栏布局显示么？【私心来说自己没有移动端的使用需求，笔记本的浏览器应该是唯一的适用场景了。】我自己尝试过在 custom.scss 里面对 grid.scss 的部分变量进行覆盖，不过好像唯独对右边栏没什么效果（始终无法令其在 100% UI 下显示）。

我的理解，你的问题，应该是在 breakpoint.css 里面修改设备定义的分辨率

我自己的解决方案其实是我把电脑的 HIDPI 调低了，调到了1080P

**Comment by stO-Orz** [comment]
好的，我去试试，多谢老哥~

**Comment by stO-Orz** [comment]
已解决。 简述一下解决方案看看还有没有其他的小伙伴遇到类似的问题。

方法确实是将 breakpoint.scss 中的分辨率要求降低。根据在 grid.scss 中的代码，breakpoint.scss中的变量代表了设备判定需要满足的最低分辨率。我是将 $on-desktop-large 这个变量改成了1280px。然后浏览器的设备类型就能被识别成 on-desktop-large 了。之后可以在 grid.scss 中对三栏的显示和宽度进行调整。

感谢 @CaiJimmy @imzhizi 两位老哥，祝两位新春快乐~
