### ISSUE TITLE
Upcoming(?): remove compiled SCSS from version system

### ISSUE THREAD

**Issue by CaiJimmy** [CaiJimmy/hugo-theme-stack#147]
Using GitHub Action I set up a workflow that builds automatically SCSS files of this theme. 

https://github.com/CaiJimmy/hugo-theme-stack/blob/96db925b0638c8808c8d1f1bf2ebade9e1a8d610/.github/workflows/hugo-artifact.yml#L1-L44

Something that I've planned to do is **remove compiled SCSS from version system**, less work for me when I have to release a new version. 
As consequence, people who use Hugo non-extended version will have to download manually `resources.zip` that I'll include with each release, and unzip it to their Hugo site folder. This will not affect the Hugo extended user.

![image](https://user-images.githubusercontent.com/5889006/108186355-913ade80-710d-11eb-877a-191b3c3061b8.png)

**Comment by zhixuan666** [comment]
Use ```ubuntu18.04``` to delete the warning

It might be better
