### ISSUE TITLE
Using an image in list sites, but not in the article

### ISSUE THREAD

**Issue by 4VRDriver** [CaiJimmy/hugo-theme-stack#148]
**Is your feature request related to a problem? Please describe.**
Hello,
I often want to include just one image in an article, and the thumbnail image in the list pages looks good, but in the article the image is showing up twice because I want the user to use the PhotoSwipe feature to see the image in full resolution.
Is it possible to hide time image (that one that is specified by the `image` front matter field) in the article but still show it in list pages?
Thank you!

**Comment by CaiJimmy** [comment]
> Is it possible to hide time image (that one that is specified by the image front matter field) in the article but still show it in list pages?

Sorry, it's not possible 😓

**Comment by 4VRDriver** [comment]
> > Is it possible to hide time image (that one that is specified by the image front matter field) in the article but still show it in list pages?
> 
> Sorry, it's not possible sweat

Alright, thanks anyway!
