### ISSUE TITLE
Select Search/Archive Page, and the button will not become dark.

### ISSUE THREAD

**Issue by ShakeM** [CaiJimmy/hugo-theme-stack#149]
Select Search/Archive Page, and the button will not become dark.

**Comment by CaiJimmy** [comment]
> the button will not become dark.

What button? A screenshot would be helpful.

**Comment by ShakeM** [comment]
![image](https://user-images.githubusercontent.com/19363971/108629016-ed4c8c80-7498-11eb-92ea-5a6956a47586.png)
![image](https://user-images.githubusercontent.com/19363971/108629026-f9384e80-7498-11eb-984c-81841cbbff3f.png)
The navbar button "Search" won't become dark when it is in Chinese, and if it is in English, it works.
