### ISSUE TITLE
左侧菜单栏在切换至“关于”页面时高亮失败

### ISSUE THREAD

**Issue by yodhcn** [CaiJimmy/hugo-theme-stack#15]
使用的版本是从 [releases](https://github.com/CaiJimmy/hugo-theme-stack/releases/tag/v1.0.2) 页面下载的 v1.0.2 版本，在路由到 ``` /about ``` 页面时，左侧菜单栏中的 ```关于``` 并没有高亮。

在 ```name = "关于"``` 时不会高亮，只有 ```name = "About"``` 才会高亮。这个主题的菜单栏的高亮匹配机制是什么？难道匹配的不是 ```url``` 而是 ```name```？我该怎么配置才能让左侧菜单栏在路由至相应页面时正确地高亮？

并且 ```/content/page/about.md``` 的 ```title```在修改后，还会出现 ```404 page not found``` 的错误，无法正确访问 ``` /about ``` 页面。无法修改“关于”页面的 ```title```，这也同样令我困惑。

```
# config.toml
# ...
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -100
        pre = "home"
    [[menu.main]]
        identifier = "about-cn"
        name = "关于"
        url = "/about/"
        weight = -90
        pre = "user"
    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives/"
        weight = -70
        pre = "archives"
# ...
```

**Comment by CaiJimmy** [comment]
你好，

> 这个主题的菜单栏的高亮匹配机制是什么？难道匹配的不是 url 而是 name？

是的，匹配的是`name`，需要和页面标题一致才会被高亮。在未来的版本里应该会改进。

> 并且 /content/page/about.md 的 title在修改后，还会出现 404 page not found 的错误，无法正确访问 /about 页面。无法修改“关于”页面的 title，这也同样令我困惑。

给 `/content/page/about.md` 的 Front Matter 添加一个 `slug` 字段来自定义固定链接，否则会默认使用 `title`。（https://gohugo.io/content-management/urls/）

**Comment by CaiJimmy** [comment]
如果需要页面标题和菜单的 `name` 不同，可以在相应页面的 Markdown Front Matter 添加：

```
menu: 
    main:
        name: title
        pre: icon
        weight: -90
```
