### ISSUE TITLE
Post margins disappear after adding section heading

### ISSUE THREAD

**Issue by austinwpearce** [CaiJimmy/hugo-theme-stack#150]
**Describe the bug**
Margin along sides of post disappear after adding section heading.

**To Reproduce**
1. Create new post in blogdown in RStudio.
2. Add body text and images.
3. Render site. 
4. Then add a section heading to the post.
5. Render site again, at which point the margins disappear.

**Expected behavior**
I would expect that after a section heading, the body text and images would still have a margin.

**Screenshots**
Without a heading
![image](https://user-images.githubusercontent.com/44807050/108598185-229e9080-735a-11eb-8883-39223911ed36.png)

### With a heading
![image](https://user-images.githubusercontent.com/44807050/108598299-d0aa3a80-735a-11eb-849d-b4e4b2553e68.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 88

**Additional context**
Site rendered with blogdown package in RStudio. This behavior might be due to blogdown, in which case, this issue can be closed..

**Comment by CaiJimmy** [comment]
That's probably something related to Blogdown's Markdown render engine, it should wrap text inside `<p>` tag.

https://github.com/CaiJimmy/hugo-theme-stack/blob/96db925b0638c8808c8d1f1bf2ebade9e1a8d610/assets/scss/partials/layout/article.scss#L192-L195

**Comment by austinwpearce** [comment]
You're probably right. I think the blogdown devs are working to update it since changes have come to Hugo and markdown and so on in recent months.
