### ISSUE TITLE
the navbar button "Search" won't become dark when it is in Chinese

### ISSUE THREAD

**Issue by ShakeM** [CaiJimmy/hugo-theme-stack#151]
In the same searching page, the navbar button "Search" won't become dark when it is in Chinese, and if it is in English, it works.

![image](https://user-images.githubusercontent.com/19363971/108629141-88ddfd00-7499-11eb-9140-cf02e2307a13.png)

![image](https://user-images.githubusercontent.com/19363971/108629120-75329680-7499-11eb-8cce-67fb8522f99a.png)

**Comment by CaiJimmy** [comment]
Remove search menu item from `config.yaml`, and add it using the first method:

https://docs.stack.jimmycai.com/configuration/custom-menu#first-method-recommended

This will allow the theme to apply the style correctly **even if the title of the page does not match with the menu item title.**

**Comment by CaiJimmy** [comment]
I'll start a migration to the first method once Hugo theme showcase removes the *[demo](https://themes.gohugo.io/theme/hugo-theme-stack/)* button of this theme.
