### ISSUE TITLE
adding "categories" on the right sidebar

### ISSUE THREAD

**Issue by thebusinessgrad** [CaiJimmy/hugo-theme-stack#153]
Hi and thank you for this great theme.

Is it possible to add a "categories" section to the right sidebar, together with where we have the "tags"

Thanks again!

tunca

**Comment by CaiJimmy** [comment]
> Is it possible to add a "categories" section to the right sidebar, together with where we have the "tags"

Sorry, it's not yet possible 😓

**Comment by thebusinessgrad** [comment]
No problem at all! Thanks!
