### ISSUE TITLE
Flashing when load new page in dark mode

### ISSUE THREAD

**Issue by PePoDev** [CaiJimmy/hugo-theme-stack#154]
Flashing when load new page in dark mode

**Comment by PePoDev** [comment]
I look at your [example site](https://theme-stack.jimmycai.com/) It's no problem but it happen in my site -> https://pepo.dev/

**Comment by PePoDev** [comment]
It wokring corrrectly in development. I don't know Why 😂

**Comment by CaiJimmy** [comment]
Try disable CloudFlare rocket loader.

**Comment by PePoDev** [comment]
Thanks. It's look better.
Now only `home` click will flashing.

**Comment by PePoDev** [comment]
Solved Thanks a lot

**Comment by horaceyoung** [comment]
> Thanks. It's look better. Now only `home` click will flashing.

Hi I'm having a similar problem. I don't have rocket loader enabled. How do you solve it in the end?

**Comment by horaceyoung** [comment]
> > Thanks. It's look better. Now only `home` click will flashing.
> 
> Hi I'm having a similar problem. I don't have rocket loader enabled. How do you solve it in the end?

Tested a bit and it only happens with FireFox
