### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by fariszr** [CaiJimmy/hugo-theme-stack#156]
**Is your feature request related to a problem? Please describe.**
please can you add RTL content and RTL layout support?
for arabic and all other RTL languages 

**Describe the solution you'd like**
make stack compatible with RTL languages 
block #157

**Comment by CaiJimmy** [comment]
Hi,

RTL support is something that I've never implemented before, and when I created this theme I didn't have it on my mind.

Probably will require many code changes, and I cannot guarantee it will come out.

Sorry. And thanks for your i18n PR.
