### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by ccleve** [CaiJimmy/hugo-theme-stack#158]
I downloaded the theme into /themes in a clean Hugo install, and updated the config to point to it. Got this error on "hugo server -D". It happens with both the head revision and v2.2.0.

Mac OS Big Sur.

hugo server -D
Start building sites … 
ERROR 2021/02/25 14:11:06 render of "taxonomy" failed: execute of template failed: template: _default/list.html:4:12: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/ccleve/Documents/dev/ccleveblog/themes/hugo-theme-stack-2.2.0/layouts/partials/helper/image.html:31:31": execute of template failed: template: partials/helper/image.html:31:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
ERROR 2021/02/25 14:11:06 render of "taxonomy" failed: execute of template failed: template: _default/list.html:4:12: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/ccleve/Documents/dev/ccleveblog/themes/hugo-theme-stack-2.2.0/layouts/partials/helper/image.html:31:31": execute of template failed: template: partials/helper/image.html:31:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
Built in 38 ms
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:4:12: executing "index.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "/Users/ccleve/Documents/dev/ccleveblog/themes/hugo-theme-stack-2.2.0/layouts/partials/helper/image.html:31:31": execute of template failed: template: partials/helper/image.html:31:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil

**Comment by CaiJimmy** [comment]
See https://github.com/CaiJimmy/hugo-theme-stack/issues/105#issuecomment-753300903
