### ISSUE TITLE
Need help with Menu item's i18n

### ISSUE THREAD

**Issue by Sp-cy** [CaiJimmy/hugo-theme-stack#159]
**Is your feature request related to a problem? Please describe.**
There is no translation on the head menu items in any languages, I would like to contribute the Spanish language.

**Describe the solution you'd like**
Can you provide a YAML formatting example on how we should do the i18n for such items? The example in the hugo docs are formatted in TOML. 

**Describe alternatives you've considered**
For now  I can leave with it in English but for proper accessibility we should find a solution.

**Additional context**
![image](https://user-images.githubusercontent.com/68587155/109289442-d33de180-77eb-11eb-974b-3362fb702b3b.png)

**Comment by CaiJimmy** [comment]
Hi, 

> There is no translation on the head menu items in any languages

That's not part of a theme, user should customize it by themself.
-----------------------

If you are working with a multilingual site, it's easier to insert menu item using the first method: https://docs.stack.jimmycai.com/configuration/custom-menu

For more information: https://gohugo.io/content-management/multilingual/

As an example:
![image](https://user-images.githubusercontent.com/5889006/109330431-ee483a00-785b-11eb-87e4-3ee8cbdca571.png)

**Comment by Sp-cy** [comment]
Thank you for your help. This works. Sorry for not closing this earlier.
