### ISSUE TITLE
Failed to get JSON resource 

### ISSUE THREAD

**Issue by JesseStutler** [CaiJimmy/hugo-theme-stack#160]
**Describe the bug**
When I start to use the command `hugo serve`
is shows the following error:

Start building sites …
ERROR 2021/03/01 22:23:16 Failed to get JSON resource "https://api.twitter.com/1/statuses/oembed.json?id=1085870671291310081&omit_script=true": Get "https://api.twitter.com/1/statuses/oembed.json?id=1085870671291310081&omit_script=true": dial tcp 31.13.85.16:443: i/o timeout
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Built in 30065 ms
Error: Error building site: "/Users/chenzicong/quickstart/content/post/rich-content/index.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.

I think it may be because my network was blocked by the 'Chinese Wall'...How to solve this

**Comment by JesseStutler** [comment]
Seems strange..when I click those JSON resource link, it can download quickly...Seems that the problem isn't the wall...?Confused :(

**Comment by CaiJimmy** [comment]
Remove `content/post/rich-content`

**Comment by JesseStutler** [comment]
thx! Close now
