### ISSUE TITLE
Demo site does not support Chinese search

### ISSUE THREAD

**Issue by shenweiyan** [CaiJimmy/hugo-theme-stack#163]
**Describe the bug**
The [demo site](https://demo.stack.jimmycai.com/) does not support Chinese search.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7 64
 - Browser: 版本 88.0.4324.182（正式版本） （64 位）
 - Version: 

**Smartphone (please complete the following information):**
![bug-1](https://user-images.githubusercontent.com/26101369/110051144-43220e00-7d90-11eb-99a2-03d329bc970d.png)
![bug-2](https://user-images.githubusercontent.com/26101369/110051154-474e2b80-7d90-11eb-9688-0ace2b1cea3d.png)

**Comment by CaiJimmy** [comment]
Thanks for reporting.

That's expected. Article's description is not part of search index.
