### ISSUE TITLE
Tag colours differ between the site root and when viewing blog post

### ISSUE THREAD

**Issue by MattDaines** [CaiJimmy/hugo-theme-stack#164]
Hey, thanks for your Hugo theme! I love the style and the layout! Just one cosmetic inconsistency below I thought I'd raise:

**Describe the bug**
Tag colours are not consistent between the root of the site and when viewing an article/post.

**To Reproduce**
Steps to reproduce the behaviour:
- Tag colours on the [root of the site](https://themes.gohugo.io/theme/hugo-theme-stack/) are green (#8ea885)
- Tag colours [on a post](https://themes.gohugo.io//theme/hugo-theme-stack/p/markdown-syntax-guide/) are navy (#34495e) or white (#ecf0f1)

**Expected behaviour**
Tag colours on the site root should follow the same colour scheme as the blog post pages.

If this is by design, I'll try wrap my head around how to implement a `custom.scss` to work around.

**Comment by CaiJimmy** [comment]
By default, the article list's category background is picked from 5 default colors:

https://github.com/CaiJimmy/hugo-theme-stack/blob/e61bca1dbdfc8a8232193b7672e7d4190bb34d31/assets/scss/variables.scss#L1-L2

When viewing an article, theme can't tell which color it was assigned in article list. 

There are two workarounds for this:

1. Specify color for each category by adding `style` attribute to them: https://github.com/CaiJimmy/hugo-theme-stack/blob/master/exampleSite/content/categories/Test/_index.md (I just realized that this wasn't documented, my bad)
2. You can edit the above SCSS file, and keep only one default color.

**Comment by MattDaines** [comment]
Oh, thanks for pointing out category colours! I hadn't even thought of that as something I might want to do.  That'll do nicely, thanks!
