### ISSUE TITLE
希望添加“字数统计”与“阅读时间估计”的功能

### ISSUE THREAD

**Issue by yodhcn** [CaiJimmy/hugo-theme-stack#17]
在其它 hugo 主题里发现了这个功能，希望能添加上

[https://github.com/zzossig/hugo-theme-zzo](https://github.com/zzossig/hugo-theme-zzo)

**Comment by CaiJimmy** [comment]
你好，

可以在 `/layouts/partials/article/components/details.html` 添加 `{{ .ReadingTime }}` & `{{ .WordCount }}` 来实现，这两个都是 Hugo 提供的[页面变量](https://gohugo.io/variables/page/)。

暂时没有打算把这个功能添加到主题里。
