### ISSUE TITLE
可以为文章添加一个浮动的目录么

### ISSUE THREAD

**Issue by Anthem-whisper** [CaiJimmy/hugo-theme-stack#170]
看文章的时候感觉如果有一个浮动的目录的话，能更好的把握文章结构，现在很多主题都有这个功能，期待
hugo-theme-stack也能推出这个功能

**Comment by CaiJimmy** [comment]
Duplicated: https://github.com/CaiJimmy/hugo-theme-stack/issues/129

谢谢你的建议。

**Comment by ixugo** [comment]
期待目录
