### ISSUE TITLE
Need help with changing the page widths

### ISSUE THREAD

**Issue by key4920** [CaiJimmy/hugo-theme-stack#172]
Is there any way to change the side bar and content widths?

The content width seems too narrow and the right side bar isn't shown with my laptop.
Even thought the width is changing dynamically depending on the using device, it seems too narrow.
I'd like to know how to reduce the left side bar's width and expand the main content width.

I attached the screenshot of your example page, shown in my laptop.
![Screenshot 2021-03-21 at 01 24 05](https://user-images.githubusercontent.com/42959473/111877402-975efc00-89e6-11eb-9d07-82c0b5cf42ce.png)

I guess I need to add customised css code, but I can't get handle on it as I'm a beginner. 

Thank you!

**Comment by CaiJimmy** [comment]
> Is there any way to change the sidebar and content widths?

Yes, by editing `grid.scss` and `breakpoints.scss` under `assets/scss` folder. Hugo Extended version is required to make the change.

In `breakpoints.scss` there is a variable called `$on-desktop-large`. The sidebar will be shown if the screen width is bigger or equal to that. You can reduce this value to make the sidebar appear on a smaller screen.

https://github.com/CaiJimmy/hugo-theme-stack/blob/3e8490da1d7beabfc563a16e64428f1df9aa942c/assets/scss/breakpoints.scss#L4

In `grid.scss` you can adjust sidebar widths.
