### ISSUE TITLE
Support line number in code block

### ISSUE THREAD

**Issue by cielpy** [CaiJimmy/hugo-theme-stack#176]
**Is your feature request related to a problem? Please describe.**

I want to discribe something with code line number, but line number not shown.

**Describe the solution you'd like**
show line number when code block show

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by CaiJimmy** [comment]
https://gohugo.io/getting-started/configuration-markup#highlight

Set `markup.highlight.lineNos` to true.

**Comment by cielpy** [comment]
Thanks！
