### ISSUE TITLE
Single pages are missing the favicon.

### ISSUE THREAD

**Issue by Sp-cy** [CaiJimmy/hugo-theme-stack#181]
**Describe the bug**
- Single pages don't have a favicon in the tab. List page doesn't have the problem.

![firefox_Y6wriS6OTC](https://user-images.githubusercontent.com/68587155/113491285-cff1e180-948c-11eb-8e95-ea349df7c7e6.png)

- My transalted page is not showing the search neither the archives widgets. They do appear in my default page. 

![image](https://user-images.githubusercontent.com/68587155/113491392-a84f4900-948d-11eb-91b2-2bae2a9a227e.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Browser: Firefox

**Additional context**

**Comment by CaiJimmy** [comment]
Might be related: https://github.com/CaiJimmy/hugo-theme-stack/issues/173

**Comment by Sp-cy** [comment]
Favicon seems to get fixed with that solution. I have a suspicion about the search and archives. Closing for now. Love the theme. Image processing in page bundles + a nice gallery with lightbox are amazing for a blog. 
Looking forward for the updates.
