### ISSUE TITLE
Search doesn't work for me

### ISSUE THREAD

**Issue by Godnyx** [CaiJimmy/hugo-theme-stack#182]
**Describe the bug**
I don't know if I'm doing something wrong but search doesn't appear for me

**To Reproduce**
The widget just doesn't show up

**Expected behavior**
To show it up (really why we have to answer all that stuff?)

**Screenshots**
......

**Desktop (please complete the following information):**
 - OS: Artix Linux
 - Browser: Firefox, Qutebrowser
 - Version: Firefox 87.0, Qutebrowser v2.1.0

**Smartphone (please complete the following information):**
Have not tested in smartphones yet

**Additional context**
I tried both hugo and hugo-extended

**Comment by CaiJimmy** [comment]
> I don't know if I'm doing something wrong

Me neither. 

Provide at least the source code & config file for debugging. If the [example site's search](https://demo.stack.jimmycai.com/search/) is working fine, then check again your configuration.

**Comment by Godnyx** [comment]
Alright, I will check that out! Thanks a lot!
