### ISSUE TITLE
修改scss不生效

### ISSUE THREAD

**Issue by cciy** [CaiJimmy/hugo-theme-stack#189]
我这边修改主题中的`\assets\scss\variables.scss`不生效，但是我修改了
`hugo-theme-stack\resources\_gen\assets\scss\scss\style.scss_b95b077eb505d5c0aff8055eaced30ad.content`中的css可以生效，
我想了解一下，`style.scss_b95b077eb505d5c0aff8055eaced30ad.content`这个文件是scss编译style.scss以后产生的吗，

**Comment by CaiJimmy** [comment]
需要使用 **Hugo Extended 版本**才能修改 SCSS 文件：https://github.com/CaiJimmy/hugo-theme-stack#requirements

> style.scss_b95b077eb505d5c0aff8055eaced30ad.content这个文件是scss编译style.scss以后产生的吗，

是的。
