### ISSUE TITLE
求助，关于您这款主题的使用

### ISSUE THREAD

**Issue by kingsqiu** [CaiJimmy/hugo-theme-stack#191]
首先非常感谢您写出这款精美的主题，在hugo的blog标签中看到您的这款主题简洁大方，还有深浅色模式，着实非常喜爱。

但是，我在使用您的主题时，遇到了一些麻烦。在您的文档中写道：“如果是第一次使用本主题，建议把 exampleSite 文件夹中的 assets 和 config.yaml 复制到站点目录下。后者是 Hugo 站点的配置文件，已经写入了主题的可配置字段。”

而我是刚刚开始学习编程，在您的examplesite文件夹下没有看到assets文件，弄了很久也没有弄好这个主题，希望您能够给予些帮助，可否请您在百忙之中抽空更新下文档呢？

**Comment by CaiJimmy** [comment]
`exampleSite/assets` 文件夹后来被我删除了，现在只需要复制 `config.yaml` 到站点根目录。

第一次使用 Hugo 的话，我建议：

- 新建文件夹
- 复制 `exampleSite` 的内容到该文件夹
- 主题解压到 `themes/hugo-theme-stack` 文件夹
- 运行 `hugo server`

**Comment by kingsqiu** [comment]
感谢您的回复，非常有用，现在已经可以调试了。因为我是先使用示例文章进行预览，最后发现是在examplesite/content/post/rich-content/index.md的问题，删除了就可以用了。以下是报错信息：
ERROR 2021/04/15 00:08:11 Failed to get JSON resource "https://api.twitter.com/1/statuses/oembed.json?id=1085870671291310081&omit_script=true": Get "https://api.twitter.com/1/statuses/oembed.json?id=1085870671291310081&omit_script=true": net/http: TLS handshake timeout
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
ERROR 2021/04/15 00:08:11 Failed to get JSON resource "https://vimeo.com/api/oembed.json?url=https://vimeo.com/48912912": Get "https://vimeo.com/api/oembed.json?url=https://vimeo.com/48912912": read tcp 192.168.0.102:50554->151.101.128.217:443: read: connection reset by peer
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]

**Comment by CaiJimmy** [comment]
报错是因为是示例文章有请求 Twitter API 的 Shortcode，需要科学上网。

**Comment by fujiawei-dev** [comment]
不想删，已经科学上网，但 Hugo 没有走系统代理，请问怎么办？

**Comment by GitHub-wang9527** [comment]
> 不想删，已经科学上网，但 Hugo 没有走系统代理，请问怎么办？

我遇到了同样的问题

**Comment by x4fa0** [comment]
@wang9527s @fujiawei-dev @kingsqiu   
在 `..\content\post\` 下，**删除** `rich-content` 整个目录
