### ISSUE TITLE
Categories images cannot be loaded correctly

### ISSUE THREAD

**Issue by beadx6ggwp** [CaiJimmy/hugo-theme-stack#194]
## Describe the bug

I execute perfect on the local side(hugo server, or apache)

But in github page, when I click into the Archives pages, the Categories images cannot be loaded correctly.

## Expected behavior
Categories images should be loaded.

## To Reproduce
sry, i don't know

## Screenshots

run on local(hugo server and apache127.0.0.1):
![圖片](https://user-images.githubusercontent.com/21116850/115165642-740c9700-a0e1-11eb-8554-5131e45cd71e.png)

run on github page:
"Test" image 404 Not Found
![圖片](https://user-images.githubusercontent.com/21116850/115165604-314abf00-a0e1-11eb-8349-1d8d25c58c0e.png)

## Environment

- **Hugo version**:  0.82.0
- **Hugo extended?**: Yes

## Additional context
不好意思我英文不是很好，用中文敘述一次

在本地端運行時一切都正常，但是部屬到Github page後，Archives中分類圖片無法正確圖取，但是點進去Test後的圖片又是正常的，且其他圖片也都沒有問題

## Link to the demo site and/or source repository
here is my site: [https://davidhsu666.com/archives/](https://davidhsu666.com/archives/)

**Comment by CaiJimmy** [comment]
是已经解决了吗？我这里点进去似乎还是无法加载。

如果可以提供站点源码会更方便 Debug。

**Comment by beadx6ggwp** [comment]
目前是直接將分類圖片放置在"static"中，雖然不會有裁減的處理，但能正常顯示

左邊的"程式筆記"圖片是放置在"static/img/categories"中，右邊的"Test"是Example的預設值
![圖片](https://user-images.githubusercontent.com/21116850/115352625-27f94980-a1ea-11eb-941d-3da7b2f4715e.png)

Source: [https://github.com/beadx6ggwp/beadx6ggwp.github.io](https://github.com/beadx6ggwp/beadx6ggwp.github.io)

本地端預覽的時候都沒事，放到github page時點F12看到那張圖片出現404 error，但那張圖確實有存在


GET | https://davidhsu666.com/categories/test/_hu8102ac0a5989befdf52fa5096a373f78_52927_ba0b8e744b36f1e48b9c54b5d2847004.jpg
404 Not Found

![圖片](https://user-images.githubusercontent.com/21116850/115353610-4d3a8780-a1eb-11eb-8588-506d483ee78f.png)

好像只有我有這問題，可能是我哪邊沒處理好

**Comment by CaiJimmy** [comment]
我看仓库里面是有这个图片的。感觉会不会是上传网站的时候出了什么问题

https://github.com/beadx6ggwp/beadx6ggwp.github.io/blob/main/docs/categories/test/_hu8102ac0a5989befdf52fa5096a373f78_52927_ba0b8e744b36f1e48b9c54b5d2847004.jpg

**Comment by CaiJimmy** [comment]
@beadx6ggwp 可能是 GitHub Page 的问题。https://github.com/CaiJimmy/hugo-theme-stack/issues/198#issuecomment-826964724

试试看新建一个 `.nojekyll` 文件。

**Comment by beadx6ggwp** [comment]
非常感謝
