### ISSUE TITLE
需要中文 demo 站点

### ISSUE THREAD

**Issue by sbilly** [CaiJimmy/hugo-theme-stack#2]
RT

**Comment by Xuyiyang23333** [comment]
中英文没什么区别吧。

**Comment by CaiJimmy** [comment]
感觉没有必要单独建一个中文 Demo 站点

倒是应该给[现有的 Demo](https://hugo-theme-stack.netlify.app/)添加一些中文文章

**Comment by sbilly** [comment]
> 中英文没什么区别吧。

主要是字体有差别。不少 E 文模版中文环境下表现就很差。现在 demo 上增加一些中文文章也可以。

**Comment by CaiJimmy** [comment]
已添加：https://theme-stack.jimmycai.com/p/test-chinese/

**Comment by sbilly** [comment]
thx
