### ISSUE TITLE
error on installing the theme

### ISSUE THREAD

**Issue by SamHamou** [CaiJimmy/hugo-theme-stack#20]
Hello i tried to install the theme today but i got this error can you please tell me how i can fix that 1:27:46 PM: Error: Error building site: failed to render pages: render of "home" failed: "/opt/build/repo/themes/stack/layouts/rss.xml:37:90": execute of template failed: template: rss.xml:37:90: executing "rss.xml" at <$image.resource.Width>: nil pointer evaluating interface {}.Width

you can find my repo here : https://github.com/SamHamou/Animoo

**Comment by CaiJimmy** [comment]
Hi,

It should be fixed now. https://github.com/CaiJimmy/hugo-theme-stack/commit/bd8e03ba6113f544194ae5de7a098a1c6973d681
