### ISSUE TITLE
Comments using utteranc.es

### ISSUE THREAD

**Issue by ress997** [CaiJimmy/hugo-theme-stack#21]
**Is your feature request related to a problem? Please describe.**
The ad and tracking code will be inserted when using disqus.

**Describe the solution you'd like**
- https://utteranc.es/

**Comment by CaiJimmy** [comment]
Hi,

Support for more comment system can be added by creating `{provider}.html` under `layouts/partials/comments/provider/`, and then edit `config.toml`.

**Comment by ress997** [comment]
Thank you for the very quick response, thank you.
