### ISSUE TITLE
Is it possible to play the video without jumping

### ISSUE THREAD

**Issue by ZiXia1** [CaiJimmy/hugo-theme-stack#215]
Like the title, can you play the video without jumping?

**Comment by zhixuan666** [comment]
youtube or video??

**Comment by ZiXia1** [comment]
> youtube or video file??
> 
> 视频文件 还是 youtube bilibili？

视频文件，就如演示站中Rich Content1文章中的

**Comment by zhixuan666** [comment]
只能自己做shortcodes
