### ISSUE TITLE
Unable to embed a recording of asciinema

### ISSUE THREAD

**Issue by kyteinsky** [CaiJimmy/hugo-theme-stack#221]
I have a asciinema .cast file intended to be put inside a post in my website, but when I place custom css and js in directories static/css and static/js resp., and followed other steps mentioned in [here](https://www.banjocode.com/post/hugo/custom-css/), and thereafter inspect the local website if they were put in there, I don't find it there.

Can you guide me on how to go about doing this?
I have also a separate [guid](https://jenciso.github.io/blog/embedding-asciinema-cast-in-your-hugo-site/), but with no outcome, just a blank screen with nothing in head or body tags.

Thank you

**Comment by zhixuan666** [comment]
### Set custom css
Create layouts/partials/head/custom.html under your Hugo site folder, Please add here 

### Set asciinema 

```html
<!-- layouts/partials/footer/custom.html -->
{{ if .Params.asciinema }}
<script src="https://cdn.jsdelivr.net/npm/asciinema-player@2.6.1/resources/public/js/asciinema-player.min.js"></script>
{{ end }}
```

```css
/* assets/scss/custom.scss */
/* asciinema style */
...
```

```html
<!-- layouts/shortcodes/asciinema.html -->
<p>
    <asciinema-player
        src="{{ with .Get "key" }}{{ . }}{{ end }}"
        cols="{{ if .Get "cols" }}{{ .Get "cols" }}{{ else }}640{{ end }}"
        rows="{{ if .Get "rows" }}{{ .Get "rows" }}{{ else }}10{{ end }}"
        {{ if .Get "autoplay" }}autoplay="{{ .Get "autoplay" }}"{{ end }}
        {{ if .Get "preload" }}preload="{{ .Get "preload" }}"{{ end }}
        {{ if .Get "loop" }}loop="{{ .Get "loop" }}"{{ end }}
        start-at="{{ if .Get "start-at" }}{{ .Get "start-at" }}{{ else }}0{{ end }}"
        speed="{{ if .Get "speed" }}{{ .Get "speed" }}{{ else }}1{{ end }}"
        {{ if .Get "idle-time-limit" }}idle-time-limit="{{ .Get "idle-time-limit" }}"{{ end }}
        {{ if .Get "poster" }}poster="{{ .Get "poster" }}"{{ end }}
        {{ if .Get "font-size" }}font-size="{{ .Get "font-size" }}"{{ end }}
        {{ if .Get "theme" }}theme="{{ .Get "theme" }}"{{ end }}
        {{ if .Get "title" }}title="{{ .Get "title" }}"{{ end }}
        {{ if .Get "author" }}author="{{ .Get "author" }}"{{ end }}
        {{ if .Get "author-url" }}author-url="{{ .Get "author-url" }}"{{ end }}
        {{ if .Get "author-img-url" }}author-img-url="{{ .Get "author-img-url" }}"{{ end }}
    ></asciinema-player>
</p>
```

Put your .cast file with your index.md file

{{< asciinema key=".cast file name" >}}

**Comment by kyteinsky** [comment]
Thank you very much @zhixuan666 for the reply.
I followed a generic approach to it and after two long days way able to figure it out (yes I opened this issue yesterday), but your method is certainly more efficient for this theme, will implement it soon.
