### ISSUE TITLE
Questions & Request

### ISSUE THREAD

**Issue by ribilynn** [CaiJimmy/hugo-theme-stack#224]
Thank you Jimmy for this beautiful theme!
I'm new to Hugo and CSS and this stack theme is my first theme to try. Apologize if the question is dumb.

### Question

1. How to set the max width of the article's content?
It's too wide and the readability is not good. I notice there are some fixed width level. So how can I restrict the max one that can be used?

2. Can I set images' width in a article separately?
`<img src="" width="450"/>` doesn't work.

### Feature Request
3. An outline view on the right side of the article's content that can help me navigate to any chapter of the article.

**Comment by CaiJimmy** [comment]
> How to set the max width of the article's content?
https://github.com/CaiJimmy/hugo-theme-stack/blob/master/assets/scss/grid.scss#L7

Adjust `max-width` should be enough.

> Can I set images' width in a article separately?
> <img src="" width="450"/> doesn't work.

Should work if the `unsafe` option is enabled. By default, Hugo omits raw HTML in the page content.
https://gohugo.io/getting-started/configuration-markup/#goldmark

> An outline view on the right side of the article's content that can help me navigate to any chapter of the article.

See #129

**Comment by ribilynn** [comment]
OK. Thanks!
