### ISSUE TITLE
I make a small suggestion

### ISSUE THREAD

**Issue by jokefrelon** [CaiJimmy/hugo-theme-stack#229]
Can the archives be arranged by month?

**Comment by CaiJimmy** [comment]
Sorry. It doesn't look good to me. 

You can change the behavior by modifying the following code:

https://github.com/CaiJimmy/hugo-theme-stack/blob/028ae12ea56077fb630bbf12ed46781db583fe2a/layouts/_default/archives.html#L20
https://github.com/CaiJimmy/hugo-theme-stack/blob/028ae12ea56077fb630bbf12ed46781db583fe2a/layouts/partials/widget/archives.html#L13

Change `2006` to `2006 Jan` for example.
