### ISSUE TITLE
Configuration for Dark Theme

### ISSUE THREAD

**Issue by grisu48** [CaiJimmy/hugo-theme-stack#23]
Hey there,

I really love this theme. I'm only having one problem: I fail to see how to enable dark mode.
It is advertised in the `README.md` but I couldn't find anywhere where to enable the dark mode. Interestingly it seems to work in my Firefox because I had it enabled in the old theme, but if I open the same page on another Computer or e.g. in Chromium, then I get the light theme.

It would be super cool, if there is a way in the `config.toml` file to enable dark theme by default and then a button on the webpage to turn it on/off (e.g. as done in the [diary theme](https://themes.gohugo.io/theme/hugo-theme-diary/)). I'm thinking about something like `enableAutoDarkMode` in the `config.toml` file:

    [params]
    title = "Example toml config"
    description = "This is my awesome blog"
    enableAutoDarkMode = true

Anyways, I really love this theme and it would be super cool to also include this one.

Thanks :slightly_smiling_face:

**Comment by CaiJimmy** [comment]
Hi,

Dark theme uses CSS `prefer-color-scheme` feature (https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). **It is enabled automatically if the client's system uses dark theme**.

I had received a feature request about adding a dark theme toggle. I tried to implement it, but I wasn't satisfied with the result. You can find more details in this PR: https://github.com/CaiJimmy/hugo-theme-stack/pull/14

Preview: https://deploy-preview-14--hugo-theme-stack.netlify.app/

It's on my To-Do list, but sorry I don't have time now to dig further into it 😓.

**Comment by grisu48** [comment]
Hi Jimmy,

thanks for coming back on this. I understand, perhaps I can have a look how to improve this in the theme.
Thanks for the reply, and no worries, we're all short on time ;-)

Have a good day!

**Comment by grisu48** [comment]
Thank you very much! Wish you a merry Christmas and a happy new year :santa:

**Comment by CaiJimmy** [comment]
Thanks, and you too ✨.
