### ISSUE TITLE
optn to disable google and cloudflare 

### ISSUE THREAD

**Issue by horusra** [CaiJimmy/hugo-theme-stack#239]
Is it possible to have an option to disable all google font/apis and cloudflare stuff?
or at least add to the documentation how to change or remove these.

**Comment by CaiJimmy** [comment]
This theme does not use Cloudflare "stuff" as I know.

Google font can be removed by overwritting `layouts\partials\footer\components\custom-font.html` with an empty HTML file.

I don't think that's worth adding neither an option nor doc. Just search the codebase using the keyword `google`.
