### ISSUE TITLE
change font defaults to systemfonts

### ISSUE THREAD

**Issue by horusra** [CaiJimmy/hugo-theme-stack#240]
![image](https://user-images.githubusercontent.com/17074394/123014914-7f24c180-d3c7-11eb-922e-1204c0a0ed4c.png)
https://systemfontstack.com

it would be great if the theme incorporated systemfonts instead of google fonts

**Comment by CaiJimmy** [comment]
There is a fallback to system font in case Google Font is not available. 

https://github.com/CaiJimmy/hugo-theme-stack/blob/70615246c5e84fa5effc5a42199824154aa4c019/assets/scss/variables.scss#L57-L61
