### ISSUE TITLE
contact and webmention

### ISSUE THREAD

**Issue by horusra** [CaiJimmy/hugo-theme-stack#241]
It would be great to have a basic [contact form](https://themes.gohugo.io//theme/Blonde/contact/)
![image](https://user-images.githubusercontent.com/17074394/123008871-fce2d000-d3bb-11eb-86f7-e2f72febf827.png)

and integrated [webmention support](https://anaulin.org/blog/adding-webmentions/) with[ manual submission form](https://webmention.io/anaulin.org/webmention).

That way blogs can be more [easily connected and communicate](https://indieweb.org/Webmention) with each other.
![image](https://user-images.githubusercontent.com/17074394/123009203-91e5c900-d3bc-11eb-85f2-9cd8b0372cc9.png)

**Comment by CaiJimmy** [comment]
> It would be great to have a basic contact form

Since this theme already has support for the comment system, I don't really see this as something necessary for a blog. Besides, it requires the integration of a third-party service.

> and integrated webmention support with manual submission form.

Nice thing to have, but it requires many works to make it look good. And to be honest, I don't have much interest to implement this 😓. Sorry.

**Comment by horusra** [comment]
@CaiJimmy 
> > and integrated webmention support with manual submission form.
> 
> Nice thing to have, but it requires many works to make it look good. And to be honest, I don't have much interest to implement this 😓. Sorry.
Did you perhaps see this article? https://anaulin.org/blog/adding-webmentions/
it used this https://github.com/PlaidWeb/webmention.js for displaying the webmentions

However if this is too much work, I understand. You already made a great theme (the best one for Hugo imo)
