### ISSUE TITLE
incorrect image path

### ISSUE THREAD

**Issue by ccqstark** [CaiJimmy/hugo-theme-stack#266]
## Describe the bug
I update the theme to the lastest version and build the site, found that it generated the incorrect image path and the images  can not display.

## Expected behavior
The url of the images in one of the post should not add the `/` before the relative path which could make the url wrong, but the new version did add it.

## Screenshots
* old version
[![W86NX4.png](https://z3.ax1x.com/2021/07/18/W86NX4.png)](https://imgtu.com/i/W86NX4)
* new version
[![W86anJ.png](https://z3.ax1x.com/2021/07/18/W86anJ.png)](https://imgtu.com/i/W86anJ)

## Environment

- **Hugo version** 0.80.0
- **Hugo extended?**: Yes

If it's a UI issue, fill the following information:

 - MacOS10.14.6
 - chrome
 - Version 91.0.4472.114

## Link to the demo site and/or source repository
https://ccqstark.github.io/p/remove_elements/

**Comment by CaiJimmy** [comment]
Please provide the source of the website (before compilation).

**Comment by ccqstark** [comment]
https://github.com/ccqstark/hugo-raw

**Comment by CaiJimmy** [comment]
Try if the following solutions work:

- Use English folder name to store images
- Don't use nested folders to store images

**Comment by ccqstark** [comment]
But in the old version, using Chinese folder name and using folders to store images have no problem, the image can display normally. I  update the version to use the new feature toc, before that the image paths are all correct.

**Comment by CaiJimmy** [comment]
No idea what broke that behavior. 🤷‍♂️

`render-image.html`, which is responsible to render post image, hasn't been changed for months: https://github.com/CaiJimmy/hugo-theme-stack/blob/master/layouts/_default/_markup/render-image.html

**Comment by ccqstark** [comment]
All right, thank you. I will try another way to slove.
