### ISSUE TITLE
Unable to use my own avatar image

### ISSUE THREAD

**Issue by codaamok** [CaiJimmy/hugo-theme-stack#27]
**Describe the bug**
I'm unable to specify my own avatar image.

If I place my own image in `static/img/avatar.png`, the place holder (grey circle with 150x150 written in the middle) is still there. 

Source is
```html
<img src="/img/avatar_huda2458f72ce188392d75c5d51cd8e24e_373_300x300_resize_box_2.png" width="300" height="300" class="site-logo" loading="lazy" alt="Avatar">
```

See this live on https://new.cookadam.co.uk.  My config.toml is simply:

```toml
    [params.sidebar]
        emoji = "🙃"
        avatar = "img/avatar.png"
```

**To Reproduce**
1. Store avatar.png (Which is different to default) in `static/img/avatar.png`
2. Execute `hugo server`
3. Observe previously described state.

**Expected behavior**
My own image to appear, not the default.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge (chromium)
 - Version [e.g. 22] Version 85.0.564.68 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ress997** [comment]
I faced the same problem.
Use an image from the `assets` folder.

Try the following command
```
mkdir -p assets/img
mv static/img/avatar.png assets/img/avatar.png
```

**Comment by codaamok** [comment]
Thanks @ress997 !

**Comment by ress997** [comment]
I think it would be good to enhance the documentation so that this problem does not occur again.

But I am not a good English speaker so I would like to ask someone else to help me out.

**Comment by CaiJimmy** [comment]
> I think it would be good to enhance the documentation so that this problem does not occur again.
> 
> But I am not a good English speaker so I would like to ask someone else to help me out.

It's included in the documentation: https://www.notion.so/jimmycai/Configuration-61531ace450d4be8a9a3d2474319bc24#bd1da7ff11ed49b7a3f8816b05fb3e49

Documentation is currently hosted in Notion.so, people can leave a comment if they found anything strange or wrong. 

But yes, this project's documentation should be improved. I've planned to create a separated documentation site when I got time to do so.

**Comment by codaamok** [comment]
I'm sorry I did not fully read documentation first, thank you for a nice theme 👍

**Comment by ress997** [comment]
Sorry, I'd seen this site before but hadn't looked at it in detail.
https://www.notion.so/Documentation-f345a3a28fb74e89a3b7490989781a04

I didn't understand it at first because I only looked at `exampleSite/config.toml`.
But I saw the code and found out that I should add it to the `assets` folder.

**Comment by CaiJimmy** [comment]
It's okay. No worries :)

**Comment by wastu01** [comment]
the documentation in notion is break. I meet the same problem

**Comment by CaiJimmy** [comment]
> the documentation in notion is break. I meet the same problem i can not using my icon even move to asset folder

The documentation site had moved to https://stack.jimmycai.com

Please check https://github.com/CaiJimmy/hugo-theme-stack-starter/ for a complete example. The starter template has custom avatar set up.

**Comment by wastu01** [comment]
I fixed that according this step below
---
1. checking config setting is right
2. adding  right size / resolution image format 
3. put it into static folder (e.g : static/img/favicon.png)
---

<img width="451" alt="截圖 2023-10-08 上午3 27 46" src="https://github.com/CaiJimmy/hugo-theme-stack/assets/47618277/a80aa95d-fa65-47f2-b975-5b07071371cd">

**Comment by buti1021** [comment]
> ## I fixed that according this step below
> 1. checking config setting is right
> 2. adding  right size / resolution image format
> 3. put it into static folder (e.g : static/img/favicon.png)
> 
> <img alt="截圖 2023-10-08 上午3 27 46" width="451" src="https://private-user-images.githubusercontent.com/47618277/273405585-a80aa95d-fa65-47f2-b975-5b07071371cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0Nzc1NTgsIm5iZiI6MTcxNjQ3NzI1OCwicGF0aCI6Ii80NzYxODI3Ny8yNzM0MDU1ODUtYTgwYWE5NWQtZmE2NS00N2YyLWI5NzUtNWIwNzA3MTM3MWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE1MTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNzI2YWYyMDFmZTFkOTVjNWM4YTAzOGYzMGJmZmYxZDdlNDFiN2VjZjY4M2E1ZjNiYTIyZDc0MjEwMTExZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQsloSXxd_tu23tx5TxoFTK6ZvpzwFwkejP5J2m5kH8">

For me it had to be in the assets folder, not static folder
