### ISSUE TITLE
配置favicon后，只有首页显示favicon

### ISSUE THREAD

**Issue by iwyang** [CaiJimmy/hugo-theme-stack#272]
其他页面都不显示，什么问题？

**Comment by Weltolk** [comment]
> 其他页面都不显示，什么问题？

请问解决了吗.我配置了图标之后也是这样,本地和github page都这样

**Comment by iwyang** [comment]
图标放在`/static/img`文件夹下，然后设置：
```
 favicon: /img/favicon.png
```

**Comment by Weltolk** [comment]
> 图标放在`/static/img`文件夹下，然后设置：
> 
> ```
>  favicon: /img/favicon.png
> ```

谢谢,请问static文件夹是在站点根目录下还是在stack这个主题的根目录下呢?

**Comment by iwyang** [comment]
> > 图标放在`/static/img`文件夹下，然后设置：
> > ```
> >  favicon: /img/favicon.png
> > ```
> 
> 谢谢,请问static文件夹是在站点根目录下还是在stack这个主题的根目录下呢?

根目录

**Comment by Weltolk** [comment]
> > > 图标放在`/static/img`文件夹下，然后设置：
> > > ```
> > >  favicon: /img/favicon.png
> > > ```
> > 
> > 
> > 谢谢,请问static文件夹是在站点根目录下还是在stack这个主题的根目录下呢?
> 
> 根目录

好的,谢谢

**Comment by Weltolk** [comment]
> > > 图标放在`/static/img`文件夹下，然后设置：
> > > ```
> > >  favicon: /img/favicon.png
> > > ```
> > 
> > 
> > 谢谢,请问static文件夹是在站点根目录下还是在stack这个主题的根目录下呢?
> 
> 根目录

老哥,你的其他页面也显示了吗,我这样配置还是不显示

**Comment by zhixuan666** [comment]
![image](https://user-images.githubusercontent.com/59254886/128016996-2a4d4b71-8fed-4696-ace8-78ff0b4631d2.png)

**Comment by Weltolk** [comment]
谢谢,解决了 @zhixuan666

**Comment by whuwangyong** [comment]
如果忘了 `/img/favicon.ico` 前面的 `/` ，就会造成只有首页显示。

**Comment by Weltolk** [comment]
> 如果忘了 `/img/favicon.ico` 前面的 `/` ，就会造成只有首页显示。

是这样的,前两天又犯了一次这个错误,建议文档里加上这一条
