### ISSUE TITLE
使用主题出错

### ISSUE THREAD

**Issue by Lincyaw** [CaiJimmy/hugo-theme-stack#282]
## 报错
![image](https://user-images.githubusercontent.com/53161583/127259142-19b62d5b-e0fd-4ce0-ba8d-8deada80a1a8.png)
## 步骤
```
hugo new site test
git init
git submodule add https://github.com/CaiJimmy/hugo-theme-stack/ themes/hugo-theme-stack
```
接下来我把 `config.toml` 删除了，并且把 `config.yaml` 移到了站点目录中。

并且还把 `exampleSite` 里的 content 内容也全都移了出来，依旧出现上面的报错

![image](https://user-images.githubusercontent.com/53161583/127259277-4964e48d-a2cc-49e3-ba3a-1cada62e40b2.png)

**Comment by zhixuan666** [comment]
请提供hugo版本

**Comment by Lincyaw** [comment]
不好意思，我是用 apt 源安装的，忘记看版本了。。
```
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z
```
