### ISSUE TITLE
本地测试显示图片,上传到github之后不显示了

### ISSUE THREAD

**Issue by Weltolk** [CaiJimmy/hugo-theme-stack#287]
我用的你的项目里的测试站点文件夹里的content,http://127.0.0.1:1313/archives/ 页面里的顶部CATEGORIES下的第一个,TEST选项卡的背景图,本地会显示,上传到github之后此页面的这个选项卡的背景图不显示了,F12显示404,但是实际上github的项目里是有这张图的,而且直接访问这张图的url也提示404

github项目地址:[https://github.com/Weltolk/Weltolk.github.io](https://github.com/Weltolk/Weltolk.github.io)
github pages url:[https://weltolk.github.io/examplesite/page/archives/](https://weltolk.github.io/examplesite/page/archives/)

**Comment by zhixuan666** [comment]
https://github.com/CaiJimmy/hugo-theme-stack/issues/198#issuecomment-826964724

pleass add `nojekyll` at root

**Comment by Weltolk** [comment]
> [#198 (comment)](https://github.com/CaiJimmy/hugo-theme-stack/issues/198#issuecomment-826964724)
> 
> Add `.nojekyll` at root

thx,solved

**Comment by zhixuan666** [comment]
Please close this issue.🙂

**Comment by Weltolk** [comment]
> Please close this issue.🙂

ok
