### ISSUE TITLE
将博客挂载到子目录后报错

### ISSUE THREAD

**Issue by Lincyaw** [CaiJimmy/hugo-theme-stack#291]
我想把博客挂载到子目录中:
![image](https://user-images.githubusercontent.com/53161583/128593303-c08c28ff-117c-4493-8b2a-60c9a27cc706.png)
但这样设置后，运行 `hugo server`会导致下面的错误：

![image](https://user-images.githubusercontent.com/53161583/128593324-f3a98b82-0d6f-4771-96b4-b498cffbb22a.png)
hugo版本为
![image](https://user-images.githubusercontent.com/53161583/128593327-2ac64c0e-a08d-40e5-8277-c9ad81f99693.png)

将子目录去掉就没问题

**Comment by CaiJimmy** [comment]
请安装 Hugo Extended 版本。

**Comment by Lincyaw** [comment]
可以了，非常感谢！
