### ISSUE TITLE
“最后更新于”前面空格太长了

### ISSUE THREAD

**Issue by iwyang** [CaiJimmy/hugo-theme-stack#300]
![空格太长了](https://cdn.jsdelivr.net/gh/iwyang/pic/202108121555733.png)

这两行能不能对齐。

**Comment by iwyang** [comment]
发现v2.6.0版本是对齐的：
![](https://cdn.jsdelivr.net/gh/iwyang/pic/202108121622474.png)

**Comment by astropenguin** [comment]
I am having the same issue and the quick workaround is adding the following CSS to `assets/scss/custom.scss`.

```css
.article-footer > .article-time {
    gap: 0px;
}
```

The cause may be that the same style (`.article-time`) is applied to both (1) the reading time just below the title and (2) the last-updated date in the footer: while the former needs the gap, the latter does not.

Anyway thank you for making such a nice theme!
