### ISSUE TITLE
Add support for comment provider disqusJS

### ISSUE THREAD

**Issue by ShadowySpirits** [CaiJimmy/hugo-theme-stack#305]
**Is your feature request related to a problem? Please describe.**
Disqus blocked in some internet censorship countries. So it is necessary to support the basic mode of disqus that can read reviews in Internet censorship countries.

**Describe the solution you'd like**
[SukkaW/DisqusJS](https://github.com/SukkaW/DisqusJS) implements this basic mode well. I integrated disqusJS into stack as a comment provider. If you consider accepting this proposal, I am willing to submit a pr.

screenshot:
light mode:
![image](https://user-images.githubusercontent.com/32436597/129437695-33a7a986-00a7-4611-9fe8-bd964348594a.png)

dark mode:
![image](https://user-images.githubusercontent.com/32436597/129437928-77e50b3b-9d3d-43a6-a13c-ee9c876063be.png)

**Comment by ShadowySpirits** [comment]
PS. disqusJS can detect whether disqus can be accessed to automatically switch between normal mode and basic mode.

demo: https://blog.lv5.moe/p/nginx-ssl-tls-configuration-optimization/

**Comment by CaiJimmy** [comment]
👍 Looks good to me. PR is welcome.
