### ISSUE TITLE
Default image for posts

### ISSUE THREAD

**Issue by ShadowySpirits** [CaiJimmy/hugo-theme-stack#308]
**Is your feature request related to a problem? Please describe.**
I found that the default image can be configured for opengraph. Is it possible to add the function of setting the default image for posts?

**Describe the solution you'd like**
Add configuration items as shown in the figure:

![image](https://user-images.githubusercontent.com/32436597/129477964-d2805a39-c3e5-4296-ad75-4cf0e5985145.png)

It would be better if you provide some default options such as random local pictures, random pictures api, random color blocks, etc.

**Comment by CaiJimmy** [comment]
Use `defaultImage.articleList` and `defaultImage.article`

**Comment by CaiJimmy** [comment]
It's undocumented, hence can be removed in future updates.

**Comment by ShadowySpirits** [comment]
> It's undocumented, hence can be removed in future updates.

Why? It seems like a great feature, especially with random image api.

**Comment by CaiJimmy** [comment]
Because Hugo has a `cascade` feature that allows you to do basically the same thing: https://gohugo.io/content-management/front-matter#front-matter-cascade
