### ISSUE TITLE
移动端适配SideBar适配Toc。桌面与移动端增加返回顶部的按钮

### ISSUE THREAD

**Issue by linsn0w** [CaiJimmy/hugo-theme-stack#309]
上次提交的bug已经得到解决，感谢，目前桌面端阅读文章时已经左上角已经有返回按钮了。
这次希望作者可一给主题增加一个返回顶部的按钮和让移动端能够使用Toc
这有点麻烦，再次感谢作者，我的blog:https://l1nsn0w.gitee.io

**Comment by CaiJimmy** [comment]
抱歉，没打算增加这两个功能。
