### ISSUE TITLE
v3.1.0 dark mode doesn't work

### ISSUE THREAD

**Issue by jokefrelon** [CaiJimmy/hugo-theme-stack#310]
I'm sure I have dark mode enabled, but it doesn't work

**Comment by jokefrelon** [comment]
Sorry! I've configured the wrong parameters!

**Comment by zhixuan666** [comment]
please use Bug report.

**Comment by CaiJimmy** [comment]
![](https://user-images.githubusercontent.com/5889006/129692371-181ee080-6702-4819-955a-4ce7d9b4f9db.png)

A bug report without any details is useless. The dark mode in the demo site works well for me.
