### ISSUE TITLE
How can I make the header image clickable for gallery view?

### ISSUE THREAD

**Issue by gschmois** [CaiJimmy/hugo-theme-stack#311]
Hello,

Currently, when inside of an article, clicking the header image redirects to the current page. Instead, I would like to have a click open the gallery view as it does it for a regular image (overlay with the zoom/share buttons etc). This would allow the reader to view the header image more in detail.

As a workaround, I can put the same picture twice in the same article: once as the "featured image" (which is then also shown as the header image) and then again inside of an article. But I find that a bit redundant. Unfortunately, I haven't managed to adapt the theme's code to this specific need.

Do you see a way on how to do that without turning everything upside down?

**Comment by CaiJimmy** [comment]
> Do you see a way on how to do that without turning everything upside down?

Nope. I didn't think about that possibility while creating this theme.

The problem I see here is that the featured image does not preserve the original aspect ratio of the image (a `max-height` is applied), so the light box effect (scale out) probably will feel buggy.

**Comment by gschmois** [comment]
Alright, thanks for the quick reply! Then I think I am just going to replace the featured image from the header of the article page by a regular picture.

Great theme by the way! One of the few that is content-focused but still has decent image support. Thanks for sharing it :+1:
