### ISSUE TITLE
瀏覽器放最大的文章寬度過寬

### ISSUE THREAD

**Issue by Peckystudios** [CaiJimmy/hugo-theme-stack#313]
哈囉！
我就直接用中文囉～
比較好溝通

我發現當我開啓我的部落格，並且將瀏覽器放到自動滿版時，文章寬度會非常寬，在閱讀上不是很舒服。
但如果我稍微把瀏覽器視窗拉小，他就會跳回閱讀比較舒適的寬度。
![image](https://user-images.githubusercontent.com/84195047/129870832-60431318-6fc0-45a2-91fa-3eeaefc32347.png)
放到最大
![image](https://user-images.githubusercontent.com/84195047/129870902-b125e640-043b-4a82-9e94-465818365041.png)
稍微拉小

（另外我的目錄功能開起來網頁沒有反應，可能有什麼東西被我的設定蓋掉了吧～？）

## Expected behavior

希望瀏覽器視窗放最大時文章寬度可以是閱讀舒服的寬度。

## To Reproduce
Indicate the steps to reproduce this bug, if applicable.
- 開啓 https://peckystudios.com 任何一個文章
- 使用chrome （mac）按左上角的黃色按鈕放到最大
- 會發現文章寬度很寬，文字很長。

## Environment

- **Hugo version** [e.g: 0.80.0]: hugo v0.83.1+extended darwin/arm64 BuildDate=unknown

## Additional context

If it's a UI issue, fill the following information:

 - OS: [e.g. iOS] Mac OS 11.4 big sur
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22]  92.0.4515.159 (正式版本) (arm64)

## Link to the demo site and/or source repository
https://github.com/Peckystudios/PeckyPlayZone

**Comment by zhixuan666** [comment]
> （另外我的目錄功能開起來網頁沒有反應，可能有什麼東西被我的設定蓋掉了吧～？）

要使用之后的版本v2.4.0

**Comment by Peckystudios** [comment]
@zhixuan666 
謝謝你

我是有下載最新版覆蓋我的主題，
不知道這個做法會不會造成什麼問題🤔️

**Comment by CaiJimmy** [comment]
不推荐这样覆盖更新主题，推荐直接更新 git submodule

我看你仓库里面的主题 submodule 还是 2.3.0 版本的

**Comment by Peckystudios** [comment]
QQ
那我現在還有救嗎
我沒有備份覆蓋前的檔案

**Comment by CaiJimmy** [comment]
试试看在站点目录运行 `git submodule update --remote --merge` 应该就能更新到最新版本的主题了。

你直接在本地覆盖，因为是 submodule，加上你没有仓库权限，更改应该是无法提交到 Git 的

**Comment by zhixuan666** [comment]
config 下面添加
```yml
markup:
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 1
```
![image](https://user-images.githubusercontent.com/59254886/129878091-24ecdeb6-0513-4b60-98d9-d15d25fa8c8f.png)

toc 好像和本地的 `assets/scss` , `layouts`有冲突

**Comment by Peckystudios** [comment]
@CaiJimmy 
謝謝 原來是這樣
有成功更新了
不過最後有跳出這行字
![image](https://user-images.githubusercontent.com/84195047/129879174-ab1c152e-dae8-4377-9251-8269861eca16.png)
可能也是什麼被我動到..
![image](https://user-images.githubusercontent.com/84195047/129879260-9aa36602-1c8c-447f-a110-6987739c5f67.png)
github 一直以來都會顯示這個，但我不知道是什麼意思，因為更新文章沒什麼問題就先放著。

@zhixuan666 
謝謝你

我試了，但還是沒有目錄跑出來
我也不知道怎麼回事😓️

我有更新檔案到github了
提供給你們參考～
謝謝你們！

**Comment by CaiJimmy** [comment]
可以试试看重新开一个站点，然后把除了 `themes` 文件夹以外的内容转移过去

**Comment by Peckystudios** [comment]
@CaiJimmy 
謝謝你

@zhixuan666 
也謝謝你幫我弄了一版
下載下來試過之後也是和下面一樣的問題

剛剛測試把多餘的自訂layout 刪除
有出現目錄，只是格式明顯和example site 不一樣

會需要自訂是因爲我要加入訂閱視窗
不知道有沒有影響
我只有在layout檔案裏面加一行
`    {{ partial "subscribe.html" . }}
`
像這種

其他都是之前還沒有新增點擊連結開新視窗加的，已刪除
還有GA

---

我也另外開一個新網站試試看
奇怪的是當我把content移到新網站
還有照文件裡面說的assets複製出來
TOC目錄有跑出來
但看起來格式和examplesite不太一樣
也少了回上一頁的按鈕，和我現在上線的網站一樣問題

我是用指令clone主題下來，因為我先使用submodule他沒反應
跳出下面這句
![image](https://user-images.githubusercontent.com/84195047/130008711-e90a03fb-fe2c-4ca5-883b-4a0f13ec9912.png)


![image](https://user-images.githubusercontent.com/84195047/130008418-0b98c1e1-94be-4988-a9d4-4e5e4e48b8a4.png)
![image](https://user-images.githubusercontent.com/84195047/130008498-d4d5772b-3a2d-4b2a-85e7-4248b8061ab0.png)

雖然可以用就很開心了
還是回來回報問題給你們～

真的很謝謝你們！

**Comment by zhixuan666** [comment]
应该是站点下的 scss 问题
删除 `assets/scss` 试试

**Comment by CaiJimmy** [comment]
> TOC目錄有跑出來
> 但看起來格式和examplesite不太一樣

也可以试试看更新到最新版本的 Hugo Extended

**Comment by Peckystudios** [comment]
隔了一天，我什麼都沒有動
一用hugo server
網頁就正常了...
現在正常顯示
![image](https://user-images.githubusercontent.com/84195047/130201633-a016bc90-5e36-438e-a354-5c1f4860de3a.png)

倒是首頁多出了滑軌
![image](https://user-images.githubusercontent.com/84195047/130201706-40031db3-3cce-4a1a-85a4-39f58b7c7b50.png)

還是回報一下給你們做參考～
謝謝你們
