### ISSUE TITLE
在中国大陆使用请求超时

### ISSUE THREAD

**Issue by wdx6** [CaiJimmy/hugo-theme-stack#316]
第一次使用
当我执行  `` hugo server http://localhost:1313 ``时就报错，我没有翻墙工具
请问怎样解决呢？
以下是错误信息

`` Start building sites …
hugo v0.87.0-B0C541E4 windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
ERROR 2021/08/19 22:13:09 Failed to get JSON resource "https://api.twitter.com/1/statuses/oembed.json?id=1085870671291310081&omit_script=true": Get "https://api.twitter.com/1/statuses/oembed.json?id=1085870671291310081&omit_script=true": net/http: TLS handshake timeout
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]
Error: Error building site: "E:\hugoweb\myblogfiles\content\post\rich-content\index.md:1:1": timed out initializing value. You may have a circular loop in a shortcode, or your site may have resources that take longer to build than the `timeout` limit in your Hugo config file.
Built in 30074 ms ``

**Comment by CaiJimmy** [comment]
删除 `content\post\rich-content`

**Comment by wdx6** [comment]
> 删除`content\post\rich-content`

非常感谢，问题已经解决
