### ISSUE TITLE
自訂的訂閱視窗跑不出來（可能是Netlify這邊有問題）

### ISSUE THREAD

**Issue by Peckystudios** [CaiJimmy/hugo-theme-stack#317]
## Describe the bug
在前面的問題解決之後，發現另一個問題
我的訂閱視窗在local端有看到
但netlify deploy之後不見了

我有2種視窗
一個是在每一篇文章下面的訂閱視窗
另一個是進到首頁會自動跳出的pop up 視窗

也許是netlify這段有問題也說不定..
好像部署上去都會和原先有部分不同

## Expected behavior
顯示文章末訂閱視窗與首頁pop up 視窗

## To Reproduce
可能要直接用local端開啓我的hugo網站
可以比對 https://peckystudios.com 網站

## Screenshots
預期要有這個視窗
![image](https://user-images.githubusercontent.com/84195047/130203316-37c397ed-7262-4d1d-96c3-ff7972086e97.png)

deploy之後消失，而且界面還和原本的不同
![image](https://user-images.githubusercontent.com/84195047/130203476-ed2aa501-4910-45e1-bae9-b34b51de469d.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: hugo v0.83.1+extended darwin/arm64 BuildDate=unknown
- **Hugo extended?**: Yes

## Additional context

If it's a UI issue, fill the following information:

 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] CHROME

## Content of config.yaml
```yaml
### Paste the content of the config file here
```

## Link to the demo site and/or source repository
https://github.com/Peckystudios/PeckyPlayZone

**Comment by zhixuan666** [comment]
repo 里的 theme version 是 2.3.0 
Toc 的版本是 2.4.0

**Comment by Peckystudios** [comment]
@zhixuan2333 
謝謝你

我終於成功了...
才發現是因為不熟github 一直沒有把themes內容推上去

真是太感謝你們了！！

**Comment by zhixuan2333** [comment]
please close.
