### ISSUE TITLE
希望能添加不蒜子

### ISSUE THREAD

**Issue by waimao365** [CaiJimmy/hugo-theme-stack#321]
主题非常好看，希望能添加不蒜子，显示网站的总访客和文章访客数量

**Comment by CaiJimmy** [comment]
我觉得这个自己修改主题添加会比较好。

Related: https://github.com/CaiJimmy/hugo-theme-stack/issues/312

**Comment by linsn0w** [comment]
> 主题非常好看，希望能添加不蒜子，显示网站的总访客和文章访客数量

我的博客里有关于这个主题添加不蒜子的教程，可以去试试
