### ISSUE TITLE
SVG Relative Paths not working

### ISSUE THREAD

**Issue by franziskuskiefer** [CaiJimmy/hugo-theme-stack#324]
## Describe the bug
Trying to add an svg image in a relative path is not possible.
`![svg-image](./svg-image.svg)`

## Expected behavior
The image should be displayed.

## To Reproduce
1. Add svg image in a relative path `![svg-image](./svg-image.svg)`
2. Start the hugo server `hugo serve`
3. The svg is included as `<img src="/svg-image.svg" alt="">`

## Environment

- **Hugo version** v0.87.0
- **Hugo extended?**: Yes

## Content of config.yaml
https://github.com/CaiJimmy/hugo-theme-stack/blob/master/exampleSite/config.yaml

**Comment by zhixuan2333** [comment]
#183

**Comment by franziskuskiefer** [comment]
> #183

Right, I've seen the other SVG related issues. But does this imply that paths have to be absolute?

**Comment by CaiJimmy** [comment]
Where is the SVG file placed? Inside the page bundle?

**Comment by franziskuskiefer** [comment]
The SVG is placed next to the md file in a post folder. So something like the following should work to reproduce on the example page.
1. Create a new post in `content/post/svg-test/index.md`
2. Add `content/post/svg-test/svg-imge.svg`
3. Add the svg image to `index.md` `![svg-image](./svg-image.svg)`
4. Start the hugo server `hugo serve`
3. The svg is included as `<img src="/svg-image.svg" alt="">`

**Comment by CaiJimmy** [comment]
Try use `![svg-image](svg-image.svg)`

**Comment by franziskuskiefer** [comment]
> Try use `![svg-image](svg-image.svg)`

That's replaced the same way, i.e. results in `<img src="/svg-image.svg">`

**Comment by CaiJimmy** [comment]
Should work now.
