### ISSUE TITLE
Categories thumbnail pic on "Archive" page failed to load on gh-pages

### ISSUE THREAD

**Issue by gasfad01test** [CaiJimmy/hugo-theme-stack#330]
Hello, I use your theme for my gh-page. The theme is simply awesome I really like it, but there is an issue where the categories thumbnail pic on "Archive" page failed to load for my (or maybe others) gh-page. I think it was because the file name. After I generate it to `/public` with `hugo -t hugo-theme-stack` the original file get resized and generated as a new file to match the size of the categories thumbnail pic. And the newly generated file names like this `/categories/general/_hu4045dfe93447d7a345514b7fc9e315e7_1084522_bf387d5a1089bf0b9e06001554c5d5f2.jpg` I think somehow the underscores broke some other stuffs so it is failed to load. Can you fix this please?

**Comment by CaiJimmy** [comment]
See https://github.com/CaiJimmy/hugo-theme-stack/issues/198#issuecomment-826964724
