### ISSUE TITLE
似乎无法创建嵌套页面

### ISSUE THREAD

**Issue by Lincyaw** [CaiJimmy/hugo-theme-stack#337]
![image](https://user-images.githubusercontent.com/53161583/131132114-625ae2dc-e652-4c8c-84af-4dc796f7ca51.png)

我的目录结构如图。我想做的是在 algorithm 这篇文章中，能够链接到其他的文章，比如 《整数》《树》。

因为这些内容如果全部放到同一篇里的话，篇幅会太长。但是我又不想把所有的内容以平面的形式展示出来。

根据[官方给的文档](https://gohugo.io/content-management/organization/)，我这样的目录设置应当可以在预览的时候，在`localhost:9999/p/algorihms/integer/`这样的目录下看到文章。但是并没有html文件被生成。

请问这是什么原因呢

**Comment by zhixuan2333** [comment]
如果实在不行可以在FrontMatter里添加
```yaml
hidden: true
```

**Comment by CaiJimmy** [comment]
我如果没理解错的话，Hugo 支持的是 Nested Section，并不是文章嵌套。

主题有 Nested Section 支持。如果要把 algorithms 变成一个 Subsection，请把 `algorithms/index.md` 改成 `algorithms/_index.md`

**Comment by zhixuan2333** [comment]
_index.md的文件夹放到 content 下面
![image](https://user-images.githubusercontent.com/59254886/131636438-03cce43e-e1ae-4c6f-b393-3b84035f98b3.png)

**Comment by Lincyaw** [comment]
![image](https://user-images.githubusercontent.com/53161583/131642245-ff96cf03-0112-4589-a082-f5e8e044e23a.png)
我的目录如上面所示
![image](https://user-images.githubusercontent.com/53161583/131642412-73ba8990-b04c-4dd8-b5d9-b888f28353cf.png)
header如上所示。

这样的配置能够通过url进入这个页面，但是我要怎么从主页里进入呢？
![image](https://user-images.githubusercontent.com/53161583/131642549-d065c35f-4e97-4f33-94b7-ad08e438ea99.png)
在主页中找不到明显的这样的section的入口

**Comment by CaiJimmy** [comment]
> 在主页中找不到明显的这样的section的入口

因为 section 不算文章，所以不会在主页显示出来。如果你把 algorithms 变成 post 的 Subsection （移动到 `content/post/algorithms/`），可以通过访问 `SITE_URL/post/` 看到有这个 Subsection
