### ISSUE TITLE
图片bug

### ISSUE THREAD

**Issue by linsn0w** [CaiJimmy/hugo-theme-stack#340]
在iPhone上的safari打开图片预览后点击右上角的关闭按钮失效，点击后没作用，无法关闭图片。
在电脑上edge打开图片后没有关闭按钮，只能按返回上一步才嫩给关闭图片预览
希望能修复以下
谢谢主题大大

**Comment by zhixuan2333** [comment]
Please use the "Bug report" issue template, and provide more information like screen resolution.
使用 bug 反馈模板，你说的东西都在demo上正常运行。

**Comment by CaiJimmy** [comment]
抱歉，无法在 iPadOS 15 的 Safari 上重现。

Can't reproduce it on Safari @ iPadOS 15. Close this issue for now.

**Comment by Mantyke** [comment]
> 抱歉，无法在 iPadOS 15 的 Safari 上重现。
> 
> 无法在 Safari @ iPadOS 15 上重现它。暂时关闭此问题。

这个问题我也碰见了，不清楚是否一致，我这边是PC端，用markdown语法加入外链图片，点击图片没有灯箱效果，而是直接打开外链地址，所以会没有关闭按钮。
