### ISSUE TITLE
Click on image to redirect to another link doesn't work

### ISSUE THREAD

**Issue by dag7dev** [CaiJimmy/hugo-theme-stack#341]
## Describe the bug
You want to reproduce this:
- have an image
- when you click on it, it will redirect to another custom website

## Expected behavior
It doesn't work. I tried every means, it simply doesn't work, it only shows an image but no "click and go to link".

## To Reproduce
These are ways to "embed" something to an image:
```
[<img src="http://www.google.com.au/images/nav_logo7.png">](http://google.com.au/)
[![Foo](http://www.google.com.au/images/nav_logo7.png)](http://google.com.au/)
<a href="http://google.com.au/" rel="some text">![Foo](http://www.google.com.au/images/nav_logo7.png)</a>
```
None of them work.

Source: https://meta.stackexchange.com/questions/38915/creating-an-image-link-in-markdown-format

Tried this too: https://discourse.gohugo.io/t/adding-a-link-to-an-image-in-a-md-file-that-opens-another-md-file/6425/3

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.87.0
- **Hugo extended?**: Yes

Is there a way?

**Comment by CaiJimmy** [comment]
Set `markup.goldmark.renderer.unsafe` to true:

(add following block in `config.yaml`)

```yaml
markup:
    goldmark:
        renderer:
            unsafe: true
```

**Comment by dag7dev** [comment]
@CaiJimmy as a temporary workaround, it works, but I don't think allowing html is a good thing, it may breaks other things.

**Comment by CaiJimmy** [comment]
Close this for now, since there's no way for `render-image.html` to tell if it's being wrapped by a `<a>` tag or not, and there's a workaround for that indicated above.
