### ISSUE TITLE
请问归档页面这个分类横幅在哪里设置？能删除吗？

### ISSUE THREAD

**Issue by HelIwalker** [CaiJimmy/hugo-theme-stack#353]
![屏幕截图 2021-09-16 154529](https://user-images.githubusercontent.com/19471848/133572739-df4ed286-eb6f-4cdd-b189-2df00fbe93e2.png)

**Comment by zhixuan2333** [comment]
看 [https://docs.stack.jimmycai.com/zh/taxonomy/](https://docs.stack.jimmycai.com/zh/taxonomy/)

**Comment by HelIwalker** [comment]
> https://docs.stack.jimmycai.com/zh/taxonomy/

非常感谢，在config.yaml里加上这个解决了
disableKinds: #不创建任何分类
- taxonomy
- term

现在还有个小问题，文章里这个返回键不生效，点了返回就和刷新界面差不多，不会返回。请问这个代码在哪里呢？不行我就删掉好了

**Comment by zhixuan2333** [comment]
代码：
https://github.com/CaiJimmy/hugo-theme-stack/blob/41fa65cbf5c43301c56b74a7cb2a8bb2edc54f1e/layouts/_default/single.html#L29-L40

是不是没设置BaseURL啊？

**Comment by HelIwalker** [comment]
> 代码：
> https://github.com/CaiJimmy/hugo-theme-stack/blob/41fa65cbf5c43301c56b74a7cb2a8bb2edc54f1e/layouts/_default/single.html#L29-L40
> 
> 巴塞普尔 · 阿夫？

是的，是要留空还是填什么地址？

**Comment by zhixuan2333** [comment]
网站的域名
example 
www.example.com
