### ISSUE TITLE
"Index of untyped nil" error on helper/image.html

### ISSUE THREAD

**Issue by ttheng3810** [CaiJimmy/hugo-theme-stack#357]
Hello, when I previously updated the theme files from v2.5.0 to v3.2.0 (by replacing all of the existing theme files in my site folder with the v3.2.0 one, and then redoing the edits previously done on the theme files, which **does not involve** editing the file ```layouts/partial/helper/image.html```), the following error message occurred as I tried to build the site using Hugo Extended v0.88.1.

```
Error: Error building site: failed to render pages: render of "page" failed: 
execute of template failed: template: _default/single.html:4:12: executing "_default/single.html" at <partial "head/head.html" .>: error calling partial: 
execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: 
execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: 
execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: 
"/(site-folder-path)/themes/hugo-theme-stack/layouts/partials/helper/image.html:31:31": execute of template failed: template: partials/helper/image.html:31:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
```

It seems like the problem lies upon this line in the image.html file:
```
{{ else if and (ne .Type nil) (index .Context.Site.Params.defaultImage .Type) }}
```

However, I am not sure if the cause of the problem is more than that, and I have no idea how to fix it. I would like to seek for a possible solution here. Thank you.

*I use a Linux version of Hugo, by the way.*

**Comment by ttheng3810** [comment]
FYI, the edits done on the theme files include:-
1. Modifying display fonts on the site by adding external font files, adding a ```custom.html``` file as instructed in the documentation and editing ```variables.scss```.
1. Modifying ```single.html``` to include an external partial in single templates.
1. Adding extra partial files and shortcodes in the main site folder, including [hugo-pdf-embed-shortcode](https://github.com/anvithks/hugo-embed-pdf-shortcode).
1. Manually adding translation for another language in ```i18n``` folder.
1.

**Comment by CaiJimmy** [comment]
Please replace your site's `config.yaml` with `exampleSite/config.yaml`. I think there's some theme configuration key missing.

**Comment by ttheng3810** [comment]
Turns out that I have messed up some of the indents of my ```config.yaml``` file, compared to the one in the ```exampleSite``` folder. I have fixed them and the site can be built normally. Thank you for your help.
