### ISSUE TITLE
相关文章的数量如何修改

### ISSUE THREAD

**Issue by faxlok** [CaiJimmy/hugo-theme-stack#358]
![image](https://user-images.githubusercontent.com/67785456/133873192-32bec99e-78f2-4b64-a677-309933d8e749.png)
这里最多全部能显示5个，请问我想显示更多数量怎么办？

**Comment by zhixuan2333** [comment]
https://github.com/CaiJimmy/hugo-theme-stack/blob/7dab67b358b6419e1c182876d89cdfb49b9f5cc2/layouts/partials/article/components/related-contents.html#L2

是写死的

**Comment by faxlok** [comment]
> https://github.com/CaiJimmy/hugo-theme-stack/blob/7dab67b358b6419e1c182876d89cdfb49b9f5cc2/layouts/partials/article/components/related-contents.html#L2
> 
> 是写死的，自行更改

感谢。
