### ISSUE TITLE
左上角的返回按钮疑问

### ISSUE THREAD

**Issue by faxlok** [CaiJimmy/hugo-theme-stack#359]
有时候从标签、种类、搜索等点进网页，但是想按返回，返回到上一页，就会直接回到主页。
然后我把a标签的代码改为history.back()之后虽然好了点，但是当多次点击右侧目录锚点跳转时，再按返回只是退回到上次锚点的地方，怎样能做到回退到真正的上个页面呢？
如果实现多次回退的话页面效果看起来应该会很奇怪吧

**Comment by CaiJimmy** [comment]
> 怎样能做到回退到真正的上个页面呢？

我感觉得上 PJAX 才能更好的解决这个问题。但目前没有这个打算。

#320 里面提到要重新设计文章页面，到时候可能会把这个按钮直接砍了。

**Comment by faxlok** [comment]
> PJAX

我有一个想法不知道可不可行，点击文章时，本地存储记录进入文章之前的地址，然后点返回的话就读取缓存就可以了。不过这样应该会造成历史记录杂乱。
