### ISSUE TITLE
如何取消Archive页面中对Categories图片的颜色修正

### ISSUE THREAD

**Issue by kazami-harutoki** [CaiJimmy/hugo-theme-stack#364]
Archive页面中Categories项指定的图片相比原图片（或者说在单个Categories页面上的图片）似乎蒙上了一层暖色调的颜色，请问这个功能可以取消吗？

**Comment by zhixuan2333** [comment]
把这些注释掉
https://github.com/CaiJimmy/hugo-theme-stack/blob/66bd8a299798b53c78fa4b6b65c5c7256485a029/assets/ts/main.ts#L9
https://github.com/CaiJimmy/hugo-theme-stack/blob/66bd8a299798b53c78fa4b6b65c5c7256485a029/assets/ts/main.ts#L29-L55
https://github.com/CaiJimmy/hugo-theme-stack/blob/66bd8a299798b53c78fa4b6b65c5c7256485a029/layouts/partials/footer/components/script.html#L1

**Comment by kazami-harutoki** [comment]
> 把这些注释掉
> https://github.com/CaiJimmy/hugo-theme-stack/blob/66bd8a299798b53c78fa4b6b65c5c7256485a029/assets/ts/main.ts#L9
> 
> 
> https://github.com/CaiJimmy/hugo-theme-stack/blob/66bd8a299798b53c78fa4b6b65c5c7256485a029/assets/ts/main.ts#L29-L55
> 
> 
> https://github.com/CaiJimmy/hugo-theme-stack/blob/66bd8a299798b53c78fa4b6b65c5c7256485a029/layouts/partials/footer/components/script.html#L1

非常感谢 问题解决了
