### ISSUE TITLE
关于 Archives 中 CATEGORIES 的图片裁切问题

### ISSUE THREAD

**Issue by QIN2DIM** [CaiJimmy/hugo-theme-stack#369]
## 如何修改 Archives 中 CATEGORIES 的样式策略

通过设定 `hugo new categories/go/_index.md` 新建分类，在该 Markdown 文档中配置 `image`可以设计分类的图像。根据文档提示，此处可以指向远程连接以及同目录下的文件，但在指定本地资源的时候图像会自适应裁切（看着不舒服），如何调整类似的样式策略呢- -

## Local

![image](https://user-images.githubusercontent.com/62018067/134603451-009a8b19-a25b-4e1f-acd6-298505819c71.png)

## Remote

![image](https://user-images.githubusercontent.com/62018067/134603473-77609344-0408-42d4-bc03-42893f48a55d.png)

**Comment by zhixuan2333** [comment]
只能自定义...
```html
<!-- layouts\partials\article-list\tile.html -->
{{ $image := partialCached "helper/image" (dict "Context" .context "Type" .Type) .context.RelPermalink .Type }}
<article class="{{ if $image.exists }}has-image{{ end }}">
    <a href="{{ .context.RelPermalink }}">
        
        {{ if $image.exists }}
            <div class="article-image">

                    <img src="{{ $image.permalink }}" loading="lazy" data-key="{{ .context.Slug }}" data-hash="{{ $image.permalink }}"/>

            </div>
        {{ end }}

        <div class="article-details">
            <h2 class="article-title">
                {{- .context.Title -}}
            </h2>
        </div>
    </a>
</article>
```

**Comment by QIN2DIM** [comment]
emmm，我选择换张图- -构图强迫症...原本垂直尺寸的图被框到水平固定的样式卡片里，即使不放大，直接留白看着也挺难受的。毕竟需求导向233，能简单处理就不搞复杂了。
