### ISSUE TITLE
About image resizing time

### ISSUE THREAD

**Issue by ress997** [CaiJimmy/hugo-theme-stack#37]
**Is your feature request related to a problem? Please describe.**
If you have a lot of thumbnails in Hugo, it will take a long time to resize them.

I used [tcardgen](https://github.com/Ladicle/tcardgen) to create a thumbnail image based on the article data.
However, it takes a lot of time to do everything from automatic thumbnail generation to resizing in CI.
So I thought that I could solve this problem by using an existing service.

**Describe the solution you'd like**
- cloudinary
    - https://cloudinary.com/cookbook/resize_an_image

Free and easy to use!!

**Describe alternatives you've considered**
- https://support.cloudflare.com/hc/en-us/articles/360028146432-Understanding-Cloudflare-Image-Resizing
- https://www.imgix.com/
- https://www.sakura.ad.jp/services/imageflux/
- https://imageresizer.io/

**Comment by CaiJimmy** [comment]
Hi,

> If you have a lot of thumbnails in Hugo, it will take a long time to resize them.

**You should not regenerate them on every build**. According to Hugo official doc:

> Processed images are stored below <project-dir>/resources (can be set with resourceDir config setting). This folder is deliberately placed in the project, as **it is recommended to check these into source control as part of the project.** These images are not “Hugo fast” to generate, but once generated they can be reused.

You should add `resources` folder to source control. In case that you are using Netlify to build site, I recommend this plugin: [cdeleeuwe/netlify-plugin-hugo-cache-resources](https://github.com/cdeleeuwe/netlify-plugin-hugo-cache-resources)

-------

Adding support to third-party image processing services like Cloudinary would require a major code refactoring. In that case, I would make an extensible API to support more providers. Unfortunately, I do not have time to do that now 😓.

**Comment by ress997** [comment]
> You should not regenerate them on every build.

I'm working on a build that includes `resources`.
However, when the article titles and tag information were updated, CI updated the image data.
So I wanted to improve it because it takes a long time to process the images when the article is significantly updated.

>  In case that you are using Netlify to build site, I recommend this plugin: cdeleeuwe/netlify-plugin-hugo-cache-resources

I think Netlify is a very good service.
But the access time from Japan is slower than GitHub Pages and I wanted to take advantage of GitHub Actions, so I was considering other methods.

---
> Adding support to third-party image processing services like Cloudinary would require a major code refactoring. In that case, I would make an extensible API to support more providers. Unfortunately, I do not have time to do that now 😓.

I found out from the source code that `layouts/partials/helper/image.html` is used for image-related processing.

However, I thought about the need for API design before sending a pull request, so I consulted with them first.

**Comment by CaiJimmy** [comment]
> I found out from the source code that layouts/partials/helper/image.html is used for image-related processing.

Not exactly. `helper/image` is used to determine if a page has featured image. Image processing is done using Hugo's API, and only if it's a local image.

**Comment by CaiJimmy** [comment]
As an update to this issue, I just created a new PR #83, adding two new configuration fields to disable image processing. 

The support for third-party providers requires more refactoring work, and I don't think it will come / in short term.
