### ISSUE TITLE
Error when deploying using Netlify

### ISSUE THREAD

**Issue by rsicarelli** [CaiJimmy/hugo-theme-stack#38]
**Describe the bug**
I'm trying to deploy my website using Netlify but I'm getting an error:

```
Error: "/opt/build/repo/themes/hugo-theme-stack/layouts/partials/article/components/details.html:8:1": parse failed: template: partials/article/components/details.html:8: illegal number syntax: "-"
```

**To Reproduce**
1. Create a new project using Netlify
2. Follow the instructions on the screen to set up the project on GitHub
3. Start to "Deploy your site"
4. See error happening in the logs

**Expected behavior**
The website should not be prevented from deploying due to syntax errors

**Screenshots**
![image](https://user-images.githubusercontent.com/3150335/96109109-9d542c80-0ede-11eb-8a12-5a5c1f2a334b.png)

**Comment by CaiJimmy** [comment]
Hi,

This theme's example site is [built using Netlify](https://app.netlify.com/sites/hugo-theme-stack/deploys/). No error is found on the latest build. 

Can you please try re-download the theme? Or build the site using the example site's content.

**Comment by rsicarelli** [comment]
@CaiJimmy 

I actually needed to change Hugo Version on Netlify console 🤦 . 

All good, thanks!
