### ISSUE TITLE
hugo -t 报错

### ISSUE THREAD

**Issue by JameyWoo** [CaiJimmy/hugo-theme-stack#383]
执行 hugo -t hugo-theme-stack 就报错，其他主题可以用就是这个主题用不了这是为啥

➜ hugo -t hugo-theme-stack
Start building sites …
hugo v0.88.1-5BC54738+extended windows/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
ERROR 2021/10/08 19:01:30 render of "taxonomy" failed: execute of template failed: template: _default/list.html:4:12: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "E:\zen\stack\themes\hugo-theme-stack\layouts\partials\helper\image.html:31:31": execute of template failed: template: partials/helper/image.html:31:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
ERROR 2021/10/08 19:01:30 render of "taxonomy" failed: execute of template failed: template: _default/list.html:4:12: executing "_default/list.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "E:\zen\stack\themes\hugo-theme-stack\layouts\partials\helper\image.html:31:31": execute of template failed: template: partials/helper/image.html:31:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:4:12: executing "index.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:14:4: executing "partials/head/head.html" at <partial "head/opengraph/include.html" .>: error calling partial: execute of template failed: template: partials/head/opengraph/include.html:1:3: executing "partials/head/opengraph/include.html" at <partial "head/opengraph/provider/base" .>: error calling partial: execute of template failed: template: partials/head/opengraph/provider/base.html:40:13: executing "partials/head/opengraph/provider/base.html" at <partialCached "helper/image" (dict "Context" . "Type" "opengraph") .RelPermalink "opengraph">: error calling partialCached: "E:\zen\stack\themes\hugo-theme-stack\layouts\partials\helper\image.html:31:31": execute of template failed: template: partials/helper/image.html:31:31: executing "partials/helper/image.html" at <index .Context.Site.Params.defaultImage .Type>: error calling index: index of untyped nil
Total in 337 ms

**Comment by CaiJimmy** [comment]
请把 `exampleSite/config.yaml` 复制到站点根目录，并删除 `config.toml`

**Comment by JameyWoo** [comment]
原来是要删除 config.toml，解决了，感谢
