### ISSUE TITLE
"Home" button opens new tabs (in Chrome)

### ISSUE THREAD

**Issue by cassondradale** [CaiJimmy/hugo-theme-stack#392]
## Describe the bug
Issue when clicking "Home" opens the site up in another tab. 

## Expected behavior
Expect when "Home" is clicked (regardless of whether you are currently on the "Home" page), the page refreshes or goes to the "Home" page without another tab of the site opening.

## To Reproduce
Click on the "Home" button on the left-hand sidebar on any page (using Chrome).

## Environment

- **Hugo version**  0.80.1
- **Hugo extended?**: Yes

If it's a UI issue, fill the following information:

 - Browser [e.g. chrome, safari] **Chrome**

## Link to the demo site and/or source repository
demo.stack.jimmycai.com

**Comment by zhixuan2333** [comment]
https://github.com/CaiJimmy/hugo-theme-stack/blob/d8c9468c685f38476b241f82130a6ae59e28ad05/exampleSite/config.yaml#L171-L180

set `newTab` to false
