### ISSUE TITLE
How to change the tag background?

### ISSUE THREAD

**Issue by YPatrickW** [CaiJimmy/hugo-theme-stack#397]
It is quite weird for my Tags shown on the card, no background color,  how can i fix this?
Thanks

**Comment by CaiJimmy** [comment]
**Tag** (shown at article footer) does not support custom badge background.

**Categories** (shown at article header) do support custom backgrounds. For example:
https://github.com/CaiJimmy/hugo-theme-stack/blob/master/exampleSite/content/categories/Test/_index.md
