### ISSUE TITLE
提一点小建议

### ISSUE THREAD

**Issue by seth-shi** [CaiJimmy/hugo-theme-stack#399]
左边头像最后点击能进到首页(适合浏览的时候返回首页)
右边的侧边栏挨着内容区. 最后有一点边距. 现在都是自己覆盖模板实现, 

还是希望官方能关注这两个小细节. thx

**Comment by zhixuan2333** [comment]
> 左边头像最后点击能进到首页(适合浏览的时候返回首页)

https://github.com/CaiJimmy/hugo-theme-stack/discussions/373#discussioncomment-1414855

> 右边的侧边栏挨着内容区. 最后有一点边距. 现在都是自己覆盖模板实现,

#320
