### ISSUE TITLE
Fail to Build on Netlify

### ISSUE THREAD

**Issue by RenaudDev** [CaiJimmy/hugo-theme-stack#40]
**Describe the bug**
Unable to build on netlify

**To Reproduce**
Hi, I simply created a hugo site using your theme as a submodule. I copied the Examplesite documents to the main folder, pushed to github ask Netlify to build it for me. 

The error seems to come from one of your partial: 
Error: "/opt/build/repo/themes/hugo-theme-stack/layouts/partials/article/components/details.html:8:1": parse failed: template: partials/article/components/details.html:8: illegal number syntax: "-"

**Expected behavior**
Having a site ready to go

**Additional context**
Log file from Netlify:
9:50:38 AM: ┌───────────────────────────────────┐
9:50:38 AM: │ 1. Build command from Netlify app │
9:50:38 AM: └───────────────────────────────────┘
9:50:38 AM: ​
9:50:38 AM: $ hugo
9:50:39 AM: Error: "/opt/build/repo/themes/hugo-theme-stack/layouts/partials/article/components/details.html:8:1": parse failed: template: partials/article/components/details.html:8: illegal number syntax: "-"
9:50:39 AM: ​
9:50:39 AM: ┌─────────────────────────────┐
9:50:39 AM: │   "build.command" failed    │
9:50:39 AM: └─────────────────────────────┘

**Comment by CaiJimmy** [comment]
Hi,

You need to change Hugo version on Netlify console.

Related: https://github.com/CaiJimmy/hugo-theme-stack/issues/38

**Comment by RenaudDev** [comment]
Thanks for the prompt reply. How about adding a netlify.toml to the theme?
```
[context.production.environment]
  HUGO_VERSION = "0.76.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
```

**Comment by CaiJimmy** [comment]
I'll add this on the next release documentation. 👌
