### ISSUE TITLE
Image href

### ISSUE THREAD

**Issue by zhixuan2333** [CaiJimmy/hugo-theme-stack#410]
## Describe the bug

Photos can‘t be hyperlinked

## To Reproduce
```md
[![Google](https://www.google.com/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png)](https://google.com)
```
It's will give me

```html
<figure>
    <a class="link" href="https://google.com" target="_blank" rel="noopener"></a>
    <a href="https://www.google.com/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png">
        <img src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png" loading="lazy" alt="Google">
    </a>
    <figcaption>Google</figcaption>
</figure>
```

## Expected behavior
[![Google](https://www.google.com/images/branding/googlelogo/1x/googlelogo_light_color_272x92dp.png)](https://google.com)

## Environment

hugo v0.87.0-B0C541E4+extended windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio

## Additional context
 - OS: windows10
 - Browser chrome
 - Version 95.0.4638.69
 - theme: Newest

**Comment by dag7dev** [comment]
Up. This is very important!

**Comment by qinyuanpei** [comment]
I try to fix this issue by `replace`:
```
{{- $Permalink := replace $Permalink "/http:/" "http://" 1 -}}
{{- $Permalink := replace $Permalink "/https:/" "https://" 1 -}}
```

It is not a elegant way, but it works. 😄

**Comment by dag7dev** [comment]
Thanks by hearth!
How to use it now?

**Comment by CaiJimmy** [comment]
Should work just with normal markdown syntax.

**Comment by dag7dev** [comment]
> Should work just with normal markdown syntax.

awesome, thanks for having fixed this, it was really important
