### ISSUE TITLE
请问如何修改右侧区域在全局的占比？

### ISSUE THREAD

**Issue by guowei-gong** [CaiJimmy/hugo-theme-stack#419]
**Is your feature request related to a problem? Please describe.**
我没有找到修改右侧全局占比的配置

**Describe the solution you'd like**
我希望右侧区域能够更窄一点，这样中间区域看起来是对称的

**Describe alternatives you've considered**
暂无

**Additional context**
如下图，我希望红色区域能够缩小到绿色区域，同时中间区域的文章目录会更宽一点。
![image](https://user-images.githubusercontent.com/62499904/142345075-df63f2c6-2789-4397-8733-70bcedc6498b.png)

**Comment by zhixuan2333** [comment]
https://github.com/CaiJimmy/hugo-theme-stack/blob/41fa65cbf5c43301c56b74a7cb2a8bb2edc54f1e/assets/scss/grid.scss#L18-L36

修改 --left-sidebar-max-width 和 --right-sidebar-max-width

**Comment by guowei-gong** [comment]
> https://github.com/CaiJimmy/hugo-theme-stack/blob/41fa65cbf5c43301c56b74a7cb2a8bb2edc54f1e/assets/scss/grid.scss#L18-L36
> 
> 修改 --left-sidebar-max-width 和 --right-sidebar-max-width

修改 33 行代码和 34 行代码对我来说是有用的，谢谢！
