### ISSUE TITLE
使用 twikoo 评论插件，每一篇文章下的评论都是一样的 

### ISSUE THREAD

**Issue by guowei-gong** [CaiJimmy/hugo-theme-stack#420]
🍻 我已经阅读了主题文档。

## Describe the bug
我仅评论了一篇文章，但是所有文章下的评论列表都出现了这条评论。

## Expected behavior
每一篇文章下，都应该是独一无二的评论。

## To Reproduce
按照主题文档配置 twikoo 所需参数

## Screenshots。
![image](https://user-images.githubusercontent.com/62499904/142407327-f0e3b7cf-7610-43ca-9659-d2ef061351b7.png)

![image](https://user-images.githubusercontent.com/62499904/142407786-5f8d7f73-6cd0-4b70-afb0-e5d301ec835d.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: hugo v0.87.0+extended darwin/amd64 BuildDate=unknown
- **Hugo extended?**: No

谢谢。

**Comment by zhixuan2333** [comment]
这是个Bug,
`twikoo.path` 设置为 `window.location.pathname`

**Comment by zhixuan2333** [comment]
要`.path`值留空

**Comment by guowei-gong** [comment]
> 要`twikoo.path`值留空

`twikoo.path` 留空，这解决了我的问题，谢谢~
