### ISSUE TITLE
How to enable disqus

### ISSUE THREAD

**Issue by fpt-mnes-namnt54** [CaiJimmy/hugo-theme-stack#427]
Hi,

I changed disqusShortname in config.yaml file but it seem did not work

![image](https://user-images.githubusercontent.com/77031360/145174349-463211b1-dee9-46f6-b591-e2510610b682.png)

**Comment by zhixuan2333** [comment]
Are you set trusted domain? If not please see https://help.disqus.com/en/articles/1717301-i-m-receiving-the-message-we-were-unable-to-load-disqus.
