### ISSUE TITLE
Comments showing on pages but not on posts

### ISSUE THREAD

**Issue by corridordigital** [CaiJimmy/hugo-theme-stack#429]
Hey everyone ! 
I enabled the comments with utterances through my config.yaml file, and they show up on all pages, but not on blog posts ! 
do you know why ? 

I use `comments: yes` for my articles

About my env: 
* HUGO_VERSION = "0.85.0"
* Theme version: July 2021

[Example site](https://anaselk.com/)

**Comment by zhixuan2333** [comment]
It's `comment: true` to enable comment. And if possible please update your theme version (Your theme version is v2.5.0).

<details>
  <summary>More Info</summary>
v2.5.0

https://github.com/CaiJimmy/hugo-theme-stack/blob/1fa573dae3f2bc7d959ef659129ec88eff400441/layouts/_default/single.html#L20-L22
v3.5.0

https://github.com/CaiJimmy/hugo-theme-stack/blob/d04b3a8771386c9988be00adda53f0bf542cf269/layouts/_default/single.html#L20-L22
</details>

**Comment by CaiJimmy** [comment]
Close this for now.
