### ISSUE TITLE
升级主题后样式不正确 the css style is not norml as the theme demo shows 

### ISSUE THREAD

**Issue by kzq666666** [CaiJimmy/hugo-theme-stack#432]
升级主题后样式不正确，如主题文档所说，我删除了站点的resources文件使用hugo生成之后css还是不对。
the style of the page is not noram as the demo shows, I did the job `delete the base site's resources fold & use the hugo to generate the resources fold`. But the style is still not ok.

hugo version：hugo v0.90.1-48907889+extended windows/amd64 BuildDate=2021-12-10T10:56:41Z VendorInfo=gohugoio
![微信截图_20211215113556](https://user-images.githubusercontent.com/36102279/146118557-5a53aba0-746b-457e-a68b-87d940dc12b2.png)

**Comment by zhixuan2333** [comment]
删除`assets`里的除了自己自定义的所有文件

**Comment by kzq666666** [comment]
Thanks，it does work.
