### ISSUE TITLE
请教一个图片不正常显示的问题

### ISSUE THREAD

**Issue by kochonohate** [CaiJimmy/hugo-theme-stack#433]
图片在本地显示正常，但上传到github后由于部分图片名称以空格开头导致无法显示，请问能使其生成名称不含空格的文件或有其他解决办法吗，谢谢大佬们

hugo v0.90.1-48907889+extended windows/amd64 BuildDate=2021-12-10T10:56:41Z VendorInfo=gohugoio

**Comment by zhixuan2333** [comment]
应该是`_`下横线吧？
https://github.com/CaiJimmy/hugo-theme-stack/issues/198#issuecomment-826964724

在网站根目录里添加`.nojekyll`

**Comment by kochonohate** [comment]
感谢大佬！
