### ISSUE TITLE
Feature Request: Support the syntax highlight for `diff` in light mode

### ISSUE THREAD

**Issue by lomirus** [CaiJimmy/hugo-theme-stack#434]
**Is your feature request related to a problem? Please describe.**
I am writing my blog with such markdown codes:
<pre>
```diff
[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev = "11f52b8c72fc3a568e8bb4a4cd1f3eb025ac2e13"
- features = ["dynamic"]
+ features = ["jpeg", "dynamic"]
```
</pre>

and it displays like this: 

![](https://i.imgur.com/KFskB7H.png)

**Describe the solution you'd like**
What I wanted is like this:
```diff
[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
rev = "11f52b8c72fc3a568e8bb4a4cd1f3eb025ac2e13"
- features = ["dynamic"]
+ features = ["jpeg", "dynamic"]
```
It should have a highlighted syntax

**Describe alternatives you've considered**
Not yet

Edit:
Hugo version: `hugo v0.89.4+extended linux/amd64 BuildDate=unknown`
Theme version: v3.5.0

**Comment by zhixuan2333** [comment]
It works in my environment. Update your hugo

<img width="575" alt="image" src="https://user-images.githubusercontent.com/59254886/146668320-da5fb4d3-18f0-4416-b424-6912ba29641b.png">

**Comment by lomirus** [comment]
> It works in my environment. Update your hugo
> 
> <img alt="image" width="575" src="https://user-images.githubusercontent.com/59254886/146668320-da5fb4d3-18f0-4416-b424-6912ba29641b.png">
I just checked my hugo version and it should be the latest: `hugo v0.89.4+extended linux/amd64 BuildDate=unknown`

**Comment by lomirus** [comment]
@zhixuan2333 Now I understand why it works on your environment but not mine. I tried again in dark mode and it worked well, but in light mode it did not work as expected,  like the image of this issue showing.
