### ISSUE TITLE
一些文章内容显示细节

### ISSUE THREAD

**Issue by linsn0w** [CaiJimmy/hugo-theme-stack#441]
如何给插入的图片添加阴影和圆角，文档里貌似没有这个变量名称

**Comment by CaiJimmy** [comment]
没有相应的变量，需要自己修改源文件，给 `.article-content img` 添加样式。
Ref: https://github.com/CaiJimmy/hugo-theme-stack/blob/master/assets/scss/partials/layout/article.scss#L273
