### ISSUE TITLE
相關文章區塊圖片無法讀取

### ISSUE THREAD

**Issue by bacnotes** [CaiJimmy/hugo-theme-stack#442]
## Describe the bug
您好，很喜歡您寫的Hugo主題。使用上有一個小地方想請教一下
在本地端localhost:1313，可以在文章頁面左下方看到相關主題區塊圖片有成功讀取
<a href="https://ibb.co/X3PwLpc"><img src="https://i.ibb.co/7RD9CVs/2021-12-26-4-51-22.png" alt="2021-12-26-4-51-22" border="0"></a>

但上線後，左下方圖片沒有成功讀取到
<a href="https://ibb.co/z7hhH8F"><img src="https://i.ibb.co/KLjjzND/2021-12-26-4-50-22.png" alt="2021-12-26-4-50-22" border="0"></a>

檢查了部署的資料夾結構跟本地的資料夾結構是一樣的，沒有特別更改過
封面圖跟其他尺寸的圖片都讀取順利，只有相關文章區塊的圖片讀取不到
想了一段時間還是無解，因此上來詢問，謝謝您。

附上相關檔案的[GitHub連結](https://github.com/bacnotes/bacnotes.github.io/tree/main/p/github-ssh-key)
以及[網站連結](https://bacnotes.github.io/p/github-ssh-key/)

**Comment by zhixuan2333** [comment]
https://github.com/CaiJimmy/hugo-theme-stack/issues/198#issuecomment-826964724

在网站根目录里添加`.nojekyll`

**Comment by bacnotes** [comment]
成功了！謝謝！非常感激🥺
