### ISSUE TITLE
The example site is down

### ISSUE THREAD

**Issue by nk9** [CaiJimmy/hugo-theme-stack#449]
When I navigate to the [example site](https://theme-stack.jimmycai.com) linked from the README, I get a 404.

**Comment by zhixuan2333** [comment]
https://demo.stack.jimmycai.com/

**Comment by nk9** [comment]
Thanks. Looks like the README needs to be updated.

**Comment by CaiJimmy** [comment]
Yeah, thanks for pointing it out. I was removing unused DNS records a few days ago and thought that I had replaced already all links.

**Comment by nk9** [comment]
Looks fixed now, thanks!
