### ISSUE TITLE
SCSS Variables Doesn't Apply to The Pages

### ISSUE THREAD

**Issue by Futrime** [CaiJimmy/hugo-theme-stack#45]
**Describe the bug**
Though having edited `/themes/hugo-theme-stack/assets/scss/variables.scss`, nothing changed in `/public`.

I've tried `hugo --forceSyncStatic` but only `/resource` changed and still nothing happend in `public`.

When running `hugo --ignoreCache`, it returned `Error: Error building site: TOCSS: failed to transform "scss/style.scss" (text/x-scss): resource "scss/scss/style.scss_b95b077eb505d5c0aff8055eaced30ad" not found in file cache` .

By the way, I have already tick the `disable cache` option in dev tools in Firefox and cleaned the whole browser cache for times.

**To Reproduce**
1. Modify `--body-text-color` in `/themes/hugo-theme-stack/assets/scss/variables.scss`
2. Run `hugo` at repo root

**Expected behavior**
The color of text should be changed.

**Screenshots**
![1](https://user-images.githubusercontent.com/35801754/97801551-894b5180-1c78-11eb-8f1f-08321b48d02c.png)
![2](https://user-images.githubusercontent.com/35801754/97801552-8b151500-1c78-11eb-9891-2d8ed7221f4f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 83

**Comment by CaiJimmy** [comment]
Use Hugo Extended if you want to edit SCSS files

https://github.com/CaiJimmy/hugo-theme-stack/blob/master/README.md#requirements

**Comment by Futrime** [comment]
Thanks a lot. The problem has been solved.
