### ISSUE TITLE
The fist-level title is ignored  in table of contents

### ISSUE THREAD

**Issue by ichenhe** [CaiJimmy/hugo-theme-stack#454]
## Describe the bug

The fist-level title is ignored  in table of contents. Only second+ level title will be recongnizd.

## Expected behavior

The  fist-level title should also be recongnizd.

If it is an intent behavior to adapt to the usecase that use first-level title as article's headline, I think we should check if there are more than one fist-level title. If it is true, it should be regarded as part of the directory.

## To Reproduce

Add a post:

```md
# Head 1

## sub1
aaa

# Head 2

## sub2

bbb
```

## Screenshots

![](https://user-images.githubusercontent.com/10266066/148227898-7aca0362-9c7a-4480-9d41-688a78a7c601.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.91.0
- **Hugo extended?**: Yes 

## Additional context

If it's a UI issue, fill the following information:

 - OS: mac
 - Browser: vivaldi (chromium)
 - Version: 5.0.2497.32

**Comment by rmdhnreza** [comment]
You can change it from `config.yaml`
https://github.com/CaiJimmy/hugo-theme-stack/blob/86cbc1b682c999f62708bb3aea82615e862c7f95/exampleSite/config.yaml#L211-#L214

**Comment by ichenhe** [comment]
@rmdhnreza Thank you.

It would be better if this could be written in the document.
