### ISSUE TITLE
怎么联系你？

### ISSUE THREAD

**Issue by iuvhub** [CaiJimmy/hugo-theme-stack#471]
## To Reproduce
Indicate the steps to reproduce this bug, if applicable.

## Screenshots
Add screenshots to help explain your problem.

## Environment

- **Hugo version** [e.g: 0.80.0]: 
- **Hugo extended?**: Yes / No

## Additional context

If it's a UI issue, fill the following information:

## Content of config.yaml
```yaml
### Paste the content of the config file here
```

**Comment by CaiJimmy** [comment]
主题相关的问题请直接使用 GitHub Issues / Discussions。其他事情可以发邮件，邮箱地址在 https://github.com/CaiJimmy
