### ISSUE TITLE
Disqus color theme cannot change with blog dark mode on Windows

### ISSUE THREAD

**Issue by Whotakesmyname** [CaiJimmy/hugo-theme-stack#474]
## Describe the bug
Disqus color theme stays light even if blog turns on dark mode on Windows

## Expected behavior
Disqus sets color theme to auto. When blog turns off dark mode, disqus theme should be light; when blog turns on dark mode, disqus theme should be dark automatically.

## To Reproduce
On Windows, open demo site and turns on dark mode. Click the first post and see the disqus module at the bottom, it is in light theme.

## Screenshots
![image](https://user-images.githubusercontent.com/19500528/151492334-9933d7a6-643c-4c3d-859b-cb5b9ea35a00.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.92.0
- **Hugo extended?**: Yes

## Additional context
This problem seems to only occur in Chrome related browsers. Tested in Chrome and Edge on Windows, and Chrome and Samsung Browser on Android.

However, on MacOS and iOS (iPad OS), this problem does not occur in Safari, but does occur in Chrome.

If it's a UI issue, fill the following information:

 - OS: Windows, Android, MacOS
 - Browser: chrome and edge
 - Version: Chrome 97.0.4692.99 on Windows 10 platform

## Content of config.yaml
```yaml
### Paste the content of the config file here
```
Since the [demo site](https://demo.stack.jimmycai.com/) provided by this repo can also demonstrate this problem, the config file is not provided.

## Link to the demo site and/or source repository
[https://demo.stack.jimmycai.com/](https://demo.stack.jimmycai.com/)

Or, you can see the same result on my site [https://blog.darkray.cn/](https://blog.darkray.cn/). Source repo [here](https://github.com/Whotakesmyname/darkray-blog)

**Comment by Whotakesmyname** [comment]
When I look at it again, in blog's dark mode, the disqus iframe seems not just in light theme, either. It looks like in a broken color style.

**Comment by Whotakesmyname** [comment]
This might not be a problem of this theme. Since I am not any browser UI pro, I will leave it here. If anyone find it resulted from Disqus instead of this theme, feel free to close it.

**Comment by Whotakesmyname** [comment]
This is proved to be a wicked problem involving some w3c specs conformation topics. See [this question](https://stackoverflow.com/questions/65260505/disqus-iframe-transparency-wont-work-on-chrome-87) and the links mentioned in the answers for more details.

The workaround mentioned by the two answers works. To be specific, add a snippet in the head partial html file like below:
```html
<!-- fix disqus dark mode transparency bug -->
<style>
  :root {
    color-scheme: light dark;
  }

  iframe {
    color-scheme: light dark;
  }
</style>
```

Since this is proved not to be something this theme should be responsible for, this issue can be closed. But now, the disqus iframe in the demo site in dark mode looks so ugly, I think maybe we can incorporate this fix into this theme. If you do not agree with this idea, feel free to close it.

**Comment by CaiJimmy** [comment]
Should be fixed now, thanks!
