### ISSUE TITLE
Support for sub-sub-folders

### ISSUE THREAD

**Issue by iranvir** [CaiJimmy/hugo-theme-stack#48]
**Is your feature request related to a problem? Please describe.**
**Describe the bug**
The following is what I tried:
1. Create a `contents/notes/` folder, within which there is another folder `content/notes/alpine`
2. All the contents of `content/notes/alpine` show up in `example.com/notes/`

**Describe the solution you'd like**
I would prefer if,
1. I can create an `_index.md` in `content/notes/alpine` and add a title and description of that sub-subfolder 
2. `example.com/notes` show a list of cards for every subfolder within it.

Please let me know if that makes sense, and if that is aligned with your design goals for this project. If not, I can always use tags and categories.
Thanks for a beautiful theme. :)

**Comment by CaiJimmy** [comment]
> All the contents of content/notes/alpine show up in example.com/notes/

I'm not sure if this is something achievable by a Hugo theme. Currently, this theme uses `{{ range .Paginator.Pages }}` to display all contents under a section:

https://github.com/CaiJimmy/hugo-theme-stack/blob/2a0d06190b83c91989e7bf8ba952ef72e05c2c44/layouts/_default/list.html#L7

But it does not return child section's content.

It's possible to display content of each child section. However, the solution I have in mind will display first all contents under child section 1, then child section 2.... And paginator will stop working too.

**Comment by CaiJimmy** [comment]
Reading again this issue, I think that I had misunderstood the feature request.

**Technically I think it's possible.** But I don't have in mind how to design this. Or if this is something that this theme should have.

**Comment by iranvir** [comment]
@CaiJimmy Thanks for considering it anyways.
If you want, you can look at the hugo-casper3 theme, it supports that feature and it is a dead simple theme. I ported my site to it, where I use this "nested docs" feature. I can share my source as well, if you want to get the gist of it.  :)

**Comment by CaiJimmy** [comment]
Thanks 😀, I think I got it. Something like this:

![image](https://user-images.githubusercontent.com/5889006/102924225-717e9580-4491-11eb-9366-4bd45a92f011.png)

**Comment by iranvir** [comment]
@CaiJimmy Thanks a bunch!!
