### ISSUE TITLE
Frontmatter image credit and/or caption

### ISSUE THREAD

**Issue by casimiroarruda** [CaiJimmy/hugo-theme-stack#480]
**Is your feature request related to a problem? Please describe.**
I usually use images from unsplash and I would like to give a shoutout to creator

**Describe the solution you'd like**
A new optional field at frontmatter, like `image-caption` or `image-credit` and its value rendered nicely below post image, with rendering of any markdown (eg. links)

**Describe alternatives you've considered**
I think it's simple enough to alternatives. This could be used also to describe the image for the matters of a18y

**Additional context**
![image](https://user-images.githubusercontent.com/318222/151992820-1a390323-2d74-4a4b-96d9-8a72512e50a5.png)
Linkedin has something similar on its blogging engine. The label there is "Add credit and caption"

**Comment by CaiJimmy** [comment]
No plan to add this currently, sorry!
