### ISSUE TITLE
toc rendering issue when title comes with link

### ISSUE THREAD

**Issue by Ayx03** [CaiJimmy/hugo-theme-stack#495]
## Describe the bug
One title used multiple numbers in toc when the title come with a link.

I've tried deleting /resources and /public but those didn't work.

## Expected behavior
Just like there's no link in titles.

## To Reproduce
Add links in title.

## Screenshots
![](https://user-images.githubusercontent.com/75155322/153719102-224a1df0-c7c8-4b5f-bdc7-62859f06bd41.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: 0.91.2
- **Hugo extended?**: Yes

 - OS: [e.g. iOS] WIndows 11
 - Browser [e.g. chrome, safari] Firefox/Edge
 - Version [e.g. 22] 97/98

## Link to the demo site and/or source repository
<https://ayx.moefox.tech/test>

**Comment by CaiJimmy** [comment]
![image](https://user-images.githubusercontent.com/5889006/153723977-8940f9cb-16da-4404-9b24-a1c5fcee0b18.png)

I think this issue is related to Hugo's TOC function. It generates an invalid HTML construction (nested hyperlink), and the browser (like Chrome) will break it in two.

![image](https://user-images.githubusercontent.com/5889006/153724042-3538069b-140a-40c8-bae2-002138e56324.png)

**Comment by Ayx03** [comment]
I'll try the previous version of hugo today to see if there's some change in hugo caused this, thank you!

**Comment by Ayx03** [comment]
@CaiJimmy The issue doesn't exist using [release v3.7.0](https://github.com/CaiJimmy/hugo-theme-stack/releases/tag/v3.7.0)
![Snipaste_2022-02-14_18-39-16](https://user-images.githubusercontent.com/75155322/153848595-1b04de2b-946f-4a39-9360-cec3fcdd3448.png)

**Comment by nk9** [comment]
I'm using 3.11 and I'm seeing the link taken and used directly in the in-page TOC. In cases where the entire header is a link, this makes it impossible to jump to that section. Instead, clicking the link sends the user to the original link href.

Is this the same issue, or a diffent one? I kind of thought the links used to be stripped, but I don't remember exactly.

<img width="1290" alt="Screenshot 2022-04-24 at 18 11 29" src="https://user-images.githubusercontent.com/3646730/164988158-3cdc2f47-4b85-4c01-8547-4836236ee5e7.png">

**Comment by CaiJimmy** [comment]
Yes, it's the same issue and should be related to the new TOC introduced in v3.8.0. Unfortunately, I don't have time to investigate it until June.

**Comment by cubercsl** [comment]
#589 #601
