### ISSUE TITLE
Can avatar support external url?

### ISSUE THREAD

**Issue by imba-tjd** [CaiJimmy/hugo-theme-stack#50]
I'd like to use `https://avatars3.githubusercontent.com/u/xxx` as my avatar so that it's the same as github's avatar. Is it possible? I know little about go and hugo.

**Comment by CaiJimmy** [comment]
It's not yet possible. But you can edit the source code:

https://github.com/CaiJimmy/hugo-theme-stack/blob/6b5e84011131eeead8a82a309178cad5212f631e/layouts/partials/sidebar/left.html#L11-L19

Replace it with:

```html
<img src="external link" class="site-logo" loading="lazy" alt="Avatar">
```
