### ISSUE TITLE
请求添加 .conf 代码块高亮渲染

### ISSUE THREAD

**Issue by nibazshab** [CaiJimmy/hugo-theme-stack#500]
当我写下.conf的代码块的时候，高亮渲染不工作

当我写下：
```
$  ```conf
$  # 文件保存目录
$  dir=${HOME}
$
$  # 从会话文件中读取下载任务
$  input-file=aria2.session
$  # 在Aria2退出时保存错误的、未完成的下载任务到会话文件
$  save-session=aria2.session
$  # 定时保存会话, 0为退出时才保存, 需1.16.1以上版本, 默认:0
$  save-session-interval=60
$  ```
```
我得到：
![image](https://user-images.githubusercontent.com/44338441/154471020-82ed8e3e-84d9-42c0-8e26-43b20c4597ea.png)

我希望能添加对 conf 的代码块高亮支持

**Comment by nibazshab** [comment]
> 

阿哲，好像确实是没有

依稀记得以前用 hexo 的时候好像是有高亮的，这么看来可能是作者专门搞的

**Comment by zhixuan2333** [comment]
![](https://user-images.githubusercontent.com/59254886/154474264-d54adeff-1195-481c-89f9-122590624752.png)

How about use `ini`?
