### ISSUE TITLE
图片懒加载

### ISSUE THREAD

**Issue by lin-snow** [CaiJimmy/hugo-theme-stack#501]
图片好像没有懒加载
，在刚打开博客时一些地方显示不出图片或者卡住

https://blog.linsnow.cn/

使用的是最新版的extend版本

**Comment by CaiJimmy** [comment]
无法复现，示例站点的图片并没有加载问题。主题自带的图片懒加载是浏览器功能，不是用 JavaScript 实现的。如果图片加载不出来和主题没什么关系。

Can't reproduce. Lazyload is working properly on the demo site. This theme's lazyload feature is implemented using the `loading` attribute from HTML5 and not a JavaScript function. In case the image isn't loading, you should check your browser & image href.
