### ISSUE TITLE
FaTex对矩阵的支持

### ISSUE THREAD

**Issue by BacteriumFox** [CaiJimmy/hugo-theme-stack#506]
#![image](https://user-images.githubusercontent.com/52241355/155844868-7c871a39-cfcd-4534-87d3-89f6582ac84e.png)
![image](https://user-images.githubusercontent.com/52241355/155844995-3655aa91-8e18-450b-ab17-660921a92e88.png)
左边为博客显示的矩阵，右边为用Typora显示的矩阵。博客中无法正确的渲染矩阵函数，但其他的FaTeX函数显示正常
如果是因为我没有使用正确的矩阵函数，请告知我正确的举证函数使用方法。谢谢！

**Comment by CaiJimmy** [comment]
```
$$
\begin{pmatrix}
   a & b \\\\
   c & d
\end{pmatrix}
$$
```

![image](https://user-images.githubusercontent.com/5889006/155860378-134ff062-85e0-45d5-ab07-0245ea06dbde.png)

Use 4 backslashes in Markdown.
