### ISSUE TITLE
Idea: migrate configuration file to TOML

### ISSUE THREAD

**Issue by CaiJimmy** [CaiJimmy/hugo-theme-stack#510]
YAML was easy to use and maintain at the beginning of this project. Now that it has so many available options (especially for comment providers), it has become a horror to write (indentation).

Might consider switching back to TOML again.

**Comment by fariszr** [comment]
I think YAML is more popular. And with IDEs like VS Code, it makes indentation way easier with add-ons like indentation rainbow.
