### ISSUE TITLE
Layout different if no widgets

### ISSUE THREAD

**Issue by nella17** [CaiJimmy/hugo-theme-stack#513]
## Describe the bug
If article doesn't have widgets, page layout is slight different.

## Expected behavior
Sidebar's width is fixed.

## Screenshots

![image](https://user-images.githubusercontent.com/14134195/155884515-c55e1e6c-7dfb-40f2-afea-79712fb7a640.png)
![image](https://user-images.githubusercontent.com/14134195/155884518-0981778a-b240-4cac-9845-ff010377d46d.png)

If it's a UI issue, fill the following information:

 - OS: macOS
 - Browser: Edge
 - Version: 98.0.1108.62
 - Window Width: 1420px
 - Window Height 776px

## Content of config.yaml
https://github.com/CaiJimmy/hugo-theme-stack/blob/master/exampleSite/config.yaml

## Link to the demo site and/or source repository

https://demo.stack.jimmycai.com/p/test-chinese/
https://demo.stack.jimmycai.com/about/

**Comment by CaiJimmy** [comment]
That's the expected behavior. If there's no widget the max-width will be slightly smaller.

https://github.com/CaiJimmy/hugo-theme-stack/blob/2712887c7c81b7dd0309910859b1d46252f82677/layouts/_default/baseof.html#L10

**Comment by nella17** [comment]
Ok, thanks.
