### ISSUE TITLE
Add Suggest changes button

### ISSUE THREAD

**Issue by fariszr** [CaiJimmy/hugo-theme-stack#521]
**Is your feature request related to a problem? Please describe.**
A `suggest changes` button, would be nice to have an easy link for people to update or modify articles on public git repositories.

**Describe the solution you'd like**
Add a `suggest changes` button which links to the original markdown file on a git hosting platform.

Here is how it's implemented in PaperMod
![image](https://user-images.githubusercontent.com/35614734/156671714-1d14e192-78a4-4e42-9715-1822b5fde0e8.png)

**Describe alternatives you've considered**
Linking to the markdown file in the article ?

**Additional context**
https://github.com/adityatelange/hugo-PaperMod/pull/278

**Comment by CaiJimmy** [comment]
No plan to include this in the theme. Sorry.

**Comment by fariszr** [comment]
Would you accept a PR implementing it ?

-------- Original Message --------

**Comment by CaiJimmy** [comment]
Not for now. I'd like to keep this theme simple. 
This feature depends on where the source files are hosted, and I believe it's better that users modify the template themselves.

**Comment by fariszr** [comment]
No really, its just a link pointing to the file on the git repository.
Its just a link, so it will work with github, gitlab, gitea or any other git platform.

And the author adds the link manually in the metadata section of each post.

-------- Original Message --------
