### ISSUE TITLE
turn back button ?

### ISSUE THREAD

**Issue by lin-snow** [CaiJimmy/hugo-theme-stack#528]
## Describe the bug
更新了最新版的3.9.0后移动端的返回按钮怎么没了啊，，否则每次都只能靠点头像回到首页，这很麻烦，体验大大下降

## Expected behavior
给主题添加一个返回按钮

## To Reproduce
Indicate the steps to reproduce this bug, if applicable.

## Screenshots
Add screenshots to help explain your problem.

## Environment

- **Hugo version*lastest* [e.g: 0.80.0]: 
- **Hugo extended?**: Yes

## Additional context

If it's a UI issue, fill the following information:

## Content of config.yaml
```yaml
### Paste the content of the config file here
```

**Comment by CaiJimmy** [comment]
没有打算加回来。

> 移动端的返回按钮怎么没了啊，，否则每次都只能靠点头像回到首页

系统自带的手势和返回按钮比这个更实用。

**Comment by lin-snow** [comment]
> 没有打算加回来。
> 
> 
> 
> > 移动端的返回按钮怎么没了啊，，否则每次都只能靠点头像回到首页
> 
> 
> 
> 系统自带的手势和返回按钮比这个更实用。

是否会在config yaml里增加这个选项，控制返回按钮是否开启
