### ISSUE TITLE
Search does not consider post subtitles - reproduced with the demo

### ISSUE THREAD

**Issue by RoneoOrg** [CaiJimmy/hugo-theme-stack#530]
## Describe the bug

Searching for content in [the demo](https://demo.stack.jimmycai.com/) does not take the subtitles into account

## To Reproduce

- visit the demo
- search for "Amet"

## Result

Some posts are correctly listed, but this post is not included in the search results: https://demo.stack.jimmycai.com/p/placeholder-text/

**Comment by CaiJimmy** [comment]
> Searching for content in [the demo](https://demo.stack.jimmycai.com/) does not take the subtitles into account

The subtitle is not displayed in the result hence it's not indexed, that's the expected behavior. You can modify the source code to include subtitles to index.
