### ISSUE TITLE
[Feedback] hugo-theme-stack-starter

### ISSUE THREAD

**Issue by CaiJimmy** [CaiJimmy/hugo-theme-stack#535]
[CaiJimmy/hugo-theme-stack-starter](https://github.com/CaiJimmy/hugo-theme-stack-starter)

This starter template is aimed to provide a faster and easier first-time setup experience. **If everything works well, you don't need to set up any local environment, just write the blog on the cloud (using GitHub codespaces).**

If you found any issues while using this new starter template, please leave a reply here.

**Comment by CorrectRoadH** [comment]
Hello，I have a problem that I don't know how to enable rss in `hugo-theme-stack-starter`.
I want a file,such feed.xml or rss.xml in public.
Have a approach or a option to enable it?

**Comment by CaiJimmy** [comment]
> Hello，I have a problem that I don't know how to enable rss in `hugo-theme-stack-starter`. I want a file,such feed.xml or rss.xml in public. Have a approach or a option to enable it?

@CorrectRoadH `SITE_URL/index.xml`
