### ISSUE TITLE
exampleSite shortcode error

### ISSUE THREAD

**Issue by bruce2233** [CaiJimmy/hugo-theme-stack#537]
## exampleSite shortcode error
example\content\post\rich-content\index.md在生成时报错，latout/shortcode中也并不存在twitter_simple的shortcode

**Comment by zhixuan2333** [comment]
`twitter_simple` 是 hugo 从 v0.89.0 开始自带的shortcode。是不是没升级啊？

**Comment by bruce2233** [comment]
我目前在用的是v0.93.2，可能和国内的网络有关，我已经把涉及twitter的代码删除，youtube保留不会报错，目前error已解决，多谢。
