### ISSUE TITLE
希望可以增加备案号支持

### ISSUE THREAD

**Issue by ztechstack** [CaiJimmy/hugo-theme-stack#55]
如题，谢谢！

**Comment by CaiJimmy** [comment]
你好，

请问这个需求是不是能通过**自定义页脚信息**来解决？

打算在配置文件里面添加一个 `footer.customText` 字段。

**Comment by Poliki** [comment]
您好！非常感谢精美的主题！同上问题，备案号服务商要求需要链接到工信部，配置文件里面的 footer.customText 不足以达到这个效果，想知道改哪里可以实现。再次感谢。

**Comment by CaiJimmy** [comment]
> 您好！非常感谢精美的主题！同上问题，备案号服务商要求需要链接到工信部，配置文件里面的 footer.customText 不足以达到这个效果，想知道改哪里可以实现。再次感谢。

@Poliki `footer.customText` 支持 HTML，可以自己写个 `<a>` 标签放进去

**Comment by Poliki** [comment]
> > 您好！非常感谢精美的主题！同上问题，备案号服务商要求需要链接到工信部，配置文件里面的 footer.customText 不足以达到这个效果，想知道改哪里可以实现。再次感谢。
> 
> @Poliki `footer.customText` 支持 HTML，可以自己写个 `<a>` 标签放进去

明白了！非常感谢！
