### ISSUE TITLE
Uncaught ReferenceError: DISQUS is not defined

### ISSUE THREAD

**Issue by mlzzen** [CaiJimmy/hugo-theme-stack#571]
## Describe the bug
Uncaught ReferenceError: DISQUS is not defined

## To Reproduce
Indicate the steps to reproduce this bug, if applicable.

## Screenshots
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/11664505/160369067-d565a39c-febb-41f1-b00b-586762929210.png)

## Environment

- **Hugo version** [e.g: 0.80.0]: 
- **Hugo extended?**: Yes / No

## Additional context

If it's a UI issue, fill the following information:

## Content of config.yaml
```yaml
### Paste the content of the config file here
```

**Comment by zhixuan2333** [comment]
在本地的话那是正常的

**Comment by mlzzen** [comment]
> 在本地的话那是正常的

那改成window.DISQUS 会不会改好一点？

**Comment by mlzzen** [comment]
打错字了， 那改成window.DISQUS 会不会更好一点？

**Comment by CaiJimmy** [comment]
> 打错字了， 那改成window.DISQUS 会不会更好一点？

应该可以 👍，或者使用 `if(typeof DISQUS !== 'object')` 来检查Disqus是否已经加载。

我看到你发了个 PR：https://github.com/CaiJimmy/hugo-theme-stack/pull/572
但是目前已经是关闭状态，我无法合并。如果愿意的话可以麻烦你再发一个吗？（或者我自己提交修改也行）

**Comment by mlzzen** [comment]
> > 打错字了， 那改成window.DISQUS 会不会更好一点？
> 
> 应该可以 👍，或者使用 `if(typeof DISQUS !== 'object')` 来检查Disqus是否已经加载。
> 
> 我看到你发了个 PR：#572 但是目前已经是关闭状态，我无法合并。如果愿意的话可以麻烦你再发一个吗？（或者我自己提交修改也行）

那还是麻烦你提交修改一下。
