### ISSUE TITLE
How did you implement PhotoSwipe?

### ISSUE THREAD

**Issue by Darthagnon** [CaiJimmy/hugo-theme-stack#573]
Not a feature request.

I'm currently tinkering with [Hugo Easy Gallery](https://github.com/Darthagnon/hugo-easy-gallery), a framework for adding Photoview, which I fell in love with after seeing it on your site. I want to add PhotoView to [my site](https://github.com/Darthagnon/hugo-theme-dream), but haven't been having much luck with HEG, and was wondering if you had any pointers for how to implement Photoview...?

**Comment by CaiJimmy** [comment]
Codes related to Photoswipe & gallery are contained in this file: https://github.com/CaiJimmy/hugo-theme-stack/blob/master/assets/ts/gallery.ts
