### ISSUE TITLE
Check if hidden posts are properly hidden

### ISSUE THREAD

**Issue by RoneoOrg** [CaiJimmy/hugo-theme-stack#575]
Hi there,

I just implemented a "hidden post feature" for Papermod, maybe my notes could be of some interest for the Stack theme  
(otherwise feel free to close this ticket):
https://roneo.org/en/hugo-hidden-posts/

I love this theme, keep on the great work!

**Comment by tardfree** [comment]
I've been building out a site using the Stack theme and hugo already has a hidden posts ability built in. I had the same requirement, and the built in one works for me with Stack theme. It's documented here if you want to check it out:
https://gohugo.io/content-management/build-options/

**Comment by RoneoOrg** [comment]
Thanks for the valuable pointer!
Now that you know about the solution I discovered lately (surely over-engineered for most use-cases), I'm closing this ticket

Cheers

**Comment by CaiJimmy** [comment]
> I've been building out a site using the Stack theme and hugo already has a hidden posts ability built in. I had the same requirement, and the built in one works for me with Stack theme. It's documented here if you want to check it out:

Thanks for the reference!

This theme has a simple hidden post feature (adding `hidden` field to FrontMatter), but seeing that Hugo has already integrated this feature into their codebase might be better to drop theme support for this and migrate to the official one.
