### ISSUE TITLE
feat: GitLab Snippets Shortcode

### ISSUE THREAD

**Issue by ghost** [CaiJimmy/hugo-theme-stack#577]
**Is your feature request related to a problem? Please describe.**

There is a shortcode for GitHub Gists and it works nicely. The problem is most of my codes are hosted on GitLab. So, I can not use the Gists shortcode.

**Describe the solution you'd like**

GitLab Snippets is equivalent to GitHub Gists. Please consider implementing a shortcode for GitLab Snippets.

**Describe alternatives you've considered**

N/A

**Additional context**

Please see <https://docs.gitlab.com/ee/user/snippets.html>

**Comment by rmdhnreza** [comment]
1. Create file with name `gitlab.html` under `layouts/shortcodes`
2. Add this line to `gitlab.html`
```html
<script type="application/javascript" src="https://gitlab.com/-/snippets/{{ index .Params 0 }}.js"></script>
```
3. Use short code `{{< gitlab snippets-number >}}` example `{{< gitlab 1234567 >}}`
![FSjc32nSrI](https://user-images.githubusercontent.com/23427492/161558406-9009c614-5d37-43d9-9dce-98e7d6211491.png)

**Comment by CaiJimmy** [comment]
@rmdhnreza Thanks for the reply!

Would you like to create a PR for this feature?
