### ISSUE TITLE
希望能开发一个文章加密的功能

### ISSUE THREAD

**Issue by waimao365** [CaiJimmy/hugo-theme-stack#579]
像LoveIt主题这样，添加一个简单的，文章加密码的功能

https://bnblogs.cc/hugo%E6%B7%BB%E5%8A%A0%E6%96%87%E7%AB%A0%E5%8A%A0%E5%AF%86%E5%8A%9F%E8%83%BD/

**Comment by waimao365** [comment]
个人测试在themes\hugo-theme-stack\layouts\_default目录修改single.html文件，在{{ partialCached "footer/footer" . }} 上面添加代码，可以文章加密了。就是每次刷新文章都要输入密码，这个有点烦人。

**Comment by CaiJimmy** [comment]
抱歉，不会添加，这种前端"加密“没有什么意义，禁用 JavaScript 后就能直接看了。
