### ISSUE TITLE
Image width with lightbox

### ISSUE THREAD

**Issue by Ari04T** [CaiJimmy/hugo-theme-stack#586]
I'm not really sure if this is a bug or not, but mostly a question.

For example, if I put this image, the image is correctly used as a gallery item, and therefore displayed with the lightbox
```
![Hola!](hola.png)
```
But if I use it as a figure with the shortcode, then the image is displayed as a standard image, without the lightbox.
```
{{< figure src=hola.png title="Hola! >}}
```
Is there a way to add images without the traditional markdown syntax? If I try adding them with pure HTML ` <img src="hola.png" height="400px" width="300px" />`, the image once again is just displayed as a normal image, not with the lightbox.

I'm asking this because I want to change the size of the displayed image, but right now I'm unable to do it. I've tried `![Hola!](hola.png){width=250px}` but my markdown processor doesn't seem to be able to understand this command.

Thanks, have a nice day.

**Comment by CaiJimmy** [comment]
Hi,

> But if I use it as a figure with the shortcode, then the image is displayed as a standard image, without the lightbox.

That's expected since the `figure` shortcode is not treated by `render-images.html` (where the gallery image logic is)

> If I try adding them with pure HTML `<img src="hola.png" height="400px" width="300px" />`, the image once again is just displayed as a normal image, not with the lightbox.

For the same reason as above. `render-image.html` only intercepts native markdown image syntax.

No plan to support image resize yet. There's already a big headache with image processing...
