### ISSUE TITLE
在二级标题中含有超链接时，目录章节计数不正确（会+1）

### ISSUE THREAD

**Issue by ACRei** [CaiJimmy/hugo-theme-stack#589]
## Describe the bug
在二级标题中含有超链接时，目录章节计数不正确（会+1）

## Expected behavior
在二级标题中含有超链接时，目录章节计数应该正常排列

## To Reproduce
https://rei.ac/post/namomo-spring-camp-2022-div1-%E6%AF%8F%E6%97%A5%E4%B8%80%E9%A2%98/#day33-p678-namonamohttpojdaimayuantopproblem678

https://github.com/ACRei/blog/blob/master/content/post/Namomo_Spring_Camp_2022_Div1_Daily_Problem.md#day33-p678-namonamo

## Screenshots
![image](https://user-images.githubusercontent.com/17238215/164158711-5c2841d4-e476-4135-afd9-46fde8edfbb4.png)

## Environment

- **Hugo version** : v0.92.0-B3549403+extended

## Content of config.yaml

https://github.com/ACRei/blog/tree/master/config/_default

## Link to the demo site and/or source repository

https://github.com/ACRei/blog
https://rei.ac/

**Comment by cubercsl** [comment]
```patch
diff --git a/assets/scss/partials/layout/article.scss b/assets/scss/partials/layout/article.scss
index eb58e77..f7cae78 100644
--- a/assets/scss/partials/layout/article.scss
+++ b/assets/scss/partials/layout/article.scss
@@ -104,7 +104,7 @@
             list-style-type: none;
             counter-reset: item;
 
-            li a::before {
+            li a:first-of-type::before {
                 counter-increment: item;
                 content: counters(item, ".") ". ";
                 font-weight: bold;
```

**Comment by ACRei** [comment]
> I reproduced this issue and this patch worked for me.
> 
> ```diff
> diff --git a/assets/scss/partials/layout/article.scss b/assets/scss/partials/layout/article.scss
> index eb58e77..f7cae78 100644
> --- a/assets/scss/partials/layout/article.scss
> +++ b/assets/scss/partials/layout/article.scss
> @@ -104,7 +104,7 @@
>              list-style-type: none;
>              counter-reset: item;
>  
> -            li a::before {
> +            li a:first-of-type::before {
>                  counter-increment: item;
>                  content: counters(item, ".") ". ";
>                  font-weight: bold;
> ```

好耶，正常工作了，谢谢蔡队
