### ISSUE TITLE
如何添加QQ好友添加链接

### ISSUE THREAD

**Issue by jerrychoices** [CaiJimmy/hugo-theme-stack#591]
想在左边侧栏中加入qq的好友添加跳转链接，但是我在identifer中添加url以后，在hugo server中点击图标仍是跳转到主页home，想问下这个问题如何解决

**Comment by CaiJimmy** [comment]
不是很明白问题 😅，请附上站点源代码和复现的步骤。
`identifier` 不是用来填 URL 的，`url` 字段才是。
