### ISSUE TITLE
Issues when creating categories

### ISSUE THREAD

**Issue by TonyFPY** [CaiJimmy/hugo-theme-stack#592]
Hi, Jimmy,

I've encountered a problem that, when I tried to create a category "Data Structure", there appeared two blocks with the same name at the top of the archive page. Why does it happen?

![image](https://user-images.githubusercontent.com/34860220/164503667-38bc5e5a-cfd7-48b0-837c-7677124b602d.png)

**Comment by CaiJimmy** [comment]
Please use the issue template and provide the link to the source repository.
