### ISSUE TITLE
设置默认语言为英文时，中文categories添加图片无法显示

### ISSUE THREAD

**Issue by ivorytan** [CaiJimmy/hugo-theme-stack#595]
**Is your feature request related to a problem? Please describe.**
设置网站默认语言为英文时，采用hugo new catogories/Test-CN/_index.zh-cn.md命令创建中文新category，在image处直接填image.jpg图片无法显示，填categories/Test-CN/image.jpg图片在achieves页面和categories/test-cn页面都显示，但在后者处图片未裁剪。

以下情况均在local端出现

填image.jpg时achieves页面如下：

![image](https://user-images.githubusercontent.com/71548373/165112795-ace23c75-9a68-49cf-95c1-c904e4b81f81.png)

填categories/Test-CN/image.jpg时：

![image](https://user-images.githubusercontent.com/71548373/165112464-53095db6-f5e1-4fce-9b73-87e6035f99ff.png)

categories页面：

![image](https://user-images.githubusercontent.com/71548373/165112540-6de424f9-feaf-41c8-9ad6-f948018aaca2.png)

**Comment by CaiJimmy** [comment]
无法复现 Bug：
![image](https://user-images.githubusercontent.com/5889006/172045690-3d537d8a-3b34-435c-9047-2582c4f6fa9a.png)

建议上传源代码仓库比较好排查。
