### ISSUE TITLE
主题新版本在safari的巨大bug

### ISSUE THREAD

**Issue by lin-snow** [CaiJimmy/hugo-theme-stack#599]
新版本自3.9开始后在safari上的样式出错，每篇文章的间距都消失了，包括menu的选项间距也消失了，目前已降回低版本，求作者尽快修复，谢谢

**Comment by CaiJimmy** [comment]
使用 iOS 15.5 测试并没有问题。发 Bug report 请使用模板并提供相应信息。

Tested with iOS 15.5 and everything seems fine. Please provide more information using the *bug report* template.

![image](https://user-images.githubusercontent.com/5889006/172045306-c51ccb55-096f-409a-b480-15bf3e01df2a.png)
