### ISSUE TITLE
is it possible to show two articles on the home page 

### ISSUE THREAD

**Issue by SamHamou** [CaiJimmy/hugo-theme-stack#6]
Hello i really love this theme, 
is it possible to show two articles like this 
![Untitled](https://user-images.githubusercontent.com/22003106/92811309-da904080-f3ad-11ea-811e-d8b2b750aaec.jpg) instead of just one

**Comment by CaiJimmy** [comment]
Hi,

It's not possible yet, might be added in future updates.

**Comment by SamHamou** [comment]
okay, thank you :)
