### ISSUE TITLE
没有归档和搜索页面

### ISSUE THREAD

**Issue by wsszh** [CaiJimmy/hugo-theme-stack#60]
Hi，我执行`hugo server`命令预览时，没有归档页和搜索页，请问这个不是自动创建的吗？

**Comment by CaiJimmy** [comment]
请参考 `exampleSite/content/page`，需要创建页面

https://github.com/CaiJimmy/hugo-theme-stack/tree/master/exampleSite/content/page

**Comment by wsszh** [comment]
感谢大佬！
