### ISSUE TITLE
Requst to Add Parameter to Show / Remove 'Publish Dates' on Posts

### ISSUE THREAD

**Issue by Ged296123** [CaiJimmy/hugo-theme-stack#612]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
If possible, a parameter to provide option to show / hide Date of Publish would be appreciated - similiar to #201 

**Describe alternatives you've considered**
The issue has been discussed on https://discourse.gohugo.io/t/content-is-it-same-for-page-and-post-and-how-to-hide-date/2246/3
A parameter in config.yaml (i.e. ShowDatesOnPosts) can de defined as a universal parameter for all posts. 
Additionally, if end-user wants to publish select posts with dates visible, they may add metadata with show the date.

i.e. For yaml

``` markdown
---
title: "My Blog Post"
date: "2015-12-09T15:03:01+09:00"
showthedate: true
---
```

**Additional context**
I tried adding this myself, but having no knowledge in coding, I began messing up the reading time feature.

**Comment by CaiJimmy** [comment]
Sorry, there's no plan to add this feature.

---

> I tried adding this myself, but having no knowledge in coding, I began messing up the reading time feature.

https://github.com/CaiJimmy/hugo-theme-stack/blob/92a6d71ce5d49583a8ad6ac0819cdbef740e6fe4/layouts/partials/article/components/details.html#L28-L35

Change conditional to `{{ if and (not .Date.IsZero) (default true .Params.showthedate) }}` should do the job (I have not tested, but that is the idea essentially ).
