### ISSUE TITLE
Error building site

### ISSUE THREAD

**Issue by L-Super** [CaiJimmy/hugo-theme-stack#617]
hugo server output: 
`WARN 2022/05/25 18:02:13 Module "hugo-theme-stack" is not compatible with this Hugo version; run "hugo mod graph" for more information.`
`Error: Error building site: TOCSS: failed to transform "scss/style.scss" (text/x-scss). Check your Hugo installation; you need the extended version to build SCSS/SASS.: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information`

but my hugo version is `hugo v0.99.1-d524067382e60ce2a2248c3133a1b3af206b6ef1 windows/amd64 BuildDate=2022-05-18T11:18:14Z VendorInfo=gohugoio`

**Comment by zhixuan2333** [comment]
You shuold install extended version for hugo.

extended hugo version example.
```sh
$ hugo version
hugo v0.93.2-643B5AE9+extended windows/amd64 BuildDate=2022-03-04T12:21:49Z VendorInfo=gohugoio
```
