### ISSUE TITLE
Categories have different background colors on some cards

### ISSUE THREAD

**Issue by etsea117** [CaiJimmy/hugo-theme-stack#620]
Hi. I have 3 posts on my site, and the categories for two of them are not showing the correct background color for categories. Is this a common issue? See screenshot below:

<img width="400" alt="Screen Shot 2022-06-04 at 12 06 44 AM" src="https://user-images.githubusercontent.com/62818348/171986918-7d0a1bde-7575-4ade-9d8b-4ab08e827233.png">

I don't see why they would have different background colors.

**Comment by etsea117** [comment]
It looks like this is the piece of code I don't fully comprehend:
```
@for $i from 1 through length($defaultTagBackgrounds) {
            &:nth-child(#{length($defaultTagBackgrounds)}n + #{$i}) {
                .article-category a {
                    background: nth($defaultTagBackgrounds, $i);
                    color: nth($defaultTagColors, $i);
                }
            }
        }
```

**Comment by CaiJimmy** [comment]
> Hi. I have 3 posts on my site, and the categories for two of them are not showing the correct background color for categories.

Unless you have specified the background color for that category, it will use one of the default colors (the code you have pasted above does that):

https://github.com/CaiJimmy/hugo-theme-stack/blob/c1fcec95a64c6787cd08ed9f5194306642058b7a/assets/scss/variables.scss#L1

**Comment by ThomasKollewe** [comment]
> Unless you have specified the background color for that category, it will use one of the default colors (the code you have pasted above does that):
> 
> [hugo-theme-stack/assets/scss/variables.scss](https://github.com/CaiJimmy/hugo-theme-stack/blob/c1fcec95a64c6787cd08ed9f5194306642058b7a/assets/scss/variables.scss#L1)
> 
> Line 1 in [c1fcec9](/CaiJimmy/hugo-theme-stack/commit/c1fcec95a64c6787cd08ed9f5194306642058b7a)
> 
>  $defaultTagBackgrounds: #8ea885, #df7988, #0177b8, #ffb900, #6b69d6;

Hi,
how do you specify the background colors for different categories?
Thanks!
