### ISSUE TITLE
Is hugo-theme-stack supports branch bundles ?

### ISSUE THREAD

**Issue by nodauf** [CaiJimmy/hugo-theme-stack#622]
In the issue #570 you stated that the issue with the images was not a real problem and you give a quote about the **leaf bundles**.

Thus, I wonder if the [branches bundles](https://gohugo.io/content-management/page-bundles/#branch-bundles) are supported by this theme.
```
content/
├── branch-bundle-1
│   ├── branch-content1.md
│   ├── branch-content2.md
│   ├── image1.jpg
│   ├── image2.png
│   └── _index.md
└── branch-bundle-2
    ├── _index.md
    └── a-leaf-bundle
        └── index.md
```

**Comment by CaiJimmy** [comment]
> Thus, I wonder if the [branches bundles](https://gohugo.io/content-management/page-bundles/#branch-bundles) are supported by this theme.

Should work with https://github.com/CaiJimmy/hugo-theme-stack/pull/81.
