### ISSUE TITLE
don't know how to get the 'favicon' field work

### ISSUE THREAD

**Issue by mc-gulu** [CaiJimmy/hugo-theme-stack#629]
## Describe the bug
I tried different resolutions of PNG and ICO images under the `assets` folder, but none of them works.

## Link to the demo site and/or source repository
https://gulu-dev.com/
Please check out site above.

**Comment by CaiJimmy** [comment]
See https://github.com/CaiJimmy/hugo-theme-stack/issues/597#issuecomment-1115792022

**Comment by mc-gulu** [comment]
thanks, it works!
