### ISSUE TITLE
[Bug]: 主题更新后不显示目录、标签云等右侧侧边栏

### ISSUE THREAD

**Issue by lspiritcoderl** [CaiJimmy/hugo-theme-stack#631]
### What happened?

没更新前使用正常，更新后不显示目录、标签云等右侧侧边栏。
更新步骤：
1. 从github下载最新zip包。
2. 将zip包解压后，覆盖hugo内theme文件夹里面的原主题文件夹。
3. 使用`hugo server -D`，文章内不显示目录，主页不显示标签云等右侧侧边栏。
4. 当使用原主题文件夹内layouts文件夹覆盖更新后主题内layouts文件夹，问题可以解决。
但是最近更新后，原layouts文件夹被我删除了，导致右边侧边栏无法显示。

### Hugo version

0.99.1

### Theme version

3.12.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### More information about the browser

firefox101.0, chrome102.0.5005.61

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by CaiJimmy** [comment]
侧边栏配置格式变了，需要手动更改：
https://github.com/CaiJimmy/hugo-theme-stack/blob/b02569add95ceb08ccddba01fb3e810b41db1ce6/exampleSite/config.yaml#L148-L161
