### ISSUE TITLE
url has "++", such as "C++",  can't get the page(404)[Bug]: 

### ISSUE THREAD

**Issue by Kinvy66** [CaiJimmy/hugo-theme-stack#636]
### What happened?

The Blog deploy on vercel.Some of my posts have tags and category names with characters like '++', such as 'c++'.  And  i have enable the tag cloud and category on the slidebar. when i click the tag or category that name with '++', it show 404 page not find.
But when I preview my blog in the local it is ok. 

### Hugo version

0.97.3

### Theme version

3.12.0

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### More information about the browser

 Windows10

### Link to the page with bug

https://kinvy.cn/tags/c++-primer-5th/,  https://kinvy.cn/categories/c++/

### Link to the source repository

https://github.com/Kinvy66/blog

**Comment by CaiJimmy** [comment]
> But when I preview my blog in the local it is ok.

Then it should not be the theme's issue since the page is generated correctly. It might be related to Vercel's server configuration.
