### ISSUE TITLE
[Bug] RSS output codeblocks line number

### ISSUE THREAD

**Issue by DreamOneX** [CaiJimmy/hugo-theme-stack#645]
### What happened?

rss output code block line number causes rss reader to display abnormally  
In browser  
![Screenshot_20220721_144141](https://user-images.githubusercontent.com/83908457/180146981-7cb1daec-f4c8-4961-b292-73161cbd77f5.jpg)
In rss reader  
![Screenshot_20220721_144031_com nononsenseapps feeder play_edit_548446508994955](https://user-images.githubusercontent.com/83908457/180147078-617a86a2-b793-4a26-9426-3906d76253b9.jpg)

### Hugo version

0.101.0 extended

### Theme version

3.12.0

### More information about the browser

RSS reader: feeder 2.2.0

### Link to the page with bug

https://blog.dreamonex.eu.org/p/2022/07/nginx-quic/

### Link to the source repository

https://github.com/DreamOneX/DawnLight-source

**Comment by CaiJimmy** [comment]
Code highlight uses Hugo's internal function and the theme does nothing there. 

BTW, Inoreader's app displays it correctly. You should report this to Feeder's developer.

![image](https://user-images.githubusercontent.com/5889006/180299535-5b252506-13b7-4335-b909-fc90628e04d4.png)

**Comment by DreamOneX** [comment]
Thanks, I'll close this issue
