### ISSUE TITLE
[Bug]: 主题在iOS14.6一下存在样式问题

### ISSUE THREAD

**Issue by lin-snow** [CaiJimmy/hugo-theme-stack#646]
### What happened?

there are a big problem with css on ios14.3and below,the css is "gap",it does not work ,![DD1X7.jpg](https://s1.328888.xyz/2022/07/25/DD1X7.jpg)
![DDkPm.jpg](https://s1.328888.xyz/2022/07/25/DDkPm.jpg)

### Hugo version

laterst extend

### Theme version

latest

### What browsers are you seeing the problem on?

Safari

### More information about the browser

ios 14.3

### Relevant log output

```shell
PS C:\Users\l1nsn\Desktop\site\Blog> hugo server --disableFastRender
Start building sites … 
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

                   | ZH-CN
-------------------+--------
  Pages            |   210
  Paginator pages  |    53
  Non-page files   |   240
  Static files     |     3
  Processed images |   660
  Aliases          |    64
  Sitemaps         |     1
  Cleaned          |     0
  Processed images |   656
  Aliases          |    64
  Sitemaps         |     1
  Cleaned          |     0

Built in 1154 ms
Watching for changes in C:\Users\l1nsn\Desktop\site\Blog\{archetypes,assets,content,data,layouts,static,themes}
Watching for config changes in C:\Users\l1nsn\Desktop\site\Blog\config.yaml, C:\Users\l1nsn\Desktop\site\Blog\themes\hugo-theme-stack\config.yaml
Environment: "development"
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

### Link to the page with bug

https://blog.linsnow.cn/

**Comment by CaiJimmy** [comment]
Related to #520

I expected this to happen. Blame Apple for their poor flexbox support on old systems and Safari being bundled with the system upgrade.

For old browser compatibility, replace flexbox gap with margin: https://github.com/CaiJimmy/hugo-theme-stack/search?q=gap

**Comment by lin-snow** [comment]
sorry, i replace the gap into margin but i also does not effect

**Comment by CaiJimmy** [comment]
It's not simply replacing `gap` with `margin`. You'll have to revert this pull request's commit: https://github.com/CaiJimmy/hugo-theme-stack/pull/520 04cdbcfedfe3f200013e05aecbb96dc3313424b3
