### ISSUE TITLE
[Bug]: Unable to render my article

### ISSUE THREAD

**Issue by miangou** [CaiJimmy/hugo-theme-stack#654]
### What happened?

My articles are not rendered when using this theme

### Hugo version

hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended windows/amd64

### Theme version

latest

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

103.0.5060.134 Windows10

### Relevant log output

```shell
'''
Start building sites …
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
WARN 2022/08/05 21:54:41 Search page not found. Create a page with layout: search.
WARN 2022/08/05 21:54:41 Search page not found. Create a page with layout: search.
WARN 2022/08/05 21:54:41 Archives page not found. Create a page with layout: archives.
WARN 2022/08/05 21:54:41 Search page not found. Create a page with layout: search.
WARN 2022/08/05 21:54:41 Archives page not found. Create a page with layout: archives.
WARN 2022/08/05 21:54:41 Search page not found. Create a page with layout: search.
WARN 2022/08/05 21:54:41 Archives page not found. Create a page with layout: archives.

                   | EN | ZH-CN | AR
-------------------+----+-------+-----
  Pages            | 10 |     7 |  7
  Paginator pages  |  0 |     0 |  0
  Non-page files   |  0 |     0 |  0
  Static files     |  0 |     0 |  0
  Processed images |  4 |     0 |  0
  Aliases          |  5 |     3 |  3
  Sitemaps         |  2 |     1 |  1
  Cleaned          |  0 |     0 |  0

Built in 632 ms
Watching for changes in D:\natsumiicu\natsumiicu\{archetypes,assets,content,data,layouts,static,themes}
Watching for config changes in D:\natsumiicu\natsumiicu\config.yaml, D:\natsumiicu\natsumiicu\themes\hugo-theme-stack\config.yaml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
'''
```

### Link to the page with bug

locate

### Link to the source repository

locate

**Comment by miangou** [comment]
![image](https://user-images.githubusercontent.com/63963655/183092737-fed7de20-d419-4fc7-9773-3b81547a6e6f.png)

**Comment by miangou** [comment]
![image](https://user-images.githubusercontent.com/63963655/183092891-44cb9b0f-1215-4649-b8d5-8d8a0056a5d7.png)
![image](https://user-images.githubusercontent.com/63963655/183092980-bc363f8b-c9d0-4562-ac47-ea821090aba7.png)

**Comment by miangou** [comment]
the chinese docs say:
'''
如果是第一次使用本主题，建议把 exampleSite 文件夹中的 assets 和 config.yaml 复制到站点目录下。后者是 Hugo 站点的配置文件，已经写入了主题的可配置字段。
'''
translate it to
‘’‘
If you are using this theme for the first time, it is recommended to copy the assets and config.yaml in the exampleSite folder to the site directory. The latter is the configuration file for the Hugo site, which has been written to the configurable fields of the theme.
’‘’
But the repository doesn't have an assets folder

**Comment by CaiJimmy** [comment]
Rename `content/posts` folder to `content/post`. Or modify `params.mainSections` in `config.yaml`, changing `post` to `posts`.

BTW the Chinese documentation is outdated (The English one is too, but newer relatively).

**Comment by miangou** [comment]
Can I try to translate the latest documentation?

**Comment by CaiJimmy** [comment]
Of course. It's available here:

https://github.com/CaiJimmy/stack-docs
