### ISSUE TITLE
[Bug]: Directory only supports 9, not 9+

### ISSUE THREAD

**Issue by miangou** [CaiJimmy/hugo-theme-stack#655]
### What happened?

Directory only supports 9, not 9+

### Hugo version

hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio

### Theme version

latest

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

104 Windows10

### Relevant log output

```shell
Directory only supports 9, not 9+
```

### Link to the page with bug

locahost

**Comment by CaiJimmy** [comment]
Could you please clarify…? 
I can't understand what you are trying to say with "Directory only supports 9, not 9+".
