### ISSUE TITLE
Why doesn't it work when I modify the theme's html?

### ISSUE THREAD

**Issue by yigeqiji** [CaiJimmy/hugo-theme-stack#662]
### What happened?

When I modify `hugo-theme-stack/layouts/partials/article-list/compact.html`, nothing seems to work, am I missing something important?
What should I do to modify the style of the home page list correctly?

### Hugo version

ex 0.100.0

### Theme version

ex .3.

### What browsers are you seeing the problem on?

Microsoft Edge

### More information about the browser

windows11

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by CaiJimmy** [comment]
> Link to the source repository
> No response

Provide the website's source code, otherwise, nobody knows why it fails.
