### ISSUE TITLE
[Bug]: search not working after deploy

### ISSUE THREAD

**Issue by uluumbch** [CaiJimmy/hugo-theme-stack#689]
### What happened?

my site search is not working after deploy otherwise in local development all feature worked perfectly. here is my site 

### Hugo version

0.102.3

### Theme version

3.13.0

### Link to the page with bug

https://uluumbch.my.id/search

**Comment by CaiJimmy** [comment]
![image](https://user-images.githubusercontent.com/5889006/191527341-6af5476b-b664-476f-9f12-ee676b90631f.png)

Wrong `baseurl` in your config file.

**Comment by uluumbch** [comment]
thank you so much🙏
