### ISSUE TITLE
[Bug]: 链接显示

### ISSUE THREAD

**Issue by lin-snow** [CaiJimmy/hugo-theme-stack#692]
### What happened?

![image](https://user-images.githubusercontent.com/99076044/193401416-927c55f2-8fbc-46ee-bfdd-fbe6299cf835.png)
 如何让原主题的links显示在article上方，效果如上图

### Hugo version

lastest

### Theme version

lastest

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

windows11 ,lastest

### Link to the page with bug

https://dev.stack.jimmycai.com/links/

**Comment by CaiJimmy** [comment]
> 如何让原主题的links显示在article上方，效果如上图

不是 Bug 请不要发在 Issue。

需要自行修改模板：https://github.com/CaiJimmy/hugo-theme-stack/blob/b1e8472bcf54e2a3699cede0dcc0e5349485ff22/layouts/_default/single.html#L29-L31

**Comment by lin-snow** [comment]
> > 如何让原主题的links显示在article上方，效果如上图
> 
> 
> 
> 不是 Bug 请不要发在 Issue。
> 
> 
> 
> 需要自行修改模板：https://github.com/CaiJimmy/hugo-theme-stack/blob/b1e8472bcf54e2a3699cede0dcc0e5349485ff22/layouts/_default/single.html#L29-L31

请问是将{{ if .Params.links }}
        {{ partial "article/components/links" . }}
    {{ end }}移动到最上方吗
