### ISSUE TITLE
[Bug]: Codebox background error in light mode

### ISSUE THREAD

**Issue by ChobobDev** [CaiJimmy/hugo-theme-stack#695]
### What happened?

I am experiencing that the code box background is not changing in light mode.
which means the code box background in light mode and the dark mode are the same.

I have implemented the theme through the` go.mod` file which is the newest way of implementing the theme.

[related issue](https://github.com/CaiJimmy/hugo-theme-stack/issues/492) can be found here.

![image](https://user-images.githubusercontent.com/32432141/193585627-ac982423-9278-41e2-a479-ed6836c9786a.png)

### Hugo version

v0.101.0

### Theme version

v3.14.0

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

windows 11 / Chrome

### Link to the page with bug

https://demo.stack.jimmycai.com

### Link to the source repository

https://github.com/ChobobDev/chobobdev.github.io/blob/main/content/post/object_calisthenics/index.md

**Comment by CaiJimmy** [comment]
I'm not able to reproduce it on this page, which contains code blocks: https://dev.stack.jimmycai.com/p/markdown-syntax-guide/

Try to delete your `resources` folder, which contains previous generated CSS files

**Comment by ChobobDev** [comment]
I am not sure why but even though I deleted my resources folder, I am still having the same trouble.

**Comment by ChobobDev** [comment]
[article](https://chobobdev.github.io/p/oop%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5-%EC%83%9D%ED%99%9C-%EC%B2%B4%EC%A1%B0-%EC%9B%90%EC%B9%99object-calisthenics/) you can find my article from following link

**Comment by ChobobDev** [comment]
Thank you for your kind guidance, it is now working as I desired .
