### ISSUE TITLE
Multiple images on one page in same image presentation

### ISSUE THREAD

**Issue by siskosgithub** [CaiJimmy/hugo-theme-stack#70]
**Describe the bug**
If you put multiple images on one page like on this page https://theme-stack.jimmycai.com/p/test-chinese/
But you put them on a new line they end up in another image presentation

**To Reproduce**
1. Go to 'https://theme-stack.jimmycai.com/p/test-chinese/'
2. Click on 'an image'
3. Press arrows to navigate
4. You can only navigate to images that are put on the same line

**Expected behavior**
I would expect that you can navigate to all the images on the same page.
Or at least have an option to put the navigation on to all the images on the same page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox and Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone SE2020 and Samsung Galaxy S51

**Comment by CaiJimmy** [comment]
You're right. This is something that should be improved. I used the example code from https://photoswipe.com/documentation/getting-started.html, and that's its default behaviour.

https://github.com/CaiJimmy/hugo-theme-stack/blob/d2057533233c480fde3c526d865cfb1276d6b4ef/assets/ts/gallery.ts#L8-L207

I do not have experience of customizing PhotoSwipe. Will take some time to understand its code & fix this. PRs / suggestions are welcome.
