### ISSUE TITLE
[Bug]: avatar picture won't be loaded

### ISSUE THREAD

**Issue by martinliu** [CaiJimmy/hugo-theme-stack#700]
### What happened?

I have the avatar file in img folder, as you can see here: https://github.com/martinliu/martinliu.github.io/blob/master/static/img/avatar.png

but, it won't be loaded either locally or remotely https://martinliu.cn/

avatar always shows 150x150 pic.

I have to spend a few days trying to fix this, and I can not figure out a way. 

### Hugo version

https://martinliu.cn/

### Theme version

v3.14.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### More information about the browser

Chrome 105.0.5195.125

### Link to the page with bug

https://martinliu.cn/

### Link to the source repository

https://github.com/martinliu/martinliu.github.io

**Comment by CaiJimmy** [comment]
> I have the avatar file in img folder, as you can see here: 
> https://github.com/martinliu/martinliu.github.io/blob/master/static/img/avatar.png

In your case (`local = true` and `src = img/avatar.png`), the image file should be placed at `SITE_FOLDER/assets/img/avatar.png`.

**Comment by martinliu** [comment]
I have no idea why I should create "assets" folder right at the site root folder. But, it works in my case.
We would change the document a little bit, as far as I understand a local place for avatar picture should just be in static folder.
Thanks for your help and this great work.
Keep you going!

Martin

**Comment by CaiJimmy** [comment]
I agree, the new documentation still has confusing parts. I'll try to improve it in the future. Meanwhile, PRs are welcome

**Comment by pplmx** [comment]
@CaiJimmy 
> I agree, the new documentation still has confusing parts. I'll try to improve it in the future. Meanwhile, PRs are welcome

This issue seems it is still not improved, right?

**Comment by CaiJimmy** [comment]
> @CaiJimmy
> 
> > I agree, the new documentation still has confusing parts. I'll try to improve it in the future. Meanwhile, PRs are welcome
> 
> This issue seems it is still not improved, right?

I added a simple explanation of how to use the `local' property: https://stack.jimmycai.com/config/sidebar#avatar-local

But yes, the documentation in general needs more work. However, I'm in my last year of graduate school and don't have time for this project.
