### ISSUE TITLE
[Bug]: Katex Matricies not rendering properly

### ISSUE THREAD

**Issue by Esauidk** [CaiJimmy/hugo-theme-stack#702]
### What happened?

Matrices are not being rendered properly:

$$
\begin{bmatrix}
x+1\\
y  \\
0
\end{bmatrix}=
\begin{bmatrix}x+1 \\ 
y \\ 
\end{bmatrix}=
\begin{bmatrix}
1 & 0 & 1 \\
0 & 1 & 0 \\
0 & 0 & 0
\end{bmatrix}
*
\begin{bmatrix}
x  \\
y  \\
1
\end{bmatrix}
$$

```
$$
\begin{bmatrix}
x+1  \\
y  \\
0
\end{bmatrix}=
\begin{bmatrix}x+1\\ y\\ \end{bmatrix}=
\begin{bmatrix}
1 & 0 & 1 \\
0 & 1 & 0 \\
0 & 0 & 0
\end{bmatrix}
*
\begin{bmatrix}
x  \\
y  \\
1
\end{bmatrix}
$$
```

Ends up looking like

$$
\begin{bmatrix}
x+1  &
y &
0&
\end{bmatrix}=
\begin{bmatrix} x+1 &y \end{bmatrix}=
\begin{bmatrix}
1 & 0 & 1 &
0 & 1 & 0 &
0 & 0 & 0
\end{bmatrix}
*
\begin{bmatrix}
x  &
y  &
1
\end{bmatrix}
$$

```
$$
\begin{bmatrix}
x+1  &
y &
0&
\end{bmatrix}=
\begin{bmatrix} x+1 &y \end{bmatrix}=
\begin{bmatrix}
1 & 0 & 1 &
0 & 1 & 0 &
0 & 0 & 0
\end{bmatrix}
*
\begin{bmatrix}
x  &
y  &
1
\end{bmatrix}
$$
```

### Hugo version

v0.99.1+extended darwin/arm64

### Theme version

3.14

### What browsers are you seeing the problem on?

Chrome

### Link to the page with bug

https://esauidk.github.io/p/3d-graphics-intro/

**Comment by CaiJimmy** [comment]
Might be related to this: https://github.com/CaiJimmy/hugo-theme-stack/issues/196#issuecomment-824179837

Can you try the workaround mentioned above?

**Comment by Esauidk** [comment]
Yep! Turns out that fixed it, thx
