### ISSUE TITLE
[Bug]: main page image (thumbnail) size cannot decrease

### ISSUE THREAD

**Issue by Haebuk** [CaiJimmy/hugo-theme-stack#703]
### What happened?

I tried to decrease image size, but hugo renders the image too big.
how can I fix it? thank you. 

<img width="701" alt="image" src="https://user-images.githubusercontent.com/68543150/197326144-9e6d28d8-d1e2-4a81-9b89-b7ace6f7d203.png">

the above image size didn't change regardless of resizing image.

### Hugo version

hugo v0.101.0+extended darwin/arm64 BuildDate=unknown

### Theme version

where to find it? I only knows it version starts with 3.

### What browsers are you seeing the problem on?

Chrome

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by CaiJimmy** [comment]
It's controlled by CSS and there's no per-page configuration for it.

https://github.com/CaiJimmy/hugo-theme-stack/blob/ae497c478924fb454783b3953d3ff09188ccdfcb/assets/scss/partials/article.scss#L21-L35
