### ISSUE TITLE
[Bug]: The right sidebar vertical overflow

### ISSUE THREAD

**Issue by lin-snow** [CaiJimmy/hugo-theme-stack#718]
### What happened?

![image](https://user-images.githubusercontent.com/99076044/200107967-5b789080-524b-423e-9cb3-f09774c6ee87.png)
当归档足够多时，tagcloud的tag会触碰到最底部

### Hugo version

lastest

### Theme version

lastest

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

windows11 ,lastest

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by CaiJimmy** [comment]
There were already attempts to fix this, but none of them convinced me.

Probably won't be fixed for a long time. As a workaround, reduce the number of widgets displayed.

**Comment by lin-snow** [comment]
> There were already attempts to fix this, but none of them convinced me.
> 
> 
> 
> Probably won't be fixed for a long time. As a workaround, reduce the number of widgets displayed.

I may provide a possible solution that use the br label added to footer.html

**Comment by CaiJimmy** [comment]
Should be fixed with #765
