### ISSUE TITLE
[Bug]: sitemap error

### ISSUE THREAD

**Issue by lin-snow** [CaiJimmy/hugo-theme-stack#720]
### What happened?

https://dev.stack.jimmycai.com/sitemap.xml
sitemap显示的内容是不正确的
![image](https://user-images.githubusercontent.com/99076044/200254028-22a7754b-c615-4097-b728-a370b9b371a1.png)

### Hugo version

lastest

### Theme version

lastest

### More information about the browser

windows11 ,lastest

### Link to the page with bug

https://dev.stack.jimmycai.com/sitemap.xml

**Comment by CaiJimmy** [comment]
It's Hugo's expected behavior after enabling multilingual site support.

Not related to the theme.
