### ISSUE TITLE
[Bug]: Insert http external pictures, can not enlarge the picture

### ISSUE THREAD

**Issue by mpv945** [CaiJimmy/hugo-theme-stack#722]
### What happened?

I add the following to my blog:

![hugo-theme-stack](https://images.ewancle.com/blog/imghugo-init-page.png)

When you do a good job, you can see the pictures, but you can't click to enlarge like the local pictures.

### Hugo version

hugo v0.104.3+extended linux/amd64

### Theme version

v3.16.0

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

Chrome 107.0.5304.87, Ubuntu 20.04.4 LTS

### Link to the page with bug

https://www.ewancle.com/p/blog-1-chinese

**Comment by CaiJimmy** [comment]
That's the expected behavior. It has been explained in the documentation:

https://stack.jimmycai.com/writing/markdown

![image](https://user-images.githubusercontent.com/5889006/202295038-1dfecbb1-b75a-4d46-9a7e-8c42a7b4ab8d.png)
