### ISSUE TITLE
[Bug]: unterminated quoted string

### ISSUE THREAD

**Issue by Purkit8075** [CaiJimmy/hugo-theme-stack#723]
### What happened?

当我用 `hugo` 时，终端显示：`Error: add site dependencies: load resources: loading templates: "/themes/hugo-theme-stack/layouts/partials/sidebar/left.html:65:1": parse failed: template: partials/sidebar/left.html:65: unterminated quoted string`
这一行的代码： `  {{ warnf "Menu item [%s] is using [pre] field to set icon, please use [params.icon] instead.\nMore
`
部署没有问题，但是本地不能预览。

### Hugo version

0.106.0

### Theme version

3.16.0

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by CaiJimmy** [comment]
Please provide the link to the source repository, otherwise, there's no way I can't reproduce the issue.

**Comment by Purkit8075** [comment]
> Please provide the link to the source repository, otherwise, there's no way I can't reproduce the issue.


不好意思，我将这个 `HTML` 文件代码格式化了，然后导致了这个问题。麻烦了（
