### ISSUE TITLE
[Bug]: CATEGORIES can't now show the image.

### ISSUE THREAD

**Issue by bs10081** [CaiJimmy/hugo-theme-stack#726]
### What happened?

In Hugo serve:

<img width="792" alt="CleanShot 2022-11-27 at 19 10 01@2x" src="https://user-images.githubusercontent.com/38148679/204132099-7909b06d-a54c-413a-abef-ddcbe8ef57d1.png">

Public to github.io:

<img width="782" alt="CleanShot 2022-11-27 at 19 09 50@2x" src="https://user-images.githubusercontent.com/38148679/204132106-6fdc8eec-dd2f-4d77-abac-4ccc3693d8c5.png">

Code:

<img width="617" alt="CleanShot 2022-11-27 at 19 12 56@2x" src="https://user-images.githubusercontent.com/38148679/204132188-4715eb4b-6721-47c3-b256-7fddcdb9f8c4.png">

### Hugo version

0.107

### Theme version

3.16

### More information about the browser

Chromium 107, macOS 12

### Link to the page with bug

https://regchien.info/archives/

### Link to the source repository

https://github.com/bs10081/bs10081.github.io

**Comment by FarrelF** [comment]
You can add the `.nojekyll` file in your root repository first if you're using GitHub Pages.
