### ISSUE TITLE
math equation render correctly on local but raw format in web

### ISSUE THREAD

**Issue by jmwyf** [CaiJimmy/hugo-theme-stack#733]
### What happened?

hugo server posts with math equations well on local, but don't render math when host on GitHub. Anything else seems fine.

### Hugo version

hugo v0.107.0+extended

### Theme version

latest

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

Mac

### Link to the page with bug

https://youngforever.tech

**Comment by CaiJimmy** [comment]
Math equation seems to be working correctly in the demo site: https://dev.stack.jimmycai.com/p/math-typesetting/

You need to provide more information (like the content of the Markdown file).

**Comment by jmwyf** [comment]
> Math equation seems to be working correctly in the demo site: https://dev.stack.jimmycai.com/p/math-typesetting/
> 
> You need to provide more information (like the content of the Markdown file).

I test use the same content in exampleSite [`math-typesetting`](https://youngforever.tech/p/math-typesetting/). [code](https://github.com/jmwyf/jmwyf.github.io)

Is there somewhere I should change in the theme? thx!

**Comment by CaiJimmy** [comment]
Try disabling Cloudflare Rocket Loader.

**Comment by jmwyf** [comment]
> Try disabling Cloudflare Rocket Loader.

cool! It works. thank you!!

I even forgot that I have setup cloudflare with the site. I can't believe it's still working after several years.
