### ISSUE TITLE
[Bug]: 内容太长了 

### ISSUE THREAD

**Issue by lin-snow** [CaiJimmy/hugo-theme-stack#745]
### What happened?

强烈建议推出代码块过长折叠功能,或者内容折叠的shortcode,谢谢

### Hugo version

lastest extended

### Theme version

lastest

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

windows11 ,lastest

### Link to the page with bug

https://demo.stack.jimmycai.com

### Link to the source repository

none

**Comment by CaiJimmy** [comment]
抱歉，不接受新的 Feature Request 了，没有精力去维护。

**Comment by QingQiuGeek** [comment]
> ### What happened?
> 强烈建议推出代码块过长折叠功能,或者内容折叠的shortcode,谢谢
> 
> ### Hugo version
> lastest extended
> 
> ### Theme version
> lastest
> 
> ### What browsers are you seeing the problem on?
> Chrome
> 
> ### More information about the browser
> windows11 ,lastest
> 
> ### Relevant log output
> _No response_
> 
> ### Link to the page with bug
> https://demo.stack.jimmycai.com
> 
> ### Link to the source repository
> none

请问你实现了代码块折叠的功能了吗，如何做，我需要它
