### ISSUE TITLE
[Bug]: 代码块和引用块显示

### ISSUE THREAD

**Issue by lin-snow** [CaiJimmy/hugo-theme-stack#746]
### What happened?

![image](https://user-images.githubusercontent.com/99076044/209459417-4f24c6f7-a8e9-479f-9d26-6ca02bf5316b.png)
引用块里的链接不会换行
![image](https://user-images.githubusercontent.com/99076044/209459431-f3a09ade-b71e-4b7e-aefb-75891d513aa8.png)
代码块里的链接不会换行

### Hugo version

laterst extend

### Theme version

lastest

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### More information about the browser

windows11 ,lastest

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by CaiJimmy** [comment]
给 `<a>` 和 `<code>` 添加 `word-break: break-word;` 属性即可。
