### ISSUE TITLE
[Bug]: Heading 1 is not shown in TOC

### ISSUE THREAD

**Issue by youkq95** [CaiJimmy/hugo-theme-stack#749]
### What happened?

Md syntax `# H1` is not shown in the article TOC, as you can see from the demo site: [Markdown Syntax Guide](https://dev.stack.jimmycai.com/p/markdown-syntax-guide/)

### Hugo version

0.104 

### Theme version

3.16.0

### What browsers are you seeing the problem on?

Chrome

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by CaiJimmy** [comment]
https://github.com/CaiJimmy/hugo-theme-stack/blob/4272da7ee402b43fab957cf328e622279168354c/exampleSite/config.yaml#L231

It’s configurable.

**Comment by mahone3297** [comment]
I think the default value startLevel should be 1 is more make sense.

**Comment by mahone3297** [comment]
@CaiJimmy hello,
Can you tell me how does the param startLevel affect the TOC html?
I search all the codo in this repo, there is only one
```
./exampleSite/hugo.yaml:243:        startLevel: 2
```

and I try to search the parent keyword `tableOfContents`, and still found nothing.

how dose this code below(toc.html) run?
```
        <div class="widget--toc">
            {{ .Context.TableOfContents }}
        </div>
```
