### ISSUE TITLE
[Bug]: Typo in README.md

### ISSUE THREAD

**Issue by RoelofLangman** [CaiJimmy/hugo-theme-stack#764]
### What happened?

In README.md, under heading Demo, I read: "Stater template demo". 

This is meant to be: "Starter template demo". Stater -> Starter.

### Hugo version

0.109.0+extended darwin/amd64

### Theme version

3.16.0

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

Chrome v109.0.5414.87, Mac OSX 

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by CaiJimmy** [comment]
Thanks!
