### ISSUE TITLE
[Bug]: 代码块没有左右滚动条

### ISSUE THREAD

**Issue by chenxiex** [CaiJimmy/hugo-theme-stack#779]
### What happened?

当代码过长时，代码块不会显示左右滚动条，也不会自动换行，导致超出代码块的代码无法显示。使用markdown内置的代码块` ```language `以及hugo的highlight shortcode都是如此。
![图片](https://user-images.githubusercontent.com/28776935/218507413-b211c99e-7a14-41f6-ac29-85b32bce9a10.png)

### Hugo version

hugo v0.109.0+extended

### Theme version

git canary

### What browsers are you seeing the problem on?

Firefox, Chrome

### More information about the browser

firefox 109.1.0 Manjaro Linux, Chromium 109.0.5414.119 Manjaro Linux

### Link to the page with bug

https://blog.anlor.top/post/manjaro-luks-slow/

### Link to the source repository

https://github.com/chenxiex/alblog

**Comment by Raspberrycai1** [comment]
@chenxiex FYI, as mentioned in the [FAQs of hugo-PaperMod](https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma)

> the `lineNos: true` will only work with `noClasses: false` or `pygmentsUseClasses: true`

**Comment by chenxiex** [comment]
I set noclasses to false and it works, THX!
