### ISSUE TITLE
[Bug]: 多个 < 或者 > 渲染样式问题

### ISSUE THREAD

**Issue by lai9fox** [CaiJimmy/hugo-theme-stack#782]
### What happened?

```md
无符号右移 (>>>)
```
![image](https://user-images.githubusercontent.com/59388471/219411540-8563f99d-1616-489b-9729-7d9af16b3ea0.png)
渲染的结果很奇怪，如何去掉这种连词效果？

### Hugo version

v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended windows/amd64 BuildDate=2022-12-23T10:38:11Z

### Theme version

3.16.0

### What browsers are you seeing the problem on?

Chrome

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by CaiJimmy** [comment]
主题并没有做这方面的处理，应该和 Hugo 的 Markdown 解析器有关：https://gohugo.io/getting-started/configuration-markup/

可能是 `typographer` 属性。
