### ISSUE TITLE
[Bug]: i18n多语言的html lang设定错误；front matter的lang属性设置无效

### ISSUE THREAD

**Issue by acabgb** [CaiJimmy/hugo-theme-stack#789]
### What happened?

config文件中设定的默认语言为en
则所有其他语言的页面都是lang="en-us"
并没有根据实际使用的语言变更。
可以根据config中i18n的设定自动设定相应语言的html lang code吗？
例如：这个就自动设定为lang="es"
es:
        languageName: Español
        title: title
        description: description
        weight: x
        contentDir: content/es

此外，尝试在md文档的front matter中的lang属性进行自定义设定，也还是无法变更html lang code的显示。
希望支持这个属性，这样默认es语言目录的md文件全部是lang="es"；其中有md文档自定义属性的，则按自定义的为准。
谢谢！

### Hugo version

0.110.0

### Theme version

latest

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by CaiJimmy** [comment]
> config文件中设定的默认语言为en
> 则所有其他语言的页面都是lang="en-us"

抱歉无法复现这个问题，我这里开启多语言功能后，每个子站点的 `lang` 标签都设置成了对应语言的：

![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/5889006/e9e9a723-835a-4be6-8347-7ea7cf89f6f4)

你也可以在 https://dev.stack.jimmycai.com/ 看到效果。

------

> 此外，尝试在md文档的front matter中的lang属性进行自定义设定，也还是无法变更html lang code的显示。
> 希望支持这个属性，这样默认es语言目录的md文件全部是lang="es"；其中有md文档自定义属性的，则按自定义的为准。

抱歉没有这个打算，你可以自己修改主题的 `baseof.html`：

https://github.com/CaiJimmy/hugo-theme-stack/blob/eefa68666171e3fcf413a00b1e91aebe8e9874e5/layouts/_default/baseof.html#L2C1-L2C1

**Comment by CaiJimmy** [comment]
我先把这个 Issue 关闭了。如果问题还存在的话欢迎重新打开 Issue 并提供一个最小重现 🙏。
