### ISSUE TITLE
[Bug]: 右边栏居中

### ISSUE THREAD

**Issue by JingYiJun** [CaiJimmy/hugo-theme-stack#795]
### What happened?

右边栏居中

### Hugo version

0.110.0

### Theme version

master

### What browsers are you seeing the problem on?

Microsoft Edge

### More information about the browser

Microsoft Edge 110.0.1587.63, Windows 10

### Link to the page with bug

https://jingyijun.github.io

**Comment by darkbluesoul** [comment]
出现同样问题，后来发现是hugo根目录的assets里有scss文件夹，这个优先级高于主题的scss，主题的scss没问题。我直接把assets里的scss文件夹重命名为scss.bak，右边栏就回去了。你看看是不是同样的原因？

**Comment by JingYiJun** [comment]
解决了，谢谢
