### ISSUE TITLE
[Bug]: code "bilibili" not found

### ISSUE THREAD

**Issue by changchichung** [CaiJimmy/hugo-theme-stack#804]
### What happened?

code "bilibili" not found when running hugo -D
```
2023-03-25 11:06:49 [chchang@ny mc ]$ hugo
Start building sites … 
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
Error: Error building site: "/home/chchang/hugo/mc/content/post/rich-content/index.md:38:1": failed to extract shortcode: template for shortcode "bilibili" not found
Total in 32 ms
```

### Hugo version

hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended

### Theme version

3.16.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by fzf404** [comment]
how to solve it?

**Comment by fzf404** [comment]
thanks, i solve it by clean the hugo cache file.
