### ISSUE TITLE
[Bug]: Can't use inline tags whereas inline categories works fine

### ISSUE THREAD

**Issue by mathisgauthey** [CaiJimmy/hugo-theme-stack#840]
### What happened?

I was playing with your template until I found out that tags can't be put inline like categories in the YAML frontmatter.

For instance, this works :
```
categories: guide
tags:
    - linux
    - dev
```

But this doesn't work : 
```
categories: guide
tags: linux dev
```

Is there something that I can do to make it work ? I need that flat tags since I'm using Obsidian to convert my notes and use this format for a one-click export to my website.

Thanks in advance !

### Hugo version

v0.115.3-5c2e014a5150553a9fa4f9c1eb7dc4db89c0f1ab+extended linux/amd64 BuildDate=2023-07-13T16:11:34Z VendorInfo=snap:0.115.3

### Theme version

V3

### What browsers are you seeing the problem on?

Firefox

### More information about the browser

115.0.2 (64 bit)

### Relevant log output

```shell
render: failed to render pages: render of "page" failed: [1;36m"/tmp/hugo_cache_mathis/modules/filecache/modules/pkg/mod/github.com/!cai!jimmy/hugo-theme-stack/v3@v3.16.0/layouts/_default/baseof.html:4:12"[0m: execute of template failed at <partial "head/head.html" .>: error calling partial: [1;36m"/tmp/hugo_cache_mathis/modules/filecache/modules/pkg/mod/github.com/!cai!jimmy/hugo-theme-stack/v3@v3.16.0/layouts/partials/head/head.html:15:4"[0m: execute of template failed at <partial "head/opengraph/include.html" .>: [1;36m"/tmp/hugo_cache_mathis/modules/filecache/modules/pkg/mod/github.com/!cai!jimmy/hugo-theme-stack/v3@v3.16.0/layouts/partials/head/opengraph/include.html:1:3"[0m: execute of template failed at <partial "head/opengraph/provider/base" .>: [1;36m"/tmp/hugo_cache_mathis/modules/filecache/modules/pkg/mod/github.com/!cai!jimmy/hugo-theme-stack/v3@v3.16.0/layouts/partials/head/opengraph/provider/base.html:22:21"[0m: execute of template failed at <.Params.tags>: range can’t iterate over linux dev 

/tmp/hugo_cache_mathis/modules/filecache/modules/pkg/mod/github.com/!cai!jimmy/hugo-theme-stack/v3@v3.16.0/layouts/_default/baseof.html:4:12:

<html lang="{{ .Site.LanguageCode }}" dir="{{ default `ltr` .Language.LanguageDirection }}">
    <head>
        {{- partial "head/head.html" . -}}
        {{- block "head" . -}}{{ end }}
    </head>

/tmp/hugo_cache_mathis/modules/filecache/modules/pkg/mod/github.com/!cai!jimmy/hugo-theme-stack/v3@v3.16.0/layouts/partials/head/head.html:15:4:

{{- partial "head/style.html" . -}}
{{- partial "head/script.html" . -}}
{{- partial "head/opengraph/include.html" . -}}

{{- range .AlternativeOutputFormats -}}

/tmp/hugo_cache_mathis/modules/filecache/modules/pkg/mod/github.com/!cai!jimmy/hugo-theme-stack/v3@v3.16.0/layouts/partials/head/opengraph/include.html:1:3:

{{ partial "head/opengraph/provider/base" . }}
{{ partial "head/opengraph/provider/twitter" . }}

/tmp/hugo_cache_mathis/modules/filecache/modules/pkg/mod/github.com/!cai!jimmy/hugo-theme-stack/v3@v3.16.0/layouts/partials/head/opengraph/provider/base.html:22:21:

{{- if .IsPage -}}
    <meta property='article:section' content='{{ .Section | title }}' />
    {{- range .Params.tags -}}
        <meta property='article:tag' content='{{ . }}' />
    {{- end -}}

hugo v0.115.3-5c2e014a5150553a9fa4f9c1eb7dc4db89c0f1ab+extended linux/amd64 BuildDate=2023-07-13T16:11:34Z VendorInfo=snap:0.115.3
Reload Page
```

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by CaiJimmy** [comment]
This theme (among others I believe) assumes that the `tag` field is of type `String[]`, hence the error when trying to iterate over (`range .Params.tags`).

> Is there something that I can do to make it work ?

I believe you can modify the theme to make it split the string before iterating over it.

**Comment by mathisgauthey** [comment]
Alright, so **categories** can either be single or multi-line, **tags** needs to be multi-line and **aliases** can be either but shouldn't have an empty entry in multi-line otherwise it doesn't work. Quite a complicated setup to automate my workflow, but now that I know the rules I'll do what I need to do, thanks!

On an added note, it would be great to ease the thing by having a standard way or reading these three standard keys I guess.
