### ISSUE TITLE
[Bug]: 设置 comment:false 评论框并没有被隐藏

### ISSUE THREAD

**Issue by debuginn** [CaiJimmy/hugo-theme-stack#847]
### What happened?

设置 comment:false 评论框并没有被隐藏

### Hugo version

0.89.0

### Theme version

3.17.0

### More information about the browser

Mac, Chrome

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by Lovirr** [comment]
comment:false
comment: false
少了个空格？yaml要求冒号后面必须空一格

**Comment by debuginn** [comment]
> comment:false comment: false 少了个空格？yaml要求冒号后面必须空一格

我试下

**Comment by debuginn** [comment]
> 

试了下 没有用

**Comment by Lovirr** [comment]
在config.yaml和文章抬头的yaml段里都设置为false了吗
<img width="391" alt="image" src="https://github.com/CaiJimmy/hugo-theme-stack/assets/106920260/746427c9-8a76-4a5e-918a-9417b0dd5ffa">
<img width="229" alt="image" src="https://github.com/CaiJimmy/hugo-theme-stack/assets/106920260/aa9d1e43-b298-408f-b878-47e09081b72c">

**Comment by debuginn** [comment]
我想隐藏部分文章的评论

**Comment by CaiJimmy** [comment]
抱歉，无法复现这个 Bug，可以提供一个最小重现吗？

Sorry, I haven't been able to reproduce this bug. Could you please submit a minimal reproducible example?

**Comment by debuginn** [comment]
> 

好的 我这边设置这个文章不可以进行评论，但是还是出现了评论栏目：
https://github.com/debuginn/blog/blob/main/content/post/summary/debuginn-hugo-blog.md?plain=1

**Comment by CaiJimmy** [comment]
你提供的仓库是私密的，我看不到内容。

The link you provided is pointed to a private repository and I cannot see the content.

**Comment by debuginn** [comment]
奥奥 不好意思 我把 文章的 head 给你看下

```
---
title: "全站静态化升级完毕"
date: 2023-05-14T13:14:07+08:00
draft: false
author: "Meng小羽"
authorLink: "https://debuginn.cn"
authorEmail: "debuginn@icloud.com"
keywords: "Debug客栈"
comment: false
weight: 0
tags: [ "Debug客栈" ]
categories: [ "summary" ]
---
```

**Comment by CaiJimmy** [comment]
是 `comments`。
