### ISSUE TITLE
[Bug]: 在代码块中的短代码也会被渲染

### ISSUE THREAD

**Issue by Xalaok** [CaiJimmy/hugo-theme-stack#849]
### What happened?

![](https://github.com/CaiJimmy/hugo-theme-stack/assets/74130512/b33c2048-b298-4d56-b2c0-82ee6633d2a1)

### Hugo version

0.115.4

### Theme version

3.16.0

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

Chrome 115, Windows 11

### Link to the page with bug

https://blog.xalaok.top/post/hugo-shortcodes

**Comment by Lovirr** [comment]
在尖括号内加上/* */，例如：
![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/106920260/dd430592-5d48-4ab7-91e1-0507661f7d83)
这样可以避免被hugo转译。
具体参考链接 [如何在代码块里内嵌 HUGO 的简码 (SHORTCODES)](https://tin6.com/post/how-to-escape-hugo-shortcodes-within-hugo-markdown/)

**Comment by Xalaok** [comment]
> 在尖括号内加上/* */，例如： ![image](https://user-images.githubusercontent.com/106920260/257715711-dd430592-5d48-4ab7-91e1-0507661f7d83.png) 这样可以避免被hugo转译。 具体参考链接 [如何在代码块里内嵌 HUGO 的简码 (SHORTCODES)](https://tin6.com/post/how-to-escape-hugo-shortcodes-within-hugo-markdown/)

OK 谢谢
