### ISSUE TITLE
[Bug]: don't have the example config.yaml file

### ISSUE THREAD

**Issue by laosji** [CaiJimmy/hugo-theme-stack#851]
### What happened?

[Bug]: don't have the example config.yaml file

### Hugo version

newest

### Theme version

newest

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

Chrome104

### Relevant log output

```shell
don't have the example config.yaml file
```

### Link to the page with bug

https://demo.stack.jimmycai.com

**Comment by lin-snow** [comment]
在主题的exampleSite里面，把他拷贝到根目录
