### ISSUE TITLE
希望大佬可以适配一下Gridea

### ISSUE THREAD

**Issue by suweiru** [CaiJimmy/hugo-theme-stack#86]
hugo hexo这样的纯代码工具对于非程序员来说，实在是太麻烦了点。
Gridea的可视化操作就简单多了，适配Gridea会让更多人用上这个漂亮的主题！
非常感谢！

**Comment by CaiJimmy** [comment]
抱歉 😅，我没有用过 Gridea，也暂时没有时间去适配别的平台。
