### ISSUE TITLE
Artalk comment Support

### ISSUE THREAD

**Issue by lin-snow** [CaiJimmy/hugo-theme-stack#896]
### What happened?

can you update the theme to support the new comment way-artalk.
there is a doc- https://artalk.js.org/

thanks.

### Hugo version

lastest

### Theme version

lastest

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

latest,latest

### Link to Minimal Reproducible Example

https://github.com/CaiJimmy/hugo-theme-stack

**Comment by mansoorbarri** [comment]
can this issue be assigned to me?
