### ISSUE TITLE
希望可以增加深色模式的手动开关

### ISSUE THREAD

**Issue by PwnerZhang** [CaiJimmy/hugo-theme-stack#9]
PC端上夜间模式自动开启的效果似乎不是很理想，所以建议增加一个深色模式的手动开关，便于在电脑上阅读的时候获得良好的体验。

**Comment by CaiJimmy** [comment]
你好，

我这两天尝试去实现了下 (#14)，但最后还是没有找到合适的切换方式，所以暂时不会添加这个功能。
