### ISSUE TITLE
搜索结果无法跳转到文章

### ISSUE THREAD

**Issue by imzhizi** [CaiJimmy/hugo-theme-stack#92]
搜索页面下，鼠标放在搜索结果上只会出现图片的链接，而不能导航到文章，浏览器是最新版的Edge。

![image](https://user-images.githubusercontent.com/38089699/103123857-a45aa080-46c0-11eb-9a0e-b6a94f7357e9.png)

**Comment by CaiJimmy** [comment]
谢谢反馈，已经修复
