### ISSUE TITLE
social menu在firefox、edge中无法正确显示，只能够在chrome中正常显示

### ISSUE THREAD

**Issue by okyq** [CaiJimmy/hugo-theme-stack#924]
### What happened?

social menu在firefox、edge中无法正确显示，只能够在chrome中正常显示。
不是个例，在访问其他stack主题依然有这样的情况
比较出名的用stack主题的博主：
https://jinli.io/
https://blog.linsnow.cn/
无一例外都无法在firefox或edge中显示social menu，只能在chrome中正常显示

### Hugo version

 v0.121.1

### Theme version

3.21.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### More information about the browser

firefox 121.0  win11

### Link to Minimal Reproducible Example

https://jinli.io/

**Comment by CaiJimmy** [comment]
> 无一例外都无法在firefox或edge中显示social menu，只能在chrome中正常显示

是被 uBlock 给封锁了。
