### ISSUE TITLE
页面标题未按预期生成

### ISSUE THREAD

**Issue by StrMnL** [CaiJimmy/hugo-theme-stack#941]
### What happened?

按照```layouts/partials/data/title.html```中所写
```
{{- if .IsHome -}}

    ....

    {{ if .Paginator.HasPrev }}
        {{ $title = printf "%s - %s" .Paginator $siteTitle }}
    {{ else }}
        {{ $title = $siteTitle}}
    {{ end }}
{{- else if eq .Kind "term" -}}

    ....

    {{ if .Paginator.HasPrev }}
        {{ $title = $title | append " - " .Paginator }}
    {{ end }} 

    ....

{{- end -}}
```
在存在分页的情况下，```home```页第二页起的页面标题应该形如```Pager 2 - Hugo Theme Stack Starter```

```term```页第二页起的页面标题应该形如```Tag: Test - Pager 2 - Hugo Theme Stack Starter```

但实际上这并不起作用。无论如何```.Paginator.HasPrev```恒为false。

### Hugo version

0.122.0

### Theme version

3.21.0

### Link to Minimal Reproducible Example

https://github.com/StrMnL/hugo-theme-stack-test/

**Comment by CaiJimmy** [comment]
Should be fixed now. Thanks for reporting this!
