### ISSUE TITLE
How to modify theme by using Hugo module?

### ISSUE THREAD

**Issue by MarkRushB** [CaiJimmy/hugo-theme-stack#944]
### What happened?

I went through the doc there, however it is not that clear, there is no theme directory originally, so which means I should create one manually then give it the correct file directories?

### Hugo version

None

### Theme version

None

### Link to Minimal Reproducible Example

None

**Comment by rmdhnreza** [comment]
Simply create that template in your local `layouts` directory.

For example,

```
/layouts/_default/single.html
```

would overwrite `single.html` template from the theme module.
