### ISSUE TITLE
Date format not showing correctly

### ISSUE THREAD

**Issue by wmbm** [CaiJimmy/hugo-theme-stack#947]
### What happened?

For some reason my dates on posts are showing as:

![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/15046836/9dde75eb-0bba-468b-9d75-b83395c9f537)

in my **index.md** files I do the following "`date: 2024-09-07`" as in the template. So I can't really tell what's going on? Any thoughts?

### Hugo version

0.122.0

### Theme version

3.21.0

### What browsers are you seeing the problem on?

Firefox

### Link to Minimal Reproducible Example

https://github.com/wmbm/wmbm.github.io

**Comment by CaiJimmy** [comment]
https://github.com/wmbm/wmbm.github.io/blob/7b9571968378d22b96b2f4f2d5b77954a392f747/config/_default/params.toml#L13-L14

You have changed the year (2006 -> 2024). The Golang date format follows a strict naming rule, these are not nonsense dates.

**Comment by wmbm** [comment]
Thanks for the quick response! Working now.
