### ISSUE TITLE
Favicon not displaying

### ISSUE THREAD

**Issue by wmbm** [CaiJimmy/hugo-theme-stack#948]
### What happened?

My params.toml file contains

```
# Output page's full content in RSS.
rssFullContent = true
favicon = "/img/favicon.ico"

```
and my favicon exists in the img folder, and yet it still doesn't appear in my browser tab?

Any tips?

### Hugo version

0.122.0

### Theme version

3.21.0

### Link to Minimal Reproducible Example

https://github.com/wmbm/wmbm.github.io

**Comment by rmdhnreza** [comment]
Move your `img` folder from `assets` to `static` the favicon should work.

**Comment by wmbm** [comment]
just tried this, but observed no change

**Comment by wmbm** [comment]
Ah got it now! For some reason a .ico file won't work but the .jpeg file works when in the static folder

**Comment by wmbm** [comment]
Thanks!
