### ISSUE TITLE
Cannot translate section title with given key

### ISSUE THREAD

**Issue by iozcelik** [CaiJimmy/hugo-theme-stack#95]
**I am new at Hugo. So may be this is not a bug or it is not related theme. I am not sure.**

I try to translate section title on layout but not succesed.
In single category or tag page, it shown in English: https://iozcelik.github.io/iozcelik/categories/yazilim/
However in archive page, it shown my translated language: https://iozcelik.github.io/iozcelik/archives/

Also when translating my language 
[`<h3 class="section-count">{{ T "list.page" (len .Pages) }}</h3>`](https://github.com/CaiJimmy/hugo-theme-stack/blob/464f4b1d3bc2bf2891f7b81db457b97de6aa2e62/layouts/_default/list.html#L12) ,
Hugo give a warning because it doesn't find in i18n. I add manuelly but I think it is wrong.

**Comment by cobalto** [comment]
Just noticed the same thing.
Don't know how to point to it on i18n file.

**Comment by CaiJimmy** [comment]
So, with the 2.0 version, I changed the behaviour of section title (#81). 
Now it's possible to rename each section title, by creating a `_index.md` file inside that section folder:

![image](https://user-images.githubusercontent.com/5889006/103161217-ad419400-47de-11eb-9afc-95bb6c20ea3b.png)
![image](https://user-images.githubusercontent.com/5889006/103161216-aa46a380-47de-11eb-9f0c-f69fb3d5b0f6.png)


> However in archive page, it shown my translated language: https://iozcelik.github.io/iozcelik/archives/

That will be changed. I've planned to remove that translation string and leave it to the user.

**Comment by CaiJimmy** [comment]
> Also when translating my language
> `<h3 class="section-count">{{ T "list.page" (len .Pages) }}</h3>` ,
> Hugo give a warning because it doesn't find in i18n. I add manuelly but I think it is wrong.

That's strange. Do you have a demo?

**Comment by iozcelik** [comment]
In single category, it shown in English.
![image](https://user-images.githubusercontent.com/10682780/103206966-32779680-490e-11eb-9fec-a98fd7594b5c.png)

But in archive page, it is Turkish.
![image](https://user-images.githubusercontent.com/10682780/103206992-415e4900-490e-11eb-9d6f-7837483c7cd5.png)

The repo for my site: https://github.com/iozcelik/iozcelik

> That's strange. Do you have a demo?

I fix it. It is local problem, I guess.

**Comment by CaiJimmy** [comment]
That will be changed in the following versions. Take a look at my comment at https://github.com/CaiJimmy/hugo-theme-stack/issues/95#issuecomment-751408872.

**Comment by iozcelik** [comment]
Ok but making it each tag or category is not best, I think. I just want translate.

**Comment by CaiJimmy** [comment]
Hugo supports more taxonomy than category & tag, plus custom sections. 

Translating each one of them is not a good idea / realistic.

**Comment by CaiJimmy** [comment]
> making it each tag or category

Not for each tag or category. That title is inherited from its section. Hence it's only defined once per section (category/tag).

**Comment by iozcelik** [comment]
> Not for each tag or category. That title is inherited from its section. Hence it's only defined once per section (category/tag).

Yes, true. And I said same. But if I do not create _index.md, how translate "category" and "tags" words?

**Comment by CaiJimmy** [comment]
> But if I do not create _index.md, how translate "category" and "tags" words?

You can't.
