### ISSUE TITLE
X-Content-Type-Options Header is not set.

### ISSUE THREAD

**Issue by ofgrenudo** [CaiJimmy/hugo-theme-stack#959]
### What happened?

+ /: The X-Content-Type-Options header is not set. This could allow the user agent to render the content of the site in a different fashion to the MIME type. See: https://www.invicti.com/web-vulnerability-scanner/vulnerabilities/missing-content-type-header/

### Hugo version

0.115.2

### Theme version

v3.21.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Link to Minimal Reproducible Example

https://unorthodoxdev.net

**Comment by rmdhnreza** [comment]
This should be settings on the server, no?

**Comment by CaiJimmy** [comment]
I agree with @rmdhnreza, this header should be set on the server since it's an HTTP thing and this theme has no control over it.
