### ISSUE TITLE
Featured image of post 无法显示

### ISSUE THREAD

**Issue by topanic** [CaiJimmy/hugo-theme-stack#971]
### What happened?

![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/158149038/859179ac-b6d4-4f7b-a5ef-79b77bf2a9ad)

如图所示，图片无法显示

### Hugo version

hugo v0.123.8+extended linux/amd64 BuildDate=unknown

### Theme version

latest

### What browsers are you seeing the problem on?

Firefox, Chrome

### Link to Minimal Reproducible Example

https://github.com/topanic/hugo-site

**Comment by topanic** [comment]
![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/158149038/724142a9-d421-437d-8a96-a0333728d5e7)
![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/158149038/be95bf44-84df-457c-8ddc-01e81bd9f430)
![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/158149038/182fee02-ba66-4666-b958-6aceb4b3fbd9)

博客里面使用markdown语法添加本地图片也无法显示

**Comment by CaiJimmy** [comment]
https://stack.jimmycai.com/writing/markdown

`jupyterhub.md` -> `index.md`

**Comment by topanic** [comment]
问题解决了谢谢
