### ISSUE TITLE
site-avatar无法正常显示

### ISSUE THREAD

**Issue by pplmx** [CaiJimmy/hugo-theme-stack#977]
### What happened?

除了首页, 其他页面全部无法显示

### Hugo version

0.123.7

### Theme version

3.24.1

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

Chrome 122.0.6261.112, Win11

### Relevant log output

```shell
Here is my config:


# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["posts"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "images/favicon.png"

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "🍥"
subtitle = "To infinity and beyond."

[sidebar.avatar]
enabled = true
local = false
src = "images/favicon.png"
```

### Link to Minimal Reproducible Example

https://yoooo.fun

**Comment by CaiJimmy** [comment]
参考 https://github.com/CaiJimmy/hugo-theme-stack-starter/ 把头像放到 `assets` 文件夹下，然后 `local = true`

或者改成 `src = "/images/favicon.png"`

**Comment by pplmx** [comment]
@CaiJimmy 

谢谢q(≧▽≦q)
