### ISSUE TITLE
Unmarshal failed: Near line 0 (last key parsed ''): bare keys cannot contain ':'

### ISSUE THREAD

**Issue by AbhinavMir** [CaiJimmy/hugo-theme-stack#98]
**Describe the bug**
```shell
Error: "<directory>\config.toml:1:1": unmarshal failed: Near line 0 (last key parsed ''): bare keys cannot contain ':'
```

**To Reproduce**
1. Hugo Quickstart
2. Git clone the theme to theme
3. `hugo server -D`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: Hugo Static Site Generator v0.55.6-A5D4C82D windows/amd64 BuildDate: 2019-05-18T07:57:00Z

**Comment by jo-hnny** [comment]
you can rename config.toml to config.yaml
https://gist.github.com/oconnor663/9aeb4ed56394cb013a20

**Comment by CaiJimmy** [comment]
> Hugo Static Site Generator v0.55.6-A5D4C82D windows/amd64 BuildDate: 2019-05-18T07:57:00Z

https://docs.stack.jimmycai.com/getting-started

**Hugo ≥ 0.78.0** is required

**Comment by AbhinavMir** [comment]
Thank you. My Search is not working, any idea what could be the reason?

**Comment by AbhinavMir** [comment]
Thank you! Your theme is beautiful!
