### ISSUE TITLE
content/page/links.image 在非站点默认语言下无法加载本地图片

### ISSUE THREAD

**Issue by HumXC** [CaiJimmy/hugo-theme-stack#982]
### What happened?

在 content/page/links 中 创建非默认语言的 index.***.md，并在其中声明 image。在页面中切换到那个语言后，links 页面声明的图片无法被加载，查看控制台输出 `GET http://localhost:1313/zh-cn/links/image-name.jpg 404 (Not Found)`

![image](https://github.com/CaiJimmy/hugo-theme-stack/assets/71064270/658e5cec-defd-48ab-9119-1d57bff68d9b)

# 复现步骤

我会在 'Link to Minimal Reproducible Example' 粘贴上我的仓库，但考虑到我未来大概会删除那个仓库，所以我在此写出复现步骤。

假设当前在一个空文件夹下

```bash
git clone --branch v3.24.2 https://github.com/CaiJimmy/hugo-theme-stack.git
mkdir themes
mv hugo-theme-stack themes/
# 使用 exampleSite 运行站点
cp -r themes/hugo-theme-stack/exampleSite/* ./
cp content/page/links/index.md content/page/links/index.zh-cn.md
hugo server
```

访问页面，点击 'Links'，在 links 页面切换为中文，即可看到 TS 的本地图片无法加载，如上图所示

### Hugo version

v0.123.8

### Theme version

v3

### What browsers are you seeing the problem on?

Chrome

### More information about the browser

 Chromium: 122.0.6261.111（正式版本） （64 位）

### Link to Minimal Reproducible Example

https://github.com/HumXC/hugo-theme-stack-issue

**Comment by CaiJimmy** [comment]
Fixed, thanks for your feedback!

**Comment by ttheng3810** [comment]
Hi, I recently encountered the same issue, this time being a normal blog post page (under the `content/post/` folder) with English being the non-default language (`index.en.md`), and a similar 404 error being thrown.

![Screenshot from 2024-07-22](https://github.com/user-attachments/assets/1a99ccc7-6888-4d61-853a-03fc6626d0b4)

Hugo version: v0.126.1 extended
Theme version: v3.26.0
Browser used: Firefox 128.0 (64-bit) on Pop!_OS
