### ISSUE TITLE
Feature Request: Support GitInfo in LastModified 

### ISSUE THREAD

**Issue by delize** [CaiJimmy/hugo-theme-stack#985]
### What happened?

Currently, Hugo supports last modified timestamps for Blog Posts using Git: https://gohugo.io/methods/page/gitinfo/

However, it doesn't seem like this is natively supported in the Stack theme. When enabled or added to: https://github.com/CaiJimmy/hugo-theme-stack-starter/blob/master/config/_default/config.toml

Using: https://gohugo.io/getting-started/configuration/#configure-dates

This appears to cause issues when creating new blog posts or modifications due to the syntax being used across the blog theme. 

It would be nice if this was fully supported - so that people wouldn't have to rely on manually inputting last modified dates.

### Hugo version

0.120

### Theme version

3.24.2

### Link to Minimal Reproducible Example

https://github.com/CaiJimmy/hugo-theme-stack-starter

**Comment by sailingsky** [comment]
I have same problem

**Comment by delize** [comment]
@sailingsky this could be a different problem. See the pinned issue. 
https://github.com/CaiJimmy/hugo-theme-stack/issues/974


This issue is more for architectural changes to incorporate last modified, determine how syntax should appear and where when gitinfo is enabled, etc. 

One can of course enable Gitinfo, but, there were all sorts of issues getting it to work / format cleanly without altering mass amounts of code.

**Comment by sailingsky** [comment]
> @sailingsky this could be a different problem. See the pinned issue. #974
> 
> This issue is more for architectural changes to incorporate last modified, determine how syntax should appear and where when gitinfo is enabled, etc.
> 
> One can of course enable Gitinfo, but, there were all sorts of issues getting it to work / format cleanly without altering mass amounts of code.

thx, I fixed it.

**Comment by CaiJimmy** [comment]
I have tested the starter template locally with `enableGitInfo = true` enabled and it seems to work fine. It seems to be related to the CI configuration of the starter template. I believe this issue can be resolved by https://github.com/CaiJimmy/hugo-theme-stack-starter/pull/39

I'm going to close this issue and merge this pull request. Feel free to reopen it if this solution does not work.
