### ISSUE TITLE
文章底部【最后修改于】无法显示？

### ISSUE THREAD

**Issue by Hansen1018** [CaiJimmy/hugo-theme-stack#986]
### What happened?

我在hugo.yaml和主题目录下config.yaml文件增加
```
frontmatter:
  lastmod: [":fileModTime", "lastmod"]
```
或者
```
enableGitInfo: true

frontmatter:
  lastmod: ['lastmod', ':git', 'date', 'publishDate']
```
仍然无法显示文章最后修改于，请教是什么问题？

### Hugo version

0.124.1

### Theme version

3.24.2

### What browsers are you seeing the problem on?

Microsoft Edge

### Link to Minimal Reproducible Example

1

**Comment by CaiJimmy** [comment]
Could be a duplicate of #985 

If you are using the starter template, this should be fixed with https://github.com/CaiJimmy/hugo-theme-stack-starter/pull/39

I'm closing this issue for now. Please check if this solution works and if not, feel free to reopen this issue.
